// Code generated by goplus from closeonce.gp. DO NOT EDIT.
//goplus:v v0.24.1

// Package closeonce makes Close idempotent: the first Close runs the
// teardown and caches its error; every later Close returns that same error
// without re-running teardown. Nil-receiver tolerant, so wrapper types can
// expose guard-free Close methods.
//
// Authored in Go+ and distributed as generated Go — consumers never need
// the goplus toolchain.
package closeonce

import "sync"

// Closer wraps a teardown function. The zero value is usable once F is set;
// construct with New for clarity.
type Closer struct {
	once sync.Once
	f    func() error
	err  error
}

// New wraps f.
func New(f func() error) *Closer {
	return &Closer{f: f}
}

// Close runs the teardown exactly once and returns its error; subsequent
// calls return the cached error. Safe on a nil *Closer (returns nil) and
// with a nil teardown (no-op).
func (c *Closer) Close() error {
	if c == nil {
		return nil
	}
	c.once.Do(func() {
		if c.f != nil {
			c.err = c.f()
		}
	})
	return c.err
}
