// Code generated by goplus from cas.gp. DO NOT EDIT.
//goplus:v v0.25.0

// Package cas provides a typed compare-and-swap vocabulary for stores whose
// values may change between observation and mutation.
package cas

// Observation binds a key to the version and value seen by a reader.
// Backends must compare Version atomically when Apply is attempted.
type Observation[K comparable, V any] struct {
	Key     K
	Version string
	Value   V
	Exists  bool
}

// Result describes every outcome of a compare-and-swap operation.
//
//goplus:enum Result[V any]
type Result[V any] interface{ isResult(V) }

//goplus:variant (Result[V]) Updated(value V, version string)
type Updated[V any] struct {
	Value   V
	Version string
}

func (Updated[V]) isResult(V) {}

//goplus:variant (Result[V]) Changed(actual V, version string)
type Changed[V any] struct {
	Actual  V
	Version string
}

func (Changed[V]) isResult(V) {}

//goplus:variant (Result[V]) Missing()
type Missing[V any] struct{}

func (Missing[V]) isResult(V) {}

// ResultCases selects one handler per Result variant for Fold.
type ResultCases[V any, R any] struct {
	Updated func(value V, version string) R
	Changed func(actual V, version string) R
	Missing func() R
}

// Fold reduces Result[V] by one-level case analysis.
func Fold[V any, R any](v Result[V], cs ResultCases[V, R]) R {
	switch m := any(v).(type) {
	case Updated[V]:
		return cs.Updated(m.Value, m.Version)
	case Changed[V]:
		return cs.Changed(m.Actual, m.Version)
	case Missing[V]:
		return cs.Missing()
	default:
		panic("goplus: impossible enum value in Fold")
	}
}

// Store is the minimal backend contract. Implementations define their version
// representation; callers treat it as opaque.
type Store[K comparable, V any] interface {
	Observe(K) (Observation[K, V], error)
	Apply(Observation[K, V], V) (Result[V], error)
}
