Feature: Law tests are generated by default
  Every instance whose class closure declares laws and whose type argument
  is concrete gets a generated <file>_gpp_laws_test.go with rapid
  properties exercising every inherited law (through the upcasts).
  Knobs, via //gpp:laws on the instance: `off` suppresses; generic
  instances are skipped unless given explicit instantiations
  (`//gpp:laws [int] [string]`); `gen=Name` selects a custom rapid
  generator. Law tests are generated output: gen -check covers them and
  orphaned ones are removed.

  Background:
    Given a module "example.com/demo" using rapid for law tests

  Scenario: Default-on generation, inherited laws, off, and generic opt-in
    Given a G++ file "main.gpp":
      """
      package main

      import (
      	"fmt"
      	"reflect"
      )

      type Semigroup[T any] class {
      	Combine(a, b T) T
      	law Assoc(a, b, c T) { return reflect.DeepEqual(Combine(Combine(a, b), c), Combine(a, Combine(b, c))) }
      }

      type Monoid[T any] class {
      	Semigroup[T]
      	Empty() T
      	law LeftId(a T) { return reflect.DeepEqual(Combine(Empty(), a), a) }
      }

      instance IntAdd Monoid[int] {
      	Combine(a, b int) int { return a + b }
      	Empty() int { return 0 }
      }

      //gpp:laws off
      instance IntMul Monoid[int] {
      	Combine(a, b int) int { return a * b }
      	Empty() int { return 1 }
      }

      //gpp:laws [int] [string]
      instance SliceConcat[T any] Monoid[[]T] {
      	Combine(a, b []T) []T { return append(append([]T{}, a...), b...) }
      	Empty() []T { return nil }
      }

      func main() { fmt.Println("ok") }
      """
    When I run gpp with arguments "gen ."
    Then the exit code is 0
    And the file "main_gpp_laws_test.go" contains:
      """
      func TestIntAddLaws(t *testing.T) {
      	t.Run("Monoid.LeftId", func(t *testing.T) {
      		rapid.Check(t, func(rt *rapid.T) {
      			a := rapid.Make[int]().Draw(rt, "a")
      			if !IntAdd.LawLeftId(a) {
      				rt.Fatalf("law LeftId violated: a=%v", a)
      			}
      		})
      	})
      	t.Run("Semigroup.Assoc", func(t *testing.T) {
      		rapid.Check(t, func(rt *rapid.T) {
      			a := rapid.Make[int]().Draw(rt, "a")
      			b := rapid.Make[int]().Draw(rt, "b")
      			c := rapid.Make[int]().Draw(rt, "c")
      			if !IntAdd.AsSemigroup().LawAssoc(a, b, c) {
      				rt.Fatalf("law Assoc violated: a=%v b=%v c=%v", a, b, c)
      			}
      		})
      	})
      }
      """
    And the file "main_gpp_laws_test.go" contains:
      """
      	t.Run("Monoid.LeftId[string]", func(t *testing.T) {
      		rapid.Check(t, func(rt *rapid.T) {
      			a := rapid.Make[[]string]().Draw(rt, "a")
      			if !SliceConcat[string]().LawLeftId(a) {
      """
    When I run gpp with arguments "test ."
    Then the exit code is 0

  Scenario: The generated law tests do not mention an off instance
    Given a G++ file "main.gpp":
      """
      package main

      import (
      	"fmt"
      	"reflect"
      )

      type Semigroup[T any] class {
      	Combine(a, b T) T
      	law Assoc(a, b, c T) { return reflect.DeepEqual(Combine(Combine(a, b), c), Combine(a, Combine(b, c))) }
      }

      instance IntAdd Semigroup[int] {
      	Combine(a, b int) int { return a + b }
      }

      //gpp:laws off
      instance IntSub Semigroup[int] {
      	Combine(a, b int) int { return a - b }
      }

      func main() { fmt.Println("ok") }
      """
    When I run gpp with arguments "gen ."
    Then the exit code is 0
    And the file "main_gpp_laws_test.go" contains:
      """
      func TestIntAddLaws(t *testing.T) {
      """

  Scenario: A law-violating instance fails gpp test with a counterexample
    Given a G++ file "main.gpp":
      """
      package main

      import (
      	"fmt"
      	"reflect"
      )

      type Semigroup[T any] class {
      	Combine(a, b T) T
      	law Assoc(a, b, c T) { return reflect.DeepEqual(Combine(Combine(a, b), c), Combine(a, Combine(b, c))) }
      }

      instance BadSub Semigroup[int] {
      	Combine(a, b int) int { return a - b }
      }

      func main() { fmt.Println("ok") }
      """
    When I run gpp with arguments "gen ."
    Then the exit code is 0
    When I run gpp with arguments "test ."
    Then the exit code is 1
    And stdout contains "law Assoc violated"

  Scenario: Law tests are covered by gen -check and orphan removal
    Given a G++ file "main.gpp":
      """
      package main

      import (
      	"fmt"
      	"reflect"
      )

      type Semigroup[T any] class {
      	Combine(a, b T) T
      	law Assoc(a, b, c T) { return reflect.DeepEqual(Combine(Combine(a, b), c), Combine(a, Combine(b, c))) }
      }

      instance IntAdd Semigroup[int] {
      	Combine(a, b int) int { return a + b }
      }

      func main() { fmt.Println("ok") }
      """
    When I run gpp with arguments "gen ."
    Then the exit code is 0
    When I run gpp with arguments "gen -check ."
    Then the exit code is 0
    Given a G++ file "main.gpp":
      """
      package main

      import "fmt"

      type Semigroup[T any] class {
      	Combine(a, b T) T
      }

      instance IntAdd Semigroup[int] {
      	Combine(a, b int) int { return a + b }
      }

      func main() { fmt.Println("ok") }
      """
    When I run gpp with arguments "gen ."
    Then the exit code is 0
    And the file "main_gpp_laws_test.go" does not exist

  Scenario: A law over an enum parameter draws through the derived generator
    Given a module "example.com/demo" using rapid for law tests
    And a G++ file "main.gpp":
      """
      package main

      type Mode enum {
      	Fast
      	Careful(retries int)
      }

      type Runner[T any] class {
      	Run(host T, m Mode) int
      	law NonNegative(host T, m Mode) {
      		return Run(host, m) >= 0
      	}
      }

      type good struct{}

      instance Good Runner[good] {
      	Run(host good, m Mode) int {
      		match m {
      		case Fast():
      			return 1
      		case Careful(r):
      			if r < 0 {
      				return 0
      			}
      			return r
      		}
      		return 0
      	}
      }

      type bad struct{}

      instance Bad Runner[bad] {
      	Run(host bad, m Mode) int {
      		match m {
      		case Fast():
      			return 1
      		case Careful(r):
      			return r
      		}
      		return 0
      	}
      }

      func main() {}
      """
    When I run gpp with arguments "gen ."
    Then the exit code is 0
    And the file "main_gpp_laws_test.go" contains:
      """
      func GenMode(t *rapid.T) Mode {
      """
    When I run gpp with arguments "test ."
    Then the exit code is 1
    And stdout contains "law NonNegative violated"
