// Code generated by goplus from schedule.gp. DO NOT EDIT.
//goplus:v v0.25.0

// Package schedule provides immutable grammar-indexed calendar schedules.
package schedule

import "time"

//goplus:enum Grammar
type Grammar interface{ isGrammar() }

//goplus:variant (Grammar) StandardGrammar()
type StandardGrammar struct{}

func (StandardGrammar) isGrammar() {}

//goplus:variant (Grammar) SecondsGrammar()
type SecondsGrammar struct{}

func (SecondsGrammar) isGrammar() {}

// GrammarCases selects one handler per Grammar variant for GrammarFold.
type GrammarCases[R any] struct {
	StandardGrammar func() R
	SecondsGrammar  func() R
}

// GrammarFold reduces Grammar by one-level case analysis.
func GrammarFold[R any](g Grammar, cs GrammarCases[R]) R {
	switch any(g).(type) {
	case StandardGrammar:
		return cs.StandardGrammar()
	case SecondsGrammar:
		return cs.SecondsGrammar()
	default:
		panic("goplus: impossible enum value in GrammarFold")
	}
}

// GrammarEqOverrides carries optional per-variant hooks for GrammarEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type GrammarEqOverrides struct {
	StandardGrammar func(x, y StandardGrammar) (eq, handled bool)
	SecondsGrammar  func(x, y SecondsGrammar) (eq, handled bool)
}

// GrammarEqualWith reports structural equality of a and b under ov.
func GrammarEqualWith(a, b Grammar, ov GrammarEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case StandardGrammar:
		y, ok := any(b).(StandardGrammar)
		if !ok {
			return false
		}
		if ov.StandardGrammar != nil {
			if eq, handled := ov.StandardGrammar(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case SecondsGrammar:
		y, ok := any(b).(SecondsGrammar)
		if !ok {
			return false
		}
		if ov.SecondsGrammar != nil {
			if eq, handled := ov.SecondsGrammar(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// GrammarEqual reports structural equality of a and b.
func GrammarEqual(a, b Grammar) bool {
	return GrammarEqualWith(a, b, GrammarEqOverrides{})
}

// FieldSet[d] is a nonempty subset of a finite domain of size d.
//
//goplus:enum FieldSet[d nat]
//goplus:derive off
type FieldSet interface{ isFieldSet() }

//goplus:variant (FieldSet) fieldSetValue(Mask uint64) FieldSet[d]
type fieldSetValue struct {
	mask uint64
}

func (fieldSetValue) isFieldSet() {}

// Schedule[f] records the grammar field count: standard schedules have five
// fields and seconds-enabled schedules have six.
//
//goplus:enum Schedule[f nat]
//goplus:derive off
type Schedule interface{ isSchedule() }

//goplus:variant (Schedule) calendarValue(Grammar Grammar, Second FieldSet[60], Minute FieldSet[60], Hour FieldSet[24], DayOfMonth FieldSet[31], Month FieldSet[12], DayOfWeek FieldSet[7], Location *time.Location, DomWildcard bool, DowWildcard bool) Schedule[f]
type calendarValue struct {
	grammar     Grammar
	second      FieldSet
	minute      FieldSet
	hour        FieldSet
	dayOfMonth  FieldSet
	month       FieldSet
	dayOfWeek   FieldSet
	location    *time.Location
	domWildcard bool
	dowWildcard bool
}

func (calendarValue) isSchedule() {}

//goplus:variant (Schedule) delayValue(Grammar Grammar, Delay time.Duration, Location *time.Location) Schedule[f]
type delayValue struct {
	grammar  Grammar
	delay    time.Duration
	location *time.Location
}

func (delayValue) isSchedule() {}

type ParseError struct{ Message string }

func (e ParseError) Error() string { return e.Message }

//goplus:enum ParseResult[f nat]
type ParseResult interface{ isParseResult() }

//goplus:variant (ParseResult) Parsed(Value Schedule[f])
type Parsed struct {
	Value Schedule
}

func (Parsed) isParseResult() {}

//goplus:variant (ParseResult) Rejected(Error ParseError)
type Rejected struct {
	Error ParseError
}

func (Rejected) isParseResult() {}

// ParseResultCases selects one handler per ParseResult variant for ParseResultFold.
type ParseResultCases[R any] struct {
	Parsed   func(Value Schedule) R
	Rejected func(Error ParseError) R
}

// ParseResultFold reduces ParseResult by one-level case analysis.
func ParseResultFold[R any](p ParseResult, cs ParseResultCases[R]) R {
	switch m := any(p).(type) {
	case Parsed:
		return cs.Parsed(m.Value)
	case Rejected:
		return cs.Rejected(m.Error)
	default:
		panic("goplus: impossible enum value in ParseResultFold")
	}
}

// SomeSchedule is the finite existential grammar boundary for runtime input.
//
//goplus:enum SomeSchedule
type SomeSchedule interface{ isSomeSchedule() }

//goplus:variant (SomeSchedule) StandardSchedule(Value Schedule[5])
type StandardSchedule struct {
	Value Schedule
}

func (StandardSchedule) isSomeSchedule() {}

//goplus:variant (SomeSchedule) SecondsSchedule(Value Schedule[6])
type SecondsSchedule struct {
	Value Schedule
}

func (SecondsSchedule) isSomeSchedule() {}

// SomeScheduleCases selects one handler per SomeSchedule variant for SomeScheduleFold.
type SomeScheduleCases[R any] struct {
	StandardSchedule func(Value Schedule) R
	SecondsSchedule  func(Value Schedule) R
}

// SomeScheduleFold reduces SomeSchedule by one-level case analysis.
func SomeScheduleFold[R any](s SomeSchedule, cs SomeScheduleCases[R]) R {
	switch m := any(s).(type) {
	case StandardSchedule:
		return cs.StandardSchedule(m.Value)
	case SecondsSchedule:
		return cs.SecondsSchedule(m.Value)
	default:
		panic("goplus: impossible enum value in SomeScheduleFold")
	}
}

//goplus:enum DynamicParse
type DynamicParse interface{ isDynamicParse() }

//goplus:variant (DynamicParse) DynamicallyParsed(Value SomeSchedule)
type DynamicallyParsed struct {
	Value SomeSchedule
}

func (DynamicallyParsed) isDynamicParse() {}

//goplus:variant (DynamicParse) DynamicRejected(Error ParseError)
type DynamicRejected struct {
	Error ParseError
}

func (DynamicRejected) isDynamicParse() {}

// DynamicParseCases selects one handler per DynamicParse variant for DynamicParseFold.
type DynamicParseCases[R any] struct {
	DynamicallyParsed func(Value SomeSchedule) R
	DynamicRejected   func(Error ParseError) R
}

// DynamicParseFold reduces DynamicParse by one-level case analysis.
func DynamicParseFold[R any](d DynamicParse, cs DynamicParseCases[R]) R {
	switch m := any(d).(type) {
	case DynamicallyParsed:
		return cs.DynamicallyParsed(m.Value)
	case DynamicRejected:
		return cs.DynamicRejected(m.Error)
	default:
		panic("goplus: impossible enum value in DynamicParseFold")
	}
}

//goplus:enum NextResult
type NextResult interface{ isNextResult() }

//goplus:variant (NextResult) NextAt(Time time.Time)
type NextAt struct {
	Time time.Time
}

func (NextAt) isNextResult() {}

//goplus:variant (NextResult) NoNext(Reason string)
type NoNext struct {
	Reason string
}

func (NoNext) isNextResult() {}

// NextResultCases selects one handler per NextResult variant for NextResultFold.
type NextResultCases[R any] struct {
	NextAt func(Time time.Time) R
	NoNext func(Reason string) R
}

// NextResultFold reduces NextResult by one-level case analysis.
func NextResultFold[R any](n NextResult, cs NextResultCases[R]) R {
	switch m := any(n).(type) {
	case NextAt:
		return cs.NextAt(m.Time)
	case NoNext:
		return cs.NoNext(m.Reason)
	default:
		panic("goplus: impossible enum value in NextResultFold")
	}
}

// NextResultEqOverrides carries optional per-variant hooks for NextResultEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type NextResultEqOverrides struct {
	NextAt func(x, y NextAt) (eq, handled bool)
	NoNext func(x, y NoNext) (eq, handled bool)
}

// NextResultEqualWith reports structural equality of a and b under ov.
func NextResultEqualWith(a, b NextResult, ov NextResultEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case NextAt:
		y, ok := any(b).(NextAt)
		if !ok {
			return false
		}
		if ov.NextAt != nil {
			if eq, handled := ov.NextAt(x, y); handled {
				return eq
			}
		}
		if x.Time != y.Time {
			return false
		}
		return true
	case NoNext:
		y, ok := any(b).(NoNext)
		if !ok {
			return false
		}
		if ov.NoNext != nil {
			if eq, handled := ov.NoNext(x, y); handled {
				return eq
			}
		}
		if x.Reason != y.Reason {
			return false
		}
		return true
	}
	return false
}

// NextResultEqual reports structural equality of a and b.
func NextResultEqual(a, b NextResult) bool {
	return NextResultEqualWith(a, b, NextResultEqOverrides{})
}

//goplus:dep ParseStandard(spec string) ParseResult[5]
func ParseStandard(spec string) ParseResult {
	value, err := parseCalendar(spec, false, time.Local)
	if err != nil {
		return Rejected{Error: ParseError{Message: err.Error()}}
	}
	return Parsed{Value: value}
}

//goplus:dep ParseStandardInLocation(spec string, location *time.Location) ParseResult[5]
func ParseStandardInLocation(spec string, location *time.Location) ParseResult {
	value, err := parseCalendar(spec, false, location)
	if err != nil {
		return Rejected{Error: ParseError{Message: err.Error()}}
	}
	return Parsed{Value: value}
}

//goplus:dep ParseSeconds(spec string) ParseResult[6]
func ParseSeconds(spec string) ParseResult {
	value, err := parseCalendar(spec, true, time.Local)
	if err != nil {
		return Rejected{Error: ParseError{Message: err.Error()}}
	}
	return Parsed{Value: value}
}

//goplus:dep ParseSecondsInLocation(spec string, location *time.Location) ParseResult[6]
func ParseSecondsInLocation(spec string, location *time.Location) ParseResult {
	value, err := parseCalendar(spec, true, location)
	if err != nil {
		return Rejected{Error: ParseError{Message: err.Error()}}
	}
	return Parsed{Value: value}
}

func ParseDynamic(spec string, grammar Grammar) DynamicParse {
	switch any(grammar).(type) {
	case StandardGrammar:

		switch __gp_m1 := any(ParseStandard(spec)).(type) {
		case Parsed:
			value := __gp_m1.Value
			return DynamicallyParsed{Value: StandardSchedule{Value: value}}
		case Rejected:
			error := __gp_m1.Error
			return DynamicRejected{Error: error}
		default:
			panic("goplus: impossible enum value in match")
		}
	case SecondsGrammar:

		switch __gp_m2 := any(ParseSeconds(spec)).(type) {
		case Parsed:
			value := __gp_m2.Value
			return DynamicallyParsed{Value: SecondsSchedule{Value: value}}
		case Rejected:
			error := __gp_m2.Error
			return DynamicRejected{Error: error}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep NextStandard(schedule Schedule[5], after time.Time) NextResult
func NextStandard(schedule Schedule, after time.Time) NextResult {
	return nextCalendar(schedule, StandardGrammar{}, after)
}

//goplus:dep NextSeconds(schedule Schedule[6], after time.Time) NextResult
func NextSeconds(schedule Schedule, after time.Time) NextResult {
	return nextCalendar(schedule, SecondsGrammar{}, after)
}

//goplus:dep newFieldSet(domain nat, mask uint64) FieldSet[domain]
func newFieldSet(domain int, mask uint64) FieldSet {
	if domain <= 0 || domain > 64 {
		panic("schedule: invalid field domain")
	}
	if mask == 0 {
		panic("schedule: empty field set")
	}
	if domain < 64 && mask>>uint(domain) != 0 {
		panic("schedule: field bit outside domain")
	}
	return fieldSetValue{mask: mask}
}

//goplus:dep newCalendar(0 fields nat, grammar Grammar, second uint64, minute uint64, hour uint64, dayOfMonth uint64, month uint64, dayOfWeek uint64, location *time.Location, domWildcard bool, dowWildcard bool) Schedule[fields]
func newCalendar(grammar Grammar, second, minute, hour, dayOfMonth, month, dayOfWeek uint64, location *time.Location, domWildcard, dowWildcard bool) Schedule {
	if location == nil {
		panic("schedule: nil location")
	}
	return calendarValue{grammar: grammar, second: newFieldSet(60, second), minute: newFieldSet(60, minute), hour: newFieldSet(24, hour), dayOfMonth: newFieldSet(31, dayOfMonth), month: newFieldSet(12, month), dayOfWeek: newFieldSet(7, dayOfWeek), location: location, domWildcard: domWildcard, dowWildcard: dowWildcard}
}

//goplus:dep newDelay(0 fields nat, grammar Grammar, delay time.Duration, location *time.Location) Schedule[fields]
func newDelay(grammar Grammar, delay time.Duration, location *time.Location) Schedule {
	if delay <= 0 {
		panic("schedule: non-positive delay")
	}
	if location == nil {
		panic("schedule: nil location")
	}
	return delayValue{grammar: grammar, delay: delay, location: location}
}
