// Code generated by goplus from memo.gp. DO NOT EDIT.
//goplus:v v0.18.0

// Package memo is a concurrent compute-once cache: the first Get for a key
// runs the compute function OUTSIDE any lock, then publishes with
// first-writer-wins pointer identity — every caller for a key observes the
// SAME value, and a losing concurrent compute is discarded. The shape every
// compile cache hand-rolls.
//
// Authored in Go+ and distributed as generated Go — consumers never need
// the goplus toolchain.
package memo

import "sync"

// Cache memoizes K → V. The zero value is usable. V is typically a pointer
// or interface; identity of the winning value is preserved.
type Cache[K comparable, V any] struct {
	m sync.Map // K -> V
}

// Get returns the cached value for k, or runs compute and caches its
// result. compute runs outside any lock, so concurrent first calls for the
// same key MAY each run compute; exactly one result wins (LoadOrStore) and
// all callers receive the winner. A compute error caches NOTHING — the next
// Get retries.
func (c *Cache[K, V]) Get(k K, compute func() (V, error)) (V, error) {
	if v, ok := c.m.Load(k); ok {
		return v.(V), nil
	}
	v, err := compute()
	if err != nil {
		var zero V
		return zero, err
	}
	actual, _ := c.m.LoadOrStore(k, v)
	return actual.(V), nil
}

// Peek returns the cached value without computing.
func (c *Cache[K, V]) Peek(k K) (V, bool) {
	if v, ok := c.m.Load(k); ok {
		return v.(V), true
	}
	var zero V
	return zero, false
}

// Len counts cached entries (O(n); diagnostic use).
func (c *Cache[K, V]) Len() int {
	n := 0
	c.m.Range(func(any, any) bool { n++; return true })
	return n
}
