// Code generated by goplus from algebra.gp. DO NOT EDIT.
//goplus:v v0.25.0

// Package algebra is the Go+ algebraic hierarchy: eight classes from
// Magma to Group, related by embedding, with each structure's laws
// declared exactly where the structure earns them.
//
// An algebraic structure here is what it is in mathematics: a carrier
// set (the instantiating type T) together with one or more operations on
// it, satisfying stated laws. An instance names one concrete structure —
// the carrier, its operations, and (by passing the generated law tests)
// evidence for its laws. Instances are law-tested by default; the
// generated tests live in the nested lawtest module so this package
// keeps zero dependencies.
//
//goplus:laws out=lawtest
package algebra

import "reflect"

// Magma is a pair (T, Combine): a nonempty carrier set T with a closed
// binary operation Combine: T × T → T. Nothing more is promised —
// closure is the type system's job, and no laws apply.
//
//goplus:class Magma[T any]
type Magma[T any] struct {
	Combine func(a, b T) T
}

// UnitalMagma is a triple (T, Combine, Empty): a magma with a two-sided
// identity element Empty(), which combined with any element — on either
// side — yields that element: Combine(Empty(), a) == a and
// Combine(a, Empty()) == a.
//
//goplus:class UnitalMagma[T any] embeds(Magma)
type UnitalMagma[T any] struct {
	Combine func(a T, b T) T
	Empty   func() T
}

//goplus:law (UnitalMagma[T]) LeftId(a T)
func (m UnitalMagma[T]) LawLeftId(a T) bool { return reflect.DeepEqual(m.Combine(m.Empty(), a), a) }

//goplus:law (UnitalMagma[T]) RightId(a T)
func (m UnitalMagma[T]) LawRightId(a T) bool { return reflect.DeepEqual(m.Combine(a, m.Empty()), a) }

// Quasigroup is a triple (T, Combine, division): a magma in which
// division is always possible — LeftDiv(a, b) is the solution x of
// Combine(b, x) == a, and RightDiv(a, b) the solution x of
// Combine(x, b) == a (the Latin-square property).
//
//goplus:class Quasigroup[T any] embeds(Magma)
type Quasigroup[T any] struct {
	Combine  func(a T, b T) T
	LeftDiv  func(a, b T) T
	RightDiv func(a, b T) T
}

//goplus:law (Quasigroup[T]) LeftDivCancels(a, b T)
func (m Quasigroup[T]) LawLeftDivCancels(a, b T) bool {
	return reflect.DeepEqual(m.Combine(b, m.LeftDiv(a, b)), a)
}

//goplus:law (Quasigroup[T]) RightDivCancels(a, b T)
func (m Quasigroup[T]) LawRightDivCancels(a, b T) bool {
	return reflect.DeepEqual(m.Combine(m.RightDiv(a, b), b), a)
}

// Loop is a quasigroup with a two-sided identity: divisibility and a
// unit, but no promise of associativity.
//
//goplus:class Loop[T any] embeds(UnitalMagma, Quasigroup)
type Loop[T any] struct {
	Combine  func(a T, b T) T
	Empty    func() T
	LeftDiv  func(a T, b T) T
	RightDiv func(a T, b T) T
}

// Semigroup is a magma whose operation is associative:
// Combine(Combine(a, b), c) == Combine(a, Combine(b, c)). Grouping
// never matters; order still may.
//
//goplus:class Semigroup[T any] embeds(Magma)
type Semigroup[T any] struct {
	Combine func(a T, b T) T
}

//goplus:law (Semigroup[T]) Assoc(a, b, c T)
func (m Semigroup[T]) LawAssoc(a, b, c T) bool {
	return reflect.DeepEqual(m.Combine(m.Combine(a, b), c), m.Combine(a, m.Combine(b, c)))
}

// AssociativeQuasigroup is a quasigroup whose operation associates.
// (Mathematically every associative quasigroup is a group; the class
// exists as the operational meet of Semigroup and Quasigroup, for
// structures presented without an explicit unit or inverse.)
//
//goplus:class AssociativeQuasigroup[T any] embeds(Semigroup, Quasigroup)
type AssociativeQuasigroup[T any] struct {
	Combine  func(a T, b T) T
	LeftDiv  func(a T, b T) T
	RightDiv func(a T, b T) T
}

// Monoid is a triple (T, Combine, Empty): an associative unital magma —
// a semigroup with a two-sided identity. The workhorse of folding:
// Accumulate and FoldMap require exactly this much structure.
//
//goplus:class Monoid[T any] embeds(Semigroup, UnitalMagma)
type Monoid[T any] struct {
	Combine func(a T, b T) T
	Empty   func() T
}

// Group is a quadruple (T, Combine, Empty, Invert): a monoid in which
// every element has a two-sided inverse — Combine(a, Invert(a)) ==
// Combine(Invert(a), a) == Empty(). Invertibility makes both divisions
// derivable (LeftDiv(a, b) = Combine(Invert(b), a); RightDiv(a, b) =
// Combine(a, Invert(b))), so Group carries their defaults: instances
// provide Combine, Empty, and Invert only.
//
//goplus:class Group[T any] embeds(Monoid, AssociativeQuasigroup)
type Group[T any] struct {
	Combine func(a T, b T) T
	Empty   func() T

	Invert   func(a T) T
	LeftDiv  func(a, b T) T
	RightDiv func(a, b T) T
}

//goplus:default (Group[T]) LeftDiv(a, b T)
func (m Group[T]) DefaultLeftDiv(a, b T) T { return m.Combine(m.Invert(b), a) }

//goplus:default (Group[T]) RightDiv(a, b T)
func (m Group[T]) DefaultRightDiv(a, b T) T { return m.Combine(a, m.Invert(b)) }

//goplus:law (Group[T]) LeftInverse(a T)
func (m Group[T]) LawLeftInverse(a T) bool {
	return reflect.DeepEqual(m.Combine(m.Invert(a), a), m.Empty())
}

//goplus:law (Group[T]) RightInverse(a T)
func (m Group[T]) LawRightInverse(a T) bool {
	return reflect.DeepEqual(m.Combine(a, m.Invert(a)), m.Empty())
}

// AsMagma views the UnitalMagma witness as its Magma part.
func (m UnitalMagma[T]) AsMagma() Magma[T] {
	return Magma[T]{Combine: m.Combine}
}

// AsMagma views the Quasigroup witness as its Magma part.
func (m Quasigroup[T]) AsMagma() Magma[T] {
	return Magma[T]{Combine: m.Combine}
}

// AsMagma views the Semigroup witness as its Magma part.
func (m Semigroup[T]) AsMagma() Magma[T] {
	return Magma[T]{Combine: m.Combine}
}

// AsUnitalMagma views the Loop witness as its UnitalMagma part.
func (m Loop[T]) AsUnitalMagma() UnitalMagma[T] {
	return UnitalMagma[T]{Combine: m.Combine, Empty: m.Empty}
}

// AsQuasigroup views the Loop witness as its Quasigroup part.
func (m Loop[T]) AsQuasigroup() Quasigroup[T] {
	return Quasigroup[T]{Combine: m.Combine, LeftDiv: m.LeftDiv, RightDiv: m.RightDiv}
}

// AsMagma views the Loop witness as its Magma part.
func (m Loop[T]) AsMagma() Magma[T] {
	return Magma[T]{Combine: m.Combine}
}

// AsSemigroup views the AssociativeQuasigroup witness as its Semigroup part.
func (m AssociativeQuasigroup[T]) AsSemigroup() Semigroup[T] {
	return Semigroup[T]{Combine: m.Combine}
}

// AsQuasigroup views the AssociativeQuasigroup witness as its Quasigroup part.
func (m AssociativeQuasigroup[T]) AsQuasigroup() Quasigroup[T] {
	return Quasigroup[T]{Combine: m.Combine, LeftDiv: m.LeftDiv, RightDiv: m.RightDiv}
}

// AsMagma views the AssociativeQuasigroup witness as its Magma part.
func (m AssociativeQuasigroup[T]) AsMagma() Magma[T] {
	return Magma[T]{Combine: m.Combine}
}

// AsSemigroup views the Monoid witness as its Semigroup part.
func (m Monoid[T]) AsSemigroup() Semigroup[T] {
	return Semigroup[T]{Combine: m.Combine}
}

// AsUnitalMagma views the Monoid witness as its UnitalMagma part.
func (m Monoid[T]) AsUnitalMagma() UnitalMagma[T] {
	return UnitalMagma[T]{Combine: m.Combine, Empty: m.Empty}
}

// AsMagma views the Monoid witness as its Magma part.
func (m Monoid[T]) AsMagma() Magma[T] {
	return Magma[T]{Combine: m.Combine}
}

// AsMonoid views the Group witness as its Monoid part.
func (m Group[T]) AsMonoid() Monoid[T] {
	return Monoid[T]{Combine: m.Combine, Empty: m.Empty}
}

// AsAssociativeQuasigroup views the Group witness as its AssociativeQuasigroup part.
func (m Group[T]) AsAssociativeQuasigroup() AssociativeQuasigroup[T] {
	return AssociativeQuasigroup[T]{Combine: m.Combine, LeftDiv: m.LeftDiv, RightDiv: m.RightDiv}
}

// AsSemigroup views the Group witness as its Semigroup part.
func (m Group[T]) AsSemigroup() Semigroup[T] {
	return Semigroup[T]{Combine: m.Combine}
}

// AsUnitalMagma views the Group witness as its UnitalMagma part.
func (m Group[T]) AsUnitalMagma() UnitalMagma[T] {
	return UnitalMagma[T]{Combine: m.Combine, Empty: m.Empty}
}

// AsQuasigroup views the Group witness as its Quasigroup part.
func (m Group[T]) AsQuasigroup() Quasigroup[T] {
	return Quasigroup[T]{Combine: m.Combine, LeftDiv: m.LeftDiv, RightDiv: m.RightDiv}
}

// AsMagma views the Group witness as its Magma part.
func (m Group[T]) AsMagma() Magma[T] {
	return Magma[T]{Combine: m.Combine}
}
