// Code generated by goplus from helpers.gp. DO NOT EDIT.
//goplus:v v0.25.0

package algebra

import "goforge.dev/goplus/std/nonempty"

// Accumulate folds a slice through a monoid, seeded with its identity.
//
//goplus:fn Accumulate[T Monoid]
func Accumulate[T any](monoid Monoid[T], xs []T) T {
	acc := monoid.Empty()
	for _, x := range xs {
		acc = monoid.Combine(acc, x)
	}
	return acc
}

// FoldMap maps each element into a monoid and accumulates the results.
//
//goplus:fn FoldMap[M Monoid]
func FoldMap[A any, M any](monoid Monoid[M], xs []A, f func(A) M) M {
	acc := monoid.Empty()
	for _, x := range xs {
		acc = monoid.Combine(acc, f(x))
	}
	return acc
}

// ReduceNonEmpty folds a semigroup without inventing an identity and without
// an empty-input panic. This is one independent consumer of std/nonempty; the
// GoForge collection compatibility module is the other.
//
//goplus:fn ReduceNonEmpty[T Semigroup]
func ReduceNonEmpty[T any](semigroup Semigroup[T], xs nonempty.NonEmpty[T]) T {
	return nonempty.Reduce1(xs, func(a, b T) T { return semigroup.Combine(a, b) })
}
