// Code generated by goplus from helpers.gp. DO NOT EDIT.
//goplus:v v0.18.0

package algebra

// Accumulate folds a slice through a monoid, seeded with its identity.
//
//goplus:fn Accumulate[T Monoid]
func Accumulate[T any](monoid Monoid[T], xs []T) T {
	acc := monoid.Empty()
	for _, x := range xs {
		acc = monoid.Combine(acc, x)
	}
	return acc
}

// FoldMap maps each element into a monoid and accumulates the results.
//
//goplus:fn FoldMap[M Monoid]
func FoldMap[A any, M any](monoid Monoid[M], xs []A, f func(A) M) M {
	acc := monoid.Empty()
	for _, x := range xs {
		acc = monoid.Combine(acc, f(x))
	}
	return acc
}
