// Code generated by goplus from instances.gp. DO NOT EDIT.
//goplus:v v0.15.0

package algebra

// IntAdd is the additive group of integers.
//
//goplus:instance IntAdd Group[int]
var IntAdd = func() Group[int] {
	w := &Group[int]{
		Combine: func(a, b int) int { return a + b },
		Empty:   func() int { return 0 },
		Invert:  func(a int) int { return -a },
	}
	w.LeftDiv = func(__gp_a0 int, __gp_a1 int) int { return w.DefaultLeftDiv(__gp_a0, __gp_a1) }
	w.RightDiv = func(__gp_a0 int, __gp_a1 int) int { return w.DefaultRightDiv(__gp_a0, __gp_a1) }
	return *w
}()

// IntMul is the multiplicative monoid of integers.
//
//goplus:instance IntMul Monoid[int]
var IntMul = func() Monoid[int] {
	w := &Monoid[int]{
		Combine: func(a, b int) int { return a * b },
		Empty:   func() int { return 1 },
	}
	return *w
}()

// StringConcat is the free monoid over strings.
//
//goplus:instance StringConcat Monoid[string]
var StringConcat = func() Monoid[string] {
	w := &Monoid[string]{
		Combine: func(a, b string) string { return a + b },
		Empty:   func() string { return "" },
	}
	return *w
}()

// BoolAnd is conjunction with identity true.
//
//goplus:instance BoolAnd Monoid[bool]
var BoolAnd = func() Monoid[bool] {
	w := &Monoid[bool]{
		Combine: func(a, b bool) bool { return a && b },
		Empty:   func() bool { return true },
	}
	return *w
}()

// BoolOr is disjunction with identity false.
//
//goplus:instance BoolOr Monoid[bool]
var BoolOr = func() Monoid[bool] {
	w := &Monoid[bool]{
		Combine: func(a, b bool) bool { return a || b },
		Empty:   func() bool { return false },
	}
	return *w
}()

// SliceConcat is the free monoid over slices of any element type.
//
//goplus:instance SliceConcat[T any] Monoid[[]T]
//goplus:laws [int] [string]
func SliceConcat[T any]() Monoid[[]T] {
	w := &Monoid[[]T]{
		Combine: func(a, b []T) []T { return append(append([]T{}, a...), b...) },
		Empty:   func() []T { return nil },
	}
	return *w
}

// MinInt is the meet semigroup of integers.
//
//goplus:instance MinInt Semigroup[int]
var MinInt = func() Semigroup[int] {
	w := &Semigroup[int]{
		Combine: func(a, b int) int {
			if a < b {
				return a
			}
			return b
		},
	}
	return *w
}()

// MaxInt is the join semigroup of integers.
//
//goplus:instance MaxInt Semigroup[int]
var MaxInt = func() Semigroup[int] {
	w := &Semigroup[int]{
		Combine: func(a, b int) int {
			if a > b {
				return a
			}
			return b
		},
	}
	return *w
}()
