// Code generated by goplus from handlers.gp. DO NOT EDIT.
//goplus:v v0.25.0

// The server's dispatch layer, authored in goplus: incoming work is an
// enum, routing is a match, and extending the server means adding a
// variant and an arm — the language serving itself.
package lsp

// Incoming is document-lifecycle work (notifications: no reply).
//
//goplus:enum Incoming
type Incoming interface{ isIncoming() }

//goplus:variant (Incoming) Opened(uri string, text string)
type Opened struct {
	Uri  string
	Text string
}

func (Opened) isIncoming() {}

//goplus:variant (Incoming) Changed(uri string, text string)
type Changed struct {
	Uri  string
	Text string
}

func (Changed) isIncoming() {}

//goplus:variant (Incoming) Closed(uri string)
type Closed struct {
	Uri string
}

func (Closed) isIncoming() {}

//goplus:variant (Incoming) Saved(uri string)
type Saved struct {
	Uri string
}

func (Saved) isIncoming() {}

// IncomingCases selects one handler per Incoming variant for IncomingFold.
type IncomingCases[R any] struct {
	Opened  func(uri string, text string) R
	Changed func(uri string, text string) R
	Closed  func(uri string) R
	Saved   func(uri string) R
}

// IncomingFold reduces Incoming by one-level case analysis.
func IncomingFold[R any](i Incoming, cs IncomingCases[R]) R {
	switch m := any(i).(type) {
	case Opened:
		return cs.Opened(m.Uri, m.Text)
	case Changed:
		return cs.Changed(m.Uri, m.Text)
	case Closed:
		return cs.Closed(m.Uri)
	case Saved:
		return cs.Saved(m.Uri)
	default:
		panic("goplus: impossible enum value in IncomingFold")
	}
}

// IncomingEqOverrides carries optional per-variant hooks for IncomingEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type IncomingEqOverrides struct {
	Opened  func(x, y Opened) (eq, handled bool)
	Changed func(x, y Changed) (eq, handled bool)
	Closed  func(x, y Closed) (eq, handled bool)
	Saved   func(x, y Saved) (eq, handled bool)
}

// IncomingEqualWith reports structural equality of a and b under ov.
func IncomingEqualWith(a, b Incoming, ov IncomingEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case Opened:
		y, ok := any(b).(Opened)
		if !ok {
			return false
		}
		if ov.Opened != nil {
			if eq, handled := ov.Opened(x, y); handled {
				return eq
			}
		}
		if x.Uri != y.Uri {
			return false
		}
		if x.Text != y.Text {
			return false
		}
		return true
	case Changed:
		y, ok := any(b).(Changed)
		if !ok {
			return false
		}
		if ov.Changed != nil {
			if eq, handled := ov.Changed(x, y); handled {
				return eq
			}
		}
		if x.Uri != y.Uri {
			return false
		}
		if x.Text != y.Text {
			return false
		}
		return true
	case Closed:
		y, ok := any(b).(Closed)
		if !ok {
			return false
		}
		if ov.Closed != nil {
			if eq, handled := ov.Closed(x, y); handled {
				return eq
			}
		}
		if x.Uri != y.Uri {
			return false
		}
		return true
	case Saved:
		y, ok := any(b).(Saved)
		if !ok {
			return false
		}
		if ov.Saved != nil {
			if eq, handled := ov.Saved(x, y); handled {
				return eq
			}
		}
		if x.Uri != y.Uri {
			return false
		}
		return true
	}
	return false
}

// IncomingEqual reports structural equality of a and b.
func IncomingEqual(a, b Incoming) bool {
	return IncomingEqualWith(a, b, IncomingEqOverrides{})
}

// Dispatch routes lifecycle work onto the server.
func Dispatch(s *Server, in Incoming) {
	switch __gp_m0 := any(in).(type) {
	case Opened:
		uri := __gp_m0.Uri
		text := __gp_m0.Text

		s.SetOverlay(uri, text)
		s.ScheduleDiagnostics()
	case Changed:
		uri := __gp_m0.Uri
		text := __gp_m0.Text

		s.SetOverlay(uri, text)
		s.ScheduleDiagnostics()
	case Closed:
		uri := __gp_m0.Uri

		s.DropOverlay(uri)
	case Saved:
		uri := __gp_m0.Uri

		_ = uri
		s.ScheduleDiagnostics()
	default:
		panic("goplus: impossible enum value in match")
	}
}

// Query is position work (requests: a reply is owed).
//
//goplus:enum Query
type Query interface{ isQuery() }

//goplus:variant (Query) QHover(uri string, line int, ch int)
type QHover struct {
	Uri  string
	Line int
	Ch   int
}

func (QHover) isQuery() {}

//goplus:variant (Query) QDefinition(uri string, line int, ch int)
type QDefinition struct {
	Uri  string
	Line int
	Ch   int
}

func (QDefinition) isQuery() {}

//goplus:variant (Query) QComplete(uri string, line int, ch int)
type QComplete struct {
	Uri  string
	Line int
	Ch   int
}

func (QComplete) isQuery() {}

// QueryCases selects one handler per Query variant for QueryFold.
type QueryCases[R any] struct {
	QHover      func(uri string, line int, ch int) R
	QDefinition func(uri string, line int, ch int) R
	QComplete   func(uri string, line int, ch int) R
}

// QueryFold reduces Query by one-level case analysis.
func QueryFold[R any](q Query, cs QueryCases[R]) R {
	switch m := any(q).(type) {
	case QHover:
		return cs.QHover(m.Uri, m.Line, m.Ch)
	case QDefinition:
		return cs.QDefinition(m.Uri, m.Line, m.Ch)
	case QComplete:
		return cs.QComplete(m.Uri, m.Line, m.Ch)
	default:
		panic("goplus: impossible enum value in QueryFold")
	}
}

// QueryEqOverrides carries optional per-variant hooks for QueryEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type QueryEqOverrides struct {
	QHover      func(x, y QHover) (eq, handled bool)
	QDefinition func(x, y QDefinition) (eq, handled bool)
	QComplete   func(x, y QComplete) (eq, handled bool)
}

// QueryEqualWith reports structural equality of a and b under ov.
func QueryEqualWith(a, b Query, ov QueryEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case QHover:
		y, ok := any(b).(QHover)
		if !ok {
			return false
		}
		if ov.QHover != nil {
			if eq, handled := ov.QHover(x, y); handled {
				return eq
			}
		}
		if x.Uri != y.Uri {
			return false
		}
		if x.Line != y.Line {
			return false
		}
		if x.Ch != y.Ch {
			return false
		}
		return true
	case QDefinition:
		y, ok := any(b).(QDefinition)
		if !ok {
			return false
		}
		if ov.QDefinition != nil {
			if eq, handled := ov.QDefinition(x, y); handled {
				return eq
			}
		}
		if x.Uri != y.Uri {
			return false
		}
		if x.Line != y.Line {
			return false
		}
		if x.Ch != y.Ch {
			return false
		}
		return true
	case QComplete:
		y, ok := any(b).(QComplete)
		if !ok {
			return false
		}
		if ov.QComplete != nil {
			if eq, handled := ov.QComplete(x, y); handled {
				return eq
			}
		}
		if x.Uri != y.Uri {
			return false
		}
		if x.Line != y.Line {
			return false
		}
		if x.Ch != y.Ch {
			return false
		}
		return true
	}
	return false
}

// QueryEqual reports structural equality of a and b.
func QueryEqual(a, b Query) bool {
	return QueryEqualWith(a, b, QueryEqOverrides{})
}

// QueryReply is what a query yields: raw JSON from the delegate, or a
// reasoned absence (the client renders null).
//
//goplus:enum QueryReply
type QueryReply interface{ isQueryReply() }

//goplus:variant (QueryReply) Raw(data []byte)
type Raw struct {
	Data []byte
}

func (Raw) isQueryReply() {}

//goplus:variant (QueryReply) NoAnswer(reason string)
type NoAnswer struct {
	Reason string
}

func (NoAnswer) isQueryReply() {}

// QueryReplyCases selects one handler per QueryReply variant for QueryReplyFold.
type QueryReplyCases[R any] struct {
	Raw      func(data []byte) R
	NoAnswer func(reason string) R
}

// QueryReplyFold reduces QueryReply by one-level case analysis.
func QueryReplyFold[R any](q QueryReply, cs QueryReplyCases[R]) R {
	switch m := any(q).(type) {
	case Raw:
		return cs.Raw(m.Data)
	case NoAnswer:
		return cs.NoAnswer(m.Reason)
	default:
		panic("goplus: impossible enum value in QueryReplyFold")
	}
}

// QueryReplyEqOverrides carries optional per-variant hooks for QueryReplyEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type QueryReplyEqOverrides struct {
	Raw      func(x, y Raw) (eq, handled bool)
	NoAnswer func(x, y NoAnswer) (eq, handled bool)
}

// QueryReplyEqualWith reports structural equality of a and b under ov.
func QueryReplyEqualWith(a, b QueryReply, ov QueryReplyEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case Raw:
		y, ok := any(b).(Raw)
		if !ok {
			return false
		}
		if ov.Raw != nil {
			if eq, handled := ov.Raw(x, y); handled {
				return eq
			}
		}
		if len(x.Data) != len(y.Data) {
			return false
		}
		for i0 := range x.Data {
			if x.Data[i0] != y.Data[i0] {
				return false
			}
		}
		return true
	case NoAnswer:
		y, ok := any(b).(NoAnswer)
		if !ok {
			return false
		}
		if ov.NoAnswer != nil {
			if eq, handled := ov.NoAnswer(x, y); handled {
				return eq
			}
		}
		if x.Reason != y.Reason {
			return false
		}
		return true
	}
	return false
}

// QueryReplyEqual reports structural equality of a and b.
func QueryReplyEqual(a, b QueryReply) bool {
	return QueryReplyEqualWith(a, b, QueryReplyEqOverrides{})
}

// Answer resolves one query through the gopls delegate.
func Answer(s *Server, q Query) QueryReply {
	switch __gp_m1 := any(q).(type) {
	case QHover:
		uri := __gp_m1.Uri
		line := __gp_m1.Line
		ch := __gp_m1.Ch

		return s.Forward("textDocument/hover", uri, line, ch)
	case QDefinition:
		uri := __gp_m1.Uri
		line := __gp_m1.Line
		ch := __gp_m1.Ch

		return s.Forward("textDocument/definition", uri, line, ch)
	case QComplete:
		uri := __gp_m1.Uri
		line := __gp_m1.Line
		ch := __gp_m1.Ch

		return s.Forward("textDocument/completion", uri, line, ch)
	default:
		panic("goplus: impossible enum value in match")
	}
}
