// Code generated by goplus from server.gp. DO NOT EDIT.
//goplus:v v0.23.0

package lsp

import (
	"encoding/json"
	"io"
	"net/url"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"go/token"

	"goforge.dev/goplus/internal/gen"
	"goforge.dev/goplus/internal/sourcemap"
	"goforge.dev/goplus/internal/version"
)

// Server holds one editing session: unsaved buffers, the latest
// in-memory generation, forward/backward sourcemaps, and the gopls
// delegate. Effects called from the goplus dispatch layer live here.
type Server struct {
	conn *conn
	root string // workspace directory

	mu       sync.Mutex
	overlays map[string][]byte         // abs .gp path → unsaved contents
	outputs  map[string][]byte         // abs generated path → latest dry-run output
	maps     map[string]*sourcemap.Map // generated path → map (both directions)

	debounce *time.Timer
	genMu    sync.Mutex

	gopls *goplsClient // nil when unavailable
}

// Serve speaks LSP over r/w until EOF or exit.
func Serve(r io.Reader, w io.Writer) error {
	s := &Server{
		conn:     newConn(r, w),
		overlays: map[string][]byte{},
		outputs:  map[string][]byte{},
		maps:     map[string]*sourcemap.Map{},
	}
	for {
		m, err := s.conn.read()
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
		if done := s.handle(m); done {
			return nil
		}
	}
}

func (s *Server) handle(m *message) (exit bool) {
	switch m.Method {
	case "initialize":
		var p initializeParams
		_ = json.Unmarshal(m.Params, &p)
		s.root = uriToPath(p.RootURI)
		s.gopls = startGopls(s.root)
		caps := map[string]any{
			"textDocumentSync": map[string]any{"openClose": true, "change": 1, "save": true},
		}
		if s.gopls != nil {
			caps["hoverProvider"] = true
			caps["definitionProvider"] = true
			caps["completionProvider"] = map[string]any{"triggerCharacters": []string{"."}}
		}
		_ = s.conn.respond(m.ID, initializeResult{
			Capabilities: caps,
			ServerInfo:   serverInfo{Name: "goplus", Version: version.Version},
		})
	case "initialized":
	case "shutdown":
		_ = s.conn.respond(m.ID, nil)
	case "exit":
		if s.gopls != nil {
			s.gopls.stop()
		}
		return true
	case "textDocument/didOpen":
		var p didOpenParams
		_ = json.Unmarshal(m.Params, &p)
		Dispatch(s, Opened{Uri: p.TextDocument.URI, Text: p.TextDocument.Text})
	case "textDocument/didChange":
		var p didChangeParams
		_ = json.Unmarshal(m.Params, &p)
		if len(p.Changes) > 0 {
			Dispatch(s, Changed{Uri: p.TextDocument.URI, Text: p.Changes[len(p.Changes)-1].Text})
		}
	case "textDocument/didClose":
		var p didCloseParams
		_ = json.Unmarshal(m.Params, &p)
		Dispatch(s, Closed{Uri: p.TextDocument.URI})
	case "textDocument/didSave":
		var p didCloseParams
		_ = json.Unmarshal(m.Params, &p)
		Dispatch(s, Saved{Uri: p.TextDocument.URI})
	case "textDocument/hover", "textDocument/definition", "textDocument/completion":
		var p positionParams
		_ = json.Unmarshal(m.Params, &p)
		var q Query
		switch m.Method {
		case "textDocument/hover":
			q = QHover{Uri: p.TextDocument.URI, Line: p.Position.Line, Ch: p.Position.Character}
		case "textDocument/definition":
			q = QDefinition{Uri: p.TextDocument.URI, Line: p.Position.Line, Ch: p.Position.Character}
		default:
			q = QComplete{Uri: p.TextDocument.URI, Line: p.Position.Line, Ch: p.Position.Character}
		}
		match := Answer(s, q)
		s.replyQuery(m.ID, match)
	default:
		if m.ID != nil {
			_ = s.conn.respondErr(m.ID, -32601, "method not supported: "+m.Method)
		}
	}
	return false
}

func (s *Server) replyQuery(id *json.RawMessage, r QueryReply) {
	_ = QueryReplyFold(r, QueryReplyCases[error]{
		Raw: func(data []byte) error {
			raw := json.RawMessage(data)
			return s.conn.respond(id, &raw)
		},
		NoAnswer: func(reason string) error {
			_ = reason
			return s.conn.respond(id, nil)
		},
	})
}

// SetOverlay records an unsaved buffer.
func (s *Server) SetOverlay(uri, text string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.overlays[uriToPath(uri)] = []byte(text)
}

// DropOverlay forgets a closed buffer.
func (s *Server) DropOverlay(uri string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	delete(s.overlays, uriToPath(uri))
}

// ScheduleDiagnostics debounces a workspace regeneration.
func (s *Server) ScheduleDiagnostics() {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.debounce != nil {
		s.debounce.Stop()
	}
	s.debounce = time.AfterFunc(200*time.Millisecond, s.runDiagnostics)
}

// runDiagnostics regenerates in memory and publishes per-file errors.
func (s *Server) runDiagnostics() {
	s.genMu.Lock()
	defer s.genMu.Unlock()
	s.mu.Lock()
	overlay := make(map[string][]byte, len(s.overlays))
	openFiles := make([]string, 0, len(s.overlays))
	for p, b := range s.overlays {
		overlay[p] = b
		openFiles = append(openFiles, p)
	}
	s.mu.Unlock()

	res, err := gen.Run(gen.Options{Dir: s.root, Patterns: []string{"./..."}, Overlay: overlay, DryRun: true})
	if err != nil {
		return
	}
	byFile := map[string][]Diagnostic{}
	for _, f := range openFiles {
		byFile[f] = nil // clear stale diagnostics on every open file
	}
	for _, d := range res.Diags {
		path := d.Pos.Filename
		if !filepath.IsAbs(path) {
			path = filepath.Join(s.root, path)
		}
		line, col := d.Pos.Line-1, d.Pos.Column-1
		if line < 0 {
			line, col = 0, 0
		}
		if col < 0 {
			col = 0
		}
		byFile[path] = append(byFile[path], Diagnostic{
			Range:    Range{Start: Position{line, col}, End: Position{line, col + 1}},
			Severity: 1,
			Source:   "goplus",
			Message:  d.Msg,
		})
	}
	for path, diags := range byFile {
		if diags == nil {
			diags = []Diagnostic{}
		}
		_ = s.conn.notify("textDocument/publishDiagnostics", publishDiagnosticsParams{
			URI: pathToURI(path), Diagnostics: diags,
		})
	}

	// A clean generation refreshes the delegate's view of the world.
	if len(res.Diags) == 0 && res.Outputs != nil {
		s.mu.Lock()
		s.outputs = res.Outputs
		s.maps = map[string]*sourcemap.Map{}
		for genPath, content := range res.Outputs {
			goplusPath := strings.TrimSuffix(genPath, "_gp.go") + ".gp"
			goplusSrc, ok := overlay[goplusPath]
			if !ok {
				continue
			}
			s.maps[genPath] = sourcemap.Build(goplusPath, goplusSrc, content)
		}
		s.mu.Unlock()
		if s.gopls != nil {
			s.gopls.syncOutputs(res.Outputs)
		}
	}
}

// Forward maps a .gp position through the latest generation, asks
// gopls, and maps result positions back.
func (s *Server) Forward(method, uri string, line, ch int) QueryReply {
	if s.gopls == nil {
		return NoAnswer{Reason: "gopls unavailable"}
	}
	goplusPath := uriToPath(uri)
	genPath := generatedCounterpart(goplusPath)
	s.mu.Lock()
	m := s.maps[genPath]
	s.mu.Unlock()
	if m == nil {
		return NoAnswer{Reason: "no generation for " + goplusPath}
	}
	fwd, ok := forwardPos(m, line, ch)
	if !ok {
		return NoAnswer{Reason: "position not generated"}
	}
	raw, err := s.gopls.request(method, positionParams{
		TextDocument: textDocumentIdentifier{URI: pathToURI(genPath)},
		Position:     fwd,
	})
	if err != nil {
		return NoAnswer{Reason: err.Error()}
	}
	mapped := s.mapBack(raw)
	return Raw{Data: mapped}
}

// mapBack rewrites generated-file URIs/ranges inside a gopls result to
// their .gp counterparts, structurally, wherever they appear.
func (s *Server) mapBack(raw json.RawMessage) []byte {
	var v any
	if err := json.Unmarshal(raw, &v); err != nil {
		return raw
	}
	v = s.mapBackValue(v)
	out, err := json.Marshal(v)
	if err != nil {
		return raw
	}
	return out
}

func (s *Server) mapBackValue(v any) any {
	switch x := v.(type) {
	case map[string]any:
		if uriv, hasURI := x["uri"].(string); hasURI {
			if rng, hasRange := x["range"].(map[string]any); hasRange {
				if nu, nr, ok := s.mapBackLocation(uriv, rng); ok {
					x["uri"], x["range"] = nu, nr
				}
			}
		}
		for k, val := range x {
			x[k] = s.mapBackValue(val)
		}
		return x
	case []any:
		for i := range x {
			x[i] = s.mapBackValue(x[i])
		}
		return x
	}
	return v
}

func (s *Server) mapBackLocation(uri string, rng map[string]any) (string, map[string]any, bool) {
	path := uriToPath(uri)
	s.mu.Lock()
	m := s.maps[path]
	s.mu.Unlock()
	if m == nil {
		return "", nil, false
	}
	conv := func(key string) bool {
		posv, ok := rng[key].(map[string]any)
		if !ok {
			return false
		}
		lf, _ := posv["line"].(float64)
		cf, _ := posv["character"].(float64)
		mapped, mok := m.Map(tokenPosition(int(lf)+1, int(cf)+1))
		if !mok {
			return false
		}
		posv["line"] = mapped.Line - 1
		posv["character"] = mapped.Column - 1
		return true
	}
	if !conv("start") || !conv("end") {
		return "", nil, false
	}
	return pathToURI(m.GoplusPath), rng, true
}

func forwardPos(m *sourcemap.Map, line, ch int) (Position, bool) {
	mapped, ok := m.Forward(tokenPosition(line+1, ch+1))
	if !ok {
		return Position{}, false
	}
	return Position{Line: mapped.Line - 1, Character: mapped.Column - 1}, true
}

func uriToPath(uri string) string {
	if u, err := url.Parse(uri); err == nil && u.Scheme == "file" {
		return u.Path
	}
	return uri
}

func pathToURI(path string) string {
	if !filepath.IsAbs(path) {
		abs, err := filepath.Abs(path)
		if err == nil {
			path = abs
		}
	}
	return "file://" + path
}

// generatedCounterpart names the emitted twin of a .gp file.
func generatedCounterpart(goplusPath string) string {
	return strings.TrimSuffix(goplusPath, ".gp") + "_gp.go"
}

// tokenPosition builds a 1-based position for sourcemap calls.
func tokenPosition(line, col int) token.Position {
	return token.Position{Line: line, Column: col}
}
