// Code generated by gpp from parsec.gpp. DO NOT EDIT.

// Package parsec is a parser-combinator library with parsec-style
// consumed/empty semantics over streaming input: Or commits once a
// branch has consumed; Try restores the lookahead explicitly. A
// Parser[T] is a function from Input to a four-way Reply — gpp's own
// enum, matched throughout.
package parsec

import (
	"fmt"
	"io"
	"strings"
)

// Reply is the outcome of running a parser: did it succeed, and did it
// consume input? The distinction drives Or's commit discipline.
//
//gpp:enum Reply[T any]
type Reply[T any] interface{ isReply(T) }

//gpp:variant (Reply[T]) ConsumedOk(Value T, Rest Input)
type ConsumedOk[T any] struct {
	Value T
	Rest  Input
}

func (ConsumedOk[T]) isReply(T) {}

//gpp:variant (Reply[T]) ConsumedErr(Err ParseError)
type ConsumedErr[T any] struct {
	Err ParseError
}

func (ConsumedErr[T]) isReply(T) {}

//gpp:variant (Reply[T]) EmptyOk(Value T, Rest Input)
type EmptyOk[T any] struct {
	Value T
	Rest  Input
}

func (EmptyOk[T]) isReply(T) {}

//gpp:variant (Reply[T]) EmptyErr(Err ParseError)
type EmptyErr[T any] struct {
	Err ParseError
}

func (EmptyErr[T]) isReply(T) {}

// ReplyCases selects one handler per Reply variant for Fold.
type ReplyCases[T any, R any] struct {
	ConsumedOk  func(Value T, Rest Input) R
	ConsumedErr func(Err ParseError) R
	EmptyOk     func(Value T, Rest Input) R
	EmptyErr    func(Err ParseError) R
}

// Fold reduces Reply[T] by one-level case analysis.
func Fold[T any, R any](v Reply[T], cs ReplyCases[T, R]) R {
	switch m := any(v).(type) {
	case ConsumedOk[T]:
		return cs.ConsumedOk(m.Value, m.Rest)
	case ConsumedErr[T]:
		return cs.ConsumedErr(m.Err)
	case EmptyOk[T]:
		return cs.EmptyOk(m.Value, m.Rest)
	case EmptyErr[T]:
		return cs.EmptyErr(m.Err)
	default:
		panic("gpp: impossible enum value in Fold")
	}
}

// Parser consumes input and replies.
type Parser[T any] func(Input) Reply[T]

// ParseError is a position plus what was seen and what would have been
// accepted.
type ParseError struct {
	Line       int
	Col        int
	Off        int
	Unexpected string
	Expected   []string
}

func (e ParseError) Error() string {
	msg := fmt.Sprintf("%d:%d: unexpected %s", e.Line, e.Col, e.Unexpected)
	if len(e.Expected) > 0 {
		msg += ", expecting " + strings.Join(e.Expected, " or ")
	}
	return msg
}

func errAt(in Input, unexpected string, expected []string) ParseError {
	return ParseError{Line: in.Line, Col: in.Col, Off: in.Off, Unexpected: unexpected, Expected: expected}
}

// Return succeeds with v, consuming nothing.
func Return[T any](v T) Parser[T] {
	return func(in Input) Reply[T] {
		return EmptyOk[T]{Value: v, Rest: in}
	}
}

// Fail fails without consuming, reporting what was expected.
func Fail[T any](expected string) Parser[T] {
	return func(in Input) Reply[T] {
		return EmptyErr[T]{Err: errAt(in, "input here", []string{expected})}
	}
}

// Bind sequences: run p, feed its value to f, run the result.
// Consumption is contagious — if either side consumed, the whole reply
// is consumed.
func Bind[T any, U any](p Parser[T], f func(T) Parser[U]) Parser[U] {
	return func(in Input) Reply[U] {
		switch __gpp_m0 := any(p(in)).(type) {
		case ConsumedOk[T]:
			v := __gpp_m0.Value
			rest := __gpp_m0.Rest
			switch __gpp_m1 := any(f(v)(rest)).(type) {
			case EmptyOk[U]:
				v2 := __gpp_m1.Value
				rest2 := __gpp_m1.Rest
				return ConsumedOk[U]{Value: v2, Rest: rest2}
			case EmptyErr[U]:
				e := __gpp_m1.Err
				return ConsumedErr[U]{Err: e}
			case ConsumedOk[U]:
				v2 := __gpp_m1.Value
				rest2 := __gpp_m1.Rest
				return ConsumedOk[U]{Value: v2, Rest: rest2}
			case ConsumedErr[U]:
				e := __gpp_m1.Err
				return ConsumedErr[U]{Err: e}
			default:
				panic("gpp: impossible enum value in match")
			}
		case EmptyOk[T]:
			v := __gpp_m0.Value
			rest := __gpp_m0.Rest
			return f(v)(rest)
		case ConsumedErr[T]:
			e := __gpp_m0.Err
			return ConsumedErr[U]{Err: e}
		case EmptyErr[T]:
			e := __gpp_m0.Err
			return EmptyErr[U]{Err: e}
		default:
			panic("gpp: impossible enum value in match")
		}
		panic("unreachable")
	}
}

// Map transforms the value, preserving the reply's consumption.
func Map[T any, U any](p Parser[T], f func(T) U) Parser[U] {
	return func(in Input) Reply[U] {
		switch __gpp_m2 := any(p(in)).(type) {
		case ConsumedOk[T]:
			v := __gpp_m2.Value
			rest := __gpp_m2.Rest
			return ConsumedOk[U]{Value: f(v), Rest: rest}
		case EmptyOk[T]:
			v := __gpp_m2.Value
			rest := __gpp_m2.Rest
			return EmptyOk[U]{Value: f(v), Rest: rest}
		case ConsumedErr[T]:
			e := __gpp_m2.Err
			return ConsumedErr[U]{Err: e}
		case EmptyErr[T]:
			e := __gpp_m2.Err
			return EmptyErr[U]{Err: e}
		default:
			panic("gpp: impossible enum value in match")
		}
		panic("unreachable")
	}
}

// Or tries q only when p failed WITHOUT consuming: consumption commits.
func Or[T any](p Parser[T], q Parser[T]) Parser[T] {
	return func(in Input) Reply[T] {
		switch __gpp_m3 := any(p(in)).(type) {
		case EmptyErr[T]:
			e := __gpp_m3.Err
			_ = e
			return q(in)
		case ConsumedOk[T]:
			v := __gpp_m3.Value
			rest := __gpp_m3.Rest
			return ConsumedOk[T]{Value: v, Rest: rest}
		case EmptyOk[T]:
			v := __gpp_m3.Value
			rest := __gpp_m3.Rest
			return EmptyOk[T]{Value: v, Rest: rest}
		case ConsumedErr[T]:
			e := __gpp_m3.Err
			return ConsumedErr[T]{Err: e}
		default:
			panic("gpp: impossible enum value in match")
		}
		panic("unreachable")
	}
}

// Try runs p with the lookahead pinned: a consumed failure becomes an
// empty failure, so an enclosing Or may still take its next branch.
func Try[T any](p Parser[T]) Parser[T] {
	return func(in Input) Reply[T] {
		unpin := in.Pin()
		r := p(in)
		unpin()
		switch __gpp_m4 := any(r).(type) {
		case ConsumedErr[T]:
			e := __gpp_m4.Err
			return EmptyErr[T]{Err: e}
		case ConsumedOk[T]:
			v := __gpp_m4.Value
			rest := __gpp_m4.Rest
			return ConsumedOk[T]{Value: v, Rest: rest}
		case EmptyOk[T]:
			v := __gpp_m4.Value
			rest := __gpp_m4.Rest
			return EmptyOk[T]{Value: v, Rest: rest}
		case EmptyErr[T]:
			e := __gpp_m4.Err
			return EmptyErr[T]{Err: e}
		default:
			panic("gpp: impossible enum value in match")
		}
		panic("unreachable")
	}
}

// Label names what an empty failure expected (parsec's <?>).
func Label[T any](p Parser[T], name string) Parser[T] {
	return func(in Input) Reply[T] {
		switch __gpp_m5 := any(p(in)).(type) {
		case EmptyErr[T]:
			e := __gpp_m5.Err
			e.Expected = []string{name}
			return EmptyErr[T]{Err: e}
		case ConsumedOk[T]:
			v := __gpp_m5.Value
			rest := __gpp_m5.Rest
			return ConsumedOk[T]{Value: v, Rest: rest}
		case EmptyOk[T]:
			v := __gpp_m5.Value
			rest := __gpp_m5.Rest
			return EmptyOk[T]{Value: v, Rest: rest}
		case ConsumedErr[T]:
			e := __gpp_m5.Err
			return ConsumedErr[T]{Err: e}
		default:
			panic("gpp: impossible enum value in match")
		}
		panic("unreachable")
	}
}

// RuneWhen accepts one rune satisfying pred, described for errors.
func RuneWhen(pred func(rune) bool, desc string) Parser[rune] {
	return func(in Input) Reply[rune] {
		r, size, eof, err := in.PeekRune()
		if err != nil {
			return EmptyErr[rune]{Err: errAt(in, "read error: "+err.Error(), nil)}
		}
		if eof {
			return EmptyErr[rune]{Err: errAt(in, "end of input", []string{desc})}
		}
		if !pred(r) {
			return EmptyErr[rune]{Err: errAt(in, fmt.Sprintf("%q", r), []string{desc})}
		}
		return ConsumedOk[rune]{Value: r, Rest: in.Advance(r, size)}
	}
}

// Rune accepts exactly r.
func Rune(want rune) Parser[rune] {
	return RuneWhen(func(r rune) bool { return r == want }, fmt.Sprintf("%q", want))
}

// Str accepts exactly s. A first-rune mismatch is an empty failure; a
// later mismatch has consumed and commits (wrap in Try for lookahead).
func Str(s string) Parser[string] {
	return func(in Input) Reply[string] {
		cur := in
		first := true
		for _, want := range s {
			r, size, eof, err := cur.PeekRune()
			if err != nil {
				return EmptyErr[string]{Err: errAt(cur, "read error: "+err.Error(), nil)}
			}
			bad := ""
			if eof {
				bad = "end of input"
			} else if r != want {
				bad = fmt.Sprintf("%q", r)
			}
			if bad != "" {
				e := errAt(cur, bad, []string{fmt.Sprintf("%q", s)})
				if first {
					return EmptyErr[string]{Err: e}
				}
				return ConsumedErr[string]{Err: e}
			}
			cur = cur.Advance(r, size)
			first = false
		}
		if s == "" {
			return EmptyOk[string]{Value: s, Rest: cur}
		}
		return ConsumedOk[string]{Value: s, Rest: cur}
	}
}

// TakeWhile consumes the longest (possibly empty) run satisfying pred.
// It never fails.
func TakeWhile(pred func(rune) bool) Parser[string] {
	return func(in Input) Reply[string] {
		var b strings.Builder
		cur := in
		for {
			r, size, eof, err := cur.PeekRune()
			if err != nil {
				return EmptyErr[string]{Err: errAt(cur, "read error: "+err.Error(), nil)}
			}
			if eof || !pred(r) {
				if b.Len() == 0 {
					return EmptyOk[string]{Value: "", Rest: cur}
				}
				return ConsumedOk[string]{Value: b.String(), Rest: cur}
			}
			b.WriteRune(r)
			cur = cur.Advance(r, size)
		}
	}
}

// EOF succeeds only at end of input.
func EOF() Parser[struct{}] {
	return func(in Input) Reply[struct{}] {
		r, _, eof, err := in.PeekRune()
		if err != nil {
			return EmptyErr[struct{}]{Err: errAt(in, "read error: "+err.Error(), nil)}
		}
		if !eof {
			return EmptyErr[struct{}]{Err: errAt(in, fmt.Sprintf("%q", r), []string{"end of input"})}
		}
		return EmptyOk[struct{}]{Value: struct{}{}, Rest: in}
	}
}

// Run parses a reader from the start.
func Run[T any](p Parser[T], r io.Reader) (T, error) {
	switch __gpp_m6 := any(p(StartInput(NewStream(r)))).(type) {
	case ConsumedOk[T]:
		v := __gpp_m6.Value
		rest := __gpp_m6.Rest
		_ = rest
		return v, nil
	case EmptyOk[T]:
		v := __gpp_m6.Value
		rest := __gpp_m6.Rest
		_ = rest
		return v, nil
	case ConsumedErr[T]:
		e := __gpp_m6.Err
		var zero T
		return zero, e
	case EmptyErr[T]:
		e := __gpp_m6.Err
		var zero T
		return zero, e
	default:
		panic("gpp: impossible enum value in match")
	}
	panic("unreachable")
}

// RunString parses a string from the start.
func RunString[T any](p Parser[T], s string) (T, error) {
	return Run(p, strings.NewReader(s))
}
