// Code generated by gpp from clock.gpp. DO NOT EDIT.
//gpp:v v0.13.0

// Package clock is a time-source seam for deterministic fake-time testing
// of time-driven components. Production code takes a Clock; tests inject a
// Fake and step it with Advance, so timer-driven logic runs deterministically
// with no sleeps.
//
// The seam carries the three shapes timer consumers actually use:
//
//   - Now — the current instant.
//   - After — the CHANNEL shape: `case <-clk.After(d):` in a select loop.
//     The returned channel is buffered (cap 1) in both implementations, so a
//     receiver that abandons the channel never blocks the sender.
//   - AfterFunc — the CALLBACK shape, returning a Stop handle mirroring
//     time.Timer.Stop.
//
// Fake fires both shapes at Advance time in deadline-ascending order, ties
// broken by insertion order, deterministically. Both Real and Fake are safe
// for concurrent use; Fake's Advance is intended to be driven from a single
// test goroutine.
//
// Authored in G++ and distributed as generated Go — consumers never need
// the gpp toolchain.
package clock

import (
	"sort"
	"sync"
	"time"
)

// Clock is the time-source seam.
type Clock interface {
	// Now returns the current time: wall-clock in production, step-driven
	// in fake-time tests.
	Now() time.Time

	// After returns a channel that fires once with the fire time after d.
	// Matches stdlib time.After shape; the channel has buffer 1 in both
	// implementations so an abandoned receiver never leaks a blocked sender.
	After(d time.Duration) <-chan time.Time

	// AfterFunc schedules fn after d and returns a Stop handle that can
	// cancel a pending fire (mirrors time.AfterFunc + time.Timer.Stop).
	AfterFunc(d time.Duration, fn func()) Stop
}

// Stop is the per-timer cancellation handle returned by AfterFunc. Stop
// returns true iff the call stopped a not-yet-fired, not-already-stopped
// timer (the fn will NOT fire); false otherwise.
type Stop interface {
	Stop() bool
}

// Real is the production Clock: delegates to time.Now / time.After /
// time.AfterFunc. The zero value is usable.
type Real struct{}

// Now returns time.Now().
func (Real) Now() time.Time { return time.Now() }

// After returns time.After(d).
//
// NOTE: stdlib time.After allocates a timer per call that stays live until
// it fires. For tight loops with large periods + frequent cancellation,
// consumers may prefer an explicit time.NewTimer + Stop pattern; for the
// common one-timer-in-flight loop the cost is amortized.
func (Real) After(d time.Duration) <-chan time.Time { return time.After(d) }

// AfterFunc wraps time.AfterFunc.
func (Real) AfterFunc(d time.Duration, fn func()) Stop {
	return realStop{t: time.AfterFunc(d, fn)}
}

type realStop struct {
	t *time.Timer
}

func (s realStop) Stop() bool { return s.t.Stop() }

// Fake is the test Clock: time moves only via Advance. Both After channels
// and AfterFunc callbacks registered before an Advance fire during it, in
// (deadline, insertion-seq) order. After and AfterFunc share one insertion
// counter, so cross-shape ties are deterministic too.
//
// Registrations from multiple goroutines are serialized by the internal
// mutex; Advance is intended to be called from a single test-driver
// goroutine. Tests that need barrier-style synchronization between Advance
// and a goroutine consuming an After channel must add their own sync.
type Fake struct {
	mu      sync.Mutex
	now     time.Time
	pending []*fakeAfter
	timers  []*fakeTimer
	nextSeq uint64
}

type fakeAfter struct {
	ch       chan time.Time
	deadline time.Time
	seq      uint64
}

type fakeTimer struct {
	parent   *Fake
	deadline time.Time
	fn       func()
	seq      uint64
	stopped  bool
	fired    bool
}

// Stop cancels the timer: true iff it stopped a not-yet-fired,
// not-already-stopped timer. fired is marked before the callback runs, so a
// Stop racing a fire observes fired and reports false.
func (t *fakeTimer) Stop() bool {
	t.parent.mu.Lock()
	defer t.parent.mu.Unlock()
	if t.stopped || t.fired {
		return false
	}
	t.stopped = true
	return true
}

// NewFake returns a Fake anchored at start. The zero time is permitted.
func NewFake(start time.Time) *Fake {
	return &Fake{now: start}
}

// Now returns the current step-clock time.
func (c *Fake) Now() time.Time {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.now
}

// PendingLen reports the number of After registrations awaiting Advance —
// the observability seam for synchronizing an Advance against a goroutine's
// re-registration of its next tick (poll PendingLen to the expected count,
// then Advance).
func (c *Fake) PendingLen() int {
	c.mu.Lock()
	defer c.mu.Unlock()
	return len(c.pending)
}

// After returns a buffered (cap 1) channel that fires at the first Advance
// whose new now covers c.now + d. A d <= 0 fires synchronously before
// returning (the buffer absorbs the send), matching stdlib semantics.
func (c *Fake) After(d time.Duration) <-chan time.Time {
	c.mu.Lock()
	defer c.mu.Unlock()
	ch := make(chan time.Time, 1)
	if d <= 0 {
		ch <- c.now
		return ch
	}
	c.pending = append(c.pending, &fakeAfter{ch: ch, deadline: c.now.Add(d), seq: c.nextSeq})
	c.nextSeq++
	return ch
}

// AfterFunc schedules fn at deadline c.now + d; it fires during a later
// Advance. Unlike After, a d <= 0 cannot fire synchronously — invoking fn
// under the mutex would deadlock re-entrant registrations — so it registers
// at deadline == now and fires on the next Advance (in the same pass as any
// callback that registered it; see Advance).
func (c *Fake) AfterFunc(d time.Duration, fn func()) Stop {
	c.mu.Lock()
	defer c.mu.Unlock()
	t := &fakeTimer{parent: c, deadline: c.now.Add(d), fn: fn, seq: c.nextSeq}
	c.timers = append(c.timers, t)
	c.nextSeq++
	return t
}

// Advance moves time forward by d and fires everything whose deadline falls
// within the step, in two blocks:
//
//  1. CHANNEL block — pending After channels, (deadline, seq)-ordered,
//     non-blocking sends on the cap-1 buffers. Snapshot-once: an After
//     registered during this Advance does not fire in the same call.
//
//  2. CALLBACK block — AfterFunc timers, same ordering, via a DRAIN LOOP:
//     each fn runs with the mutex RELEASED (re-entrant registrations are
//     legal), fired is marked under the mutex BEFORE fn runs (a racing Stop
//     reports false), and a re-arm at deadline <= the new now fires in the
//     SAME Advance pass. Termination relies on callbacks not unconditionally
//     re-arming at d = 0 on every fire — a usage contract, not a Fake defect.
func (c *Fake) Advance(d time.Duration) {
	c.mu.Lock()
	c.now = c.now.Add(d)
	deadline := c.now
	var fires []*fakeAfter
	var keep []*fakeAfter
	for _, p := range c.pending {
		if !p.deadline.After(deadline) {
			fires = append(fires, p)
		} else {
			keep = append(keep, p)
		}
	}
	c.pending = keep
	c.mu.Unlock()

	sort.SliceStable(fires, func(i, j int) bool {
		if fires[i].deadline.Equal(fires[j].deadline) {
			return fires[i].seq < fires[j].seq
		}
		return fires[i].deadline.Before(fires[j].deadline)
	})
	for _, p := range fires {
		p.ch <- p.deadline
	}

	for {
		c.mu.Lock()
		var ready []*fakeTimer
		var remaining []*fakeTimer
		for _, t := range c.timers {
			if t.stopped || t.fired {
				continue
			}
			if !t.deadline.After(deadline) {
				ready = append(ready, t)
			} else {
				remaining = append(remaining, t)
			}
		}
		c.timers = remaining
		if len(ready) == 0 {
			c.mu.Unlock()
			return
		}
		sort.SliceStable(ready, func(i, j int) bool {
			if ready[i].deadline.Equal(ready[j].deadline) {
				return ready[i].seq < ready[j].seq
			}
			return ready[i].deadline.Before(ready[j].deadline)
		})
		for _, t := range ready {
			t.fired = true
		}
		c.mu.Unlock()
		for _, t := range ready {
			if t.fn != nil {
				t.fn()
			}
		}
	}
}
