Feature: Toolchain wrapper
  goplus build/test/run/vet regenerate the module, then delegate to the go
  tool verbatim, passing its exit code through. gen -stage writes and
  git-adds refreshed outputs — the pre-commit auto-fixer contract.

  Background:
    Given a file "go.mod":
      """
      module example.com/demo

      go 1.24
      """
    And a Go+ file "stack.gp":
      """
      package demo

      type Stack[T any] struct{ Items []T }

      func (s Stack[T]) Map[U any](f func(T) U) Stack[U] {
      	out := Stack[U]{Items: make([]U, 0, len(s.Items))}
      	for _, x := range s.Items {
      		out.Items = append(out.Items, f(x))
      	}
      	return out
      }
      """

  Scenario: goplus build regenerates before compiling
    When I run goplus with arguments "build ./..."
    Then the exit code is 0
    And the file "stack_gp.go" contains:
      """
      func Map[T any, U any](s Stack[T], f func(T) U) Stack[U] {
      """

  Scenario: goplus test regenerates, then runs go test against the emitted API
    Given a file "stack_test.go":
      """
      package demo

      import (
      	"strconv"
      	"testing"
      )

      func TestMap(t *testing.T) {
      	s := Stack[int]{Items: []int{1, 2}}
      	got := Map(s, strconv.Itoa)
      	if len(got.Items) != 2 || got.Items[0] != "1" {
      		t.Fatalf("got %v", got.Items)
      	}
      }
      """
    When I run goplus with arguments "test ./..."
    Then the exit code is 0
    And stdout contains "ok"

  Scenario: goplus vet passes go's exit code through
    When I run goplus with arguments "vet ./..."
    Then the exit code is 0

  Scenario: Generation diagnostics abort delegation before go runs
    Given a Go+ file "broken.gp":
      """
      package demo

      func Oops() int { return "no" }
      """
    When I run goplus with arguments "build ./..."
    Then the exit code is 2
    And stderr contains "broken.gp:3:"

  Scenario: gen -stage stages exactly the refreshed outputs
    Given a git repository
    When I run goplus with arguments "gen -stage ./..."
    Then the exit code is 0
    And the git staging area contains "stack_gp.go"

  Scenario: gen -stage stages the deletion of an orphaned output
    Given a file "gone_gp.go":
      """
      // Code generated by goplus from gone.gp. DO NOT EDIT.

      package demo
      """
    And a git repository
    When I run goplus with arguments "gen -stage ./..."
    Then the exit code is 0
    And the file "gone_gp.go" does not exist
    And the git staging area contains "gone_gp.go"
    And the git staging area contains "stack_gp.go"
