Feature: Toolchain wrapper
  gpp build/test/run/vet regenerate the module, then delegate to the go
  tool verbatim, passing its exit code through. gen -stage writes and
  git-adds refreshed outputs — the pre-commit auto-fixer contract.

  Background:
    Given a file "go.mod":
      """
      module example.com/demo

      go 1.24
      """
    And a G++ file "stack.gpp":
      """
      package demo

      type Stack[T any] struct{ Items []T }

      func (s Stack[T]) Map[U any](f func(T) U) Stack[U] {
      	out := Stack[U]{Items: make([]U, 0, len(s.Items))}
      	for _, x := range s.Items {
      		out.Items = append(out.Items, f(x))
      	}
      	return out
      }
      """

  Scenario: gpp build regenerates before compiling
    When I run gpp with arguments "build ./..."
    Then the exit code is 0
    And the file "stack_gpp.go" contains:
      """
      func StackMap[T any, U any](s Stack[T], f func(T) U) Stack[U] {
      """

  Scenario: gpp test regenerates, then runs go test against the emitted API
    Given a file "stack_test.go":
      """
      package demo

      import (
      	"strconv"
      	"testing"
      )

      func TestMap(t *testing.T) {
      	s := Stack[int]{Items: []int{1, 2}}
      	got := StackMap(s, strconv.Itoa)
      	if len(got.Items) != 2 || got.Items[0] != "1" {
      		t.Fatalf("got %v", got.Items)
      	}
      }
      """
    When I run gpp with arguments "test ./..."
    Then the exit code is 0
    And stdout contains "ok"

  Scenario: gpp vet passes go's exit code through
    When I run gpp with arguments "vet ./..."
    Then the exit code is 0

  Scenario: Generation diagnostics abort delegation before go runs
    Given a G++ file "broken.gpp":
      """
      package demo

      func Oops() int { return "no" }
      """
    When I run gpp with arguments "build ./..."
    Then the exit code is 2
    And stderr contains "broken.gpp:3:"

  Scenario: gen -stage stages exactly the refreshed outputs
    Given a git repository
    When I run gpp with arguments "gen -stage ./..."
    Then the exit code is 0
    And the git staging area contains "stack_gpp.go"

  Scenario: gen -stage stages the deletion of an orphaned output
    Given a file "gone_gpp.go":
      """
      // Code generated by gpp from gone.gpp. DO NOT EDIT.

      package demo
      """
    And a git repository
    When I run gpp with arguments "gen -stage ./..."
    Then the exit code is 0
    And the file "gone_gpp.go" does not exist
    And the git staging area contains "gone_gpp.go"
    And the git staging area contains "stack_gpp.go"
