// Code generated by goplus from smtlib.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package smtlib provides the solver-neutral SMT-LIB 2 syntax and command
// boundary used by native Go+ solvers.
package smtlib

import "iter"

import smt "goforge.dev/goplus/std/smt"

type Span struct {
	Start int
	End   int
}

//goplus:enum AtomKind
type AtomKind interface{ isAtomKind() }

//goplus:variant (AtomKind) SymbolAtom()
type SymbolAtom struct{}

func (SymbolAtom) isAtomKind() {}

//goplus:variant (AtomKind) KeywordAtom()
type KeywordAtom struct{}

func (KeywordAtom) isAtomKind() {}

//goplus:variant (AtomKind) NumeralAtom()
type NumeralAtom struct{}

func (NumeralAtom) isAtomKind() {}

//goplus:variant (AtomKind) DecimalAtom()
type DecimalAtom struct{}

func (DecimalAtom) isAtomKind() {}

//goplus:variant (AtomKind) StringAtom()
type StringAtom struct{}

func (StringAtom) isAtomKind() {}

// AtomKindCases selects one handler per AtomKind variant for AtomKindFold.
type AtomKindCases[R any] struct {
	SymbolAtom  func() R
	KeywordAtom func() R
	NumeralAtom func() R
	DecimalAtom func() R
	StringAtom  func() R
}

// AtomKindFold reduces AtomKind by one-level case analysis.
func AtomKindFold[R any](a AtomKind, cs AtomKindCases[R]) R {
	switch any(a).(type) {
	case SymbolAtom:
		return cs.SymbolAtom()
	case KeywordAtom:
		return cs.KeywordAtom()
	case NumeralAtom:
		return cs.NumeralAtom()
	case DecimalAtom:
		return cs.DecimalAtom()
	case StringAtom:
		return cs.StringAtom()
	default:
		panic("goplus: impossible enum value in AtomKindFold")
	}
}

// AtomKindEqOverrides carries optional per-variant hooks for AtomKindEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type AtomKindEqOverrides struct {
	SymbolAtom  func(x, y SymbolAtom) (eq, handled bool)
	KeywordAtom func(x, y KeywordAtom) (eq, handled bool)
	NumeralAtom func(x, y NumeralAtom) (eq, handled bool)
	DecimalAtom func(x, y DecimalAtom) (eq, handled bool)
	StringAtom  func(x, y StringAtom) (eq, handled bool)
}

// AtomKindEqualWith reports structural equality of a and b under ov.
func AtomKindEqualWith(a, b AtomKind, ov AtomKindEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case SymbolAtom:
		y, ok := any(b).(SymbolAtom)
		if !ok {
			return false
		}
		if ov.SymbolAtom != nil {
			if eq, handled := ov.SymbolAtom(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case KeywordAtom:
		y, ok := any(b).(KeywordAtom)
		if !ok {
			return false
		}
		if ov.KeywordAtom != nil {
			if eq, handled := ov.KeywordAtom(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case NumeralAtom:
		y, ok := any(b).(NumeralAtom)
		if !ok {
			return false
		}
		if ov.NumeralAtom != nil {
			if eq, handled := ov.NumeralAtom(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case DecimalAtom:
		y, ok := any(b).(DecimalAtom)
		if !ok {
			return false
		}
		if ov.DecimalAtom != nil {
			if eq, handled := ov.DecimalAtom(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case StringAtom:
		y, ok := any(b).(StringAtom)
		if !ok {
			return false
		}
		if ov.StringAtom != nil {
			if eq, handled := ov.StringAtom(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// AtomKindEqual reports structural equality of a and b.
func AtomKindEqual(a, b AtomKind) bool {
	return AtomKindEqualWith(a, b, AtomKindEqOverrides{})
}

//goplus:enum SExpr
type SExpr interface{ isSExpr() }

//goplus:variant (SExpr) Atom(Kind AtomKind, Text string, At Span)
type Atom struct {
	Kind AtomKind
	Text string
	At   Span
}

func (Atom) isSExpr() {}

//goplus:variant (SExpr) List(Values []SExpr, At Span)
type List struct {
	Values []SExpr
	At     Span
}

func (List) isSExpr() {}

// SExprCases selects one handler per SExpr variant for SExprFold.
type SExprCases[R any] struct {
	Atom func(Kind AtomKind, Text string, At Span) R
	List func(Values []SExpr, At Span) R
}

// SExprFold reduces SExpr by one-level case analysis.
func SExprFold[R any](s SExpr, cs SExprCases[R]) R {
	switch m := any(s).(type) {
	case Atom:
		return cs.Atom(m.Kind, m.Text, m.At)
	case List:
		return cs.List(m.Values, m.At)
	default:
		panic("goplus: impossible enum value in SExprFold")
	}
}

// SExprChildren lists the direct SExpr subterms of t.
func SExprChildren(t SExpr) []SExpr {
	var out []SExpr
	switch m := any(t).(type) {
	case List:
		for _, c0 := range m.Values {
			if c0 != nil {
				out = append(out, c0)
			}
		}
	}
	return out
}

// SExprUniverse yields t and all transitive SExpr subterms, preorder.
func SExprUniverse(t SExpr) iter.Seq[SExpr] {
	return func(yield func(SExpr) bool) {
		var walk func(SExpr) bool
		walk = func(cur SExpr) bool {
			if !yield(cur) {
				return false
			}
			for _, c := range SExprChildren(cur) {
				if !walk(c) {
					return false
				}
			}
			return true
		}
		walk(t)
	}
}

// SExprTransform rewrites t bottom-up: children first, then f at each node.
func SExprTransform(t SExpr, f func(SExpr) SExpr) SExpr {
	switch m := any(t).(type) {
	case List:
		if len(m.Values) > 0 {
			s1 := make([]SExpr, len(m.Values))
			for i1, x1 := range m.Values {
				s1[i1] = x1
				if x1 != nil {
					s1[i1] = SExprTransform(x1, f)
				}
			}
			m.Values = s1
		}
		return f(m)
	}
	return f(t)
}

// SExprEqOverrides carries optional per-variant hooks for SExprEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type SExprEqOverrides struct {
	Atom func(x, y Atom) (eq, handled bool)
	List func(x, y List) (eq, handled bool)
}

// SExprEqualWith reports structural equality of a and b under ov.
func SExprEqualWith(a, b SExpr, ov SExprEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case Atom:
		y, ok := any(b).(Atom)
		if !ok {
			return false
		}
		if ov.Atom != nil {
			if eq, handled := ov.Atom(x, y); handled {
				return eq
			}
		}
		if !AtomKindEqual(x.Kind, y.Kind) {
			return false
		}
		if x.Text != y.Text {
			return false
		}
		if x.At != y.At {
			return false
		}
		return true
	case List:
		y, ok := any(b).(List)
		if !ok {
			return false
		}
		if ov.List != nil {
			if eq, handled := ov.List(x, y); handled {
				return eq
			}
		}
		if len(x.Values) != len(y.Values) {
			return false
		}
		for i0 := range x.Values {
			if !SExprEqualWith(x.Values[i0], y.Values[i0], ov) {
				return false
			}
		}
		if x.At != y.At {
			return false
		}
		return true
	}
	return false
}

// SExprEqual reports structural equality of a and b.
func SExprEqual(a, b SExpr) bool {
	return SExprEqualWith(a, b, SExprEqOverrides{})
}

//goplus:enum Command
type Command interface{ isCommand() }

//goplus:variant (Command) SetLogic(Name string, At Span)
type SetLogic struct {
	Name string
	At   Span
}

func (SetLogic) isCommand() {}

//goplus:variant (Command) SetOption(Name string, Value SExpr, At Span)
type SetOption struct {
	Name  string
	Value SExpr
	At    Span
}

func (SetOption) isCommand() {}

//goplus:variant (Command) DeclareSort(Name string, Arity int, At Span)
type DeclareSort struct {
	Name  string
	Arity int
	At    Span
}

func (DeclareSort) isCommand() {}

//goplus:variant (Command) DeclareConst(Name string, Sort SExpr, At Span)
type DeclareConst struct {
	Name string
	Sort SExpr
	At   Span
}

func (DeclareConst) isCommand() {}

//goplus:variant (Command) DeclareFun(Name string, Domain []SExpr, Range SExpr, At Span)
type DeclareFun struct {
	Name   string
	Domain []SExpr
	Range  SExpr
	At     Span
}

func (DeclareFun) isCommand() {}

//goplus:variant (Command) Assert(Term SExpr, At Span)
type Assert struct {
	Term SExpr
	At   Span
}

func (Assert) isCommand() {}

//goplus:variant (Command) CheckSat(At Span)
type CheckSat struct {
	At Span
}

func (CheckSat) isCommand() {}

//goplus:variant (Command) CheckSatAssuming(Assumptions []SExpr, At Span)
type CheckSatAssuming struct {
	Assumptions []SExpr
	At          Span
}

func (CheckSatAssuming) isCommand() {}

//goplus:variant (Command) Push(Levels int, At Span)
type Push struct {
	Levels int
	At     Span
}

func (Push) isCommand() {}

//goplus:variant (Command) Pop(Levels int, At Span)
type Pop struct {
	Levels int
	At     Span
}

func (Pop) isCommand() {}

//goplus:variant (Command) GetModel(At Span)
type GetModel struct {
	At Span
}

func (GetModel) isCommand() {}

//goplus:variant (Command) GetValue(Terms []SExpr, At Span)
type GetValue struct {
	Terms []SExpr
	At    Span
}

func (GetValue) isCommand() {}

//goplus:variant (Command) Exit(At Span)
type Exit struct {
	At Span
}

func (Exit) isCommand() {}

//goplus:variant (Command) RawCommand(Name string, Arguments []SExpr, At Span)
type RawCommand struct {
	Name      string
	Arguments []SExpr
	At        Span
}

func (RawCommand) isCommand() {}

// CommandCases selects one handler per Command variant for CommandFold.
type CommandCases[R any] struct {
	SetLogic         func(Name string, At Span) R
	SetOption        func(Name string, Value SExpr, At Span) R
	DeclareSort      func(Name string, Arity int, At Span) R
	DeclareConst     func(Name string, Sort SExpr, At Span) R
	DeclareFun       func(Name string, Domain []SExpr, Range SExpr, At Span) R
	Assert           func(Term SExpr, At Span) R
	CheckSat         func(At Span) R
	CheckSatAssuming func(Assumptions []SExpr, At Span) R
	Push             func(Levels int, At Span) R
	Pop              func(Levels int, At Span) R
	GetModel         func(At Span) R
	GetValue         func(Terms []SExpr, At Span) R
	Exit             func(At Span) R
	RawCommand       func(Name string, Arguments []SExpr, At Span) R
}

// CommandFold reduces Command by one-level case analysis.
func CommandFold[R any](v Command, cs CommandCases[R]) R {
	switch m := any(v).(type) {
	case SetLogic:
		return cs.SetLogic(m.Name, m.At)
	case SetOption:
		return cs.SetOption(m.Name, m.Value, m.At)
	case DeclareSort:
		return cs.DeclareSort(m.Name, m.Arity, m.At)
	case DeclareConst:
		return cs.DeclareConst(m.Name, m.Sort, m.At)
	case DeclareFun:
		return cs.DeclareFun(m.Name, m.Domain, m.Range, m.At)
	case Assert:
		return cs.Assert(m.Term, m.At)
	case CheckSat:
		return cs.CheckSat(m.At)
	case CheckSatAssuming:
		return cs.CheckSatAssuming(m.Assumptions, m.At)
	case Push:
		return cs.Push(m.Levels, m.At)
	case Pop:
		return cs.Pop(m.Levels, m.At)
	case GetModel:
		return cs.GetModel(m.At)
	case GetValue:
		return cs.GetValue(m.Terms, m.At)
	case Exit:
		return cs.Exit(m.At)
	case RawCommand:
		return cs.RawCommand(m.Name, m.Arguments, m.At)
	default:
		panic("goplus: impossible enum value in CommandFold")
	}
}

// CommandEqOverrides carries optional per-variant hooks for CommandEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type CommandEqOverrides struct {
	SetLogic         func(x, y SetLogic) (eq, handled bool)
	SetOption        func(x, y SetOption) (eq, handled bool)
	DeclareSort      func(x, y DeclareSort) (eq, handled bool)
	DeclareConst     func(x, y DeclareConst) (eq, handled bool)
	DeclareFun       func(x, y DeclareFun) (eq, handled bool)
	Assert           func(x, y Assert) (eq, handled bool)
	CheckSat         func(x, y CheckSat) (eq, handled bool)
	CheckSatAssuming func(x, y CheckSatAssuming) (eq, handled bool)
	Push             func(x, y Push) (eq, handled bool)
	Pop              func(x, y Pop) (eq, handled bool)
	GetModel         func(x, y GetModel) (eq, handled bool)
	GetValue         func(x, y GetValue) (eq, handled bool)
	Exit             func(x, y Exit) (eq, handled bool)
	RawCommand       func(x, y RawCommand) (eq, handled bool)
}

// CommandEqualWith reports structural equality of a and b under ov.
func CommandEqualWith(a, b Command, ov CommandEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case SetLogic:
		y, ok := any(b).(SetLogic)
		if !ok {
			return false
		}
		if ov.SetLogic != nil {
			if eq, handled := ov.SetLogic(x, y); handled {
				return eq
			}
		}
		if x.Name != y.Name {
			return false
		}
		if x.At != y.At {
			return false
		}
		return true
	case SetOption:
		y, ok := any(b).(SetOption)
		if !ok {
			return false
		}
		if ov.SetOption != nil {
			if eq, handled := ov.SetOption(x, y); handled {
				return eq
			}
		}
		if x.Name != y.Name {
			return false
		}
		if !SExprEqual(x.Value, y.Value) {
			return false
		}
		if x.At != y.At {
			return false
		}
		return true
	case DeclareSort:
		y, ok := any(b).(DeclareSort)
		if !ok {
			return false
		}
		if ov.DeclareSort != nil {
			if eq, handled := ov.DeclareSort(x, y); handled {
				return eq
			}
		}
		if x.Name != y.Name {
			return false
		}
		if x.Arity != y.Arity {
			return false
		}
		if x.At != y.At {
			return false
		}
		return true
	case DeclareConst:
		y, ok := any(b).(DeclareConst)
		if !ok {
			return false
		}
		if ov.DeclareConst != nil {
			if eq, handled := ov.DeclareConst(x, y); handled {
				return eq
			}
		}
		if x.Name != y.Name {
			return false
		}
		if !SExprEqual(x.Sort, y.Sort) {
			return false
		}
		if x.At != y.At {
			return false
		}
		return true
	case DeclareFun:
		y, ok := any(b).(DeclareFun)
		if !ok {
			return false
		}
		if ov.DeclareFun != nil {
			if eq, handled := ov.DeclareFun(x, y); handled {
				return eq
			}
		}
		if x.Name != y.Name {
			return false
		}
		if len(x.Domain) != len(y.Domain) {
			return false
		}
		for i0 := range x.Domain {
			if !SExprEqual(x.Domain[i0], y.Domain[i0]) {
				return false
			}
		}
		if !SExprEqual(x.Range, y.Range) {
			return false
		}
		if x.At != y.At {
			return false
		}
		return true
	case Assert:
		y, ok := any(b).(Assert)
		if !ok {
			return false
		}
		if ov.Assert != nil {
			if eq, handled := ov.Assert(x, y); handled {
				return eq
			}
		}
		if !SExprEqual(x.Term, y.Term) {
			return false
		}
		if x.At != y.At {
			return false
		}
		return true
	case CheckSat:
		y, ok := any(b).(CheckSat)
		if !ok {
			return false
		}
		if ov.CheckSat != nil {
			if eq, handled := ov.CheckSat(x, y); handled {
				return eq
			}
		}
		if x.At != y.At {
			return false
		}
		return true
	case CheckSatAssuming:
		y, ok := any(b).(CheckSatAssuming)
		if !ok {
			return false
		}
		if ov.CheckSatAssuming != nil {
			if eq, handled := ov.CheckSatAssuming(x, y); handled {
				return eq
			}
		}
		if len(x.Assumptions) != len(y.Assumptions) {
			return false
		}
		for i1 := range x.Assumptions {
			if !SExprEqual(x.Assumptions[i1], y.Assumptions[i1]) {
				return false
			}
		}
		if x.At != y.At {
			return false
		}
		return true
	case Push:
		y, ok := any(b).(Push)
		if !ok {
			return false
		}
		if ov.Push != nil {
			if eq, handled := ov.Push(x, y); handled {
				return eq
			}
		}
		if x.Levels != y.Levels {
			return false
		}
		if x.At != y.At {
			return false
		}
		return true
	case Pop:
		y, ok := any(b).(Pop)
		if !ok {
			return false
		}
		if ov.Pop != nil {
			if eq, handled := ov.Pop(x, y); handled {
				return eq
			}
		}
		if x.Levels != y.Levels {
			return false
		}
		if x.At != y.At {
			return false
		}
		return true
	case GetModel:
		y, ok := any(b).(GetModel)
		if !ok {
			return false
		}
		if ov.GetModel != nil {
			if eq, handled := ov.GetModel(x, y); handled {
				return eq
			}
		}
		if x.At != y.At {
			return false
		}
		return true
	case GetValue:
		y, ok := any(b).(GetValue)
		if !ok {
			return false
		}
		if ov.GetValue != nil {
			if eq, handled := ov.GetValue(x, y); handled {
				return eq
			}
		}
		if len(x.Terms) != len(y.Terms) {
			return false
		}
		for i2 := range x.Terms {
			if !SExprEqual(x.Terms[i2], y.Terms[i2]) {
				return false
			}
		}
		if x.At != y.At {
			return false
		}
		return true
	case Exit:
		y, ok := any(b).(Exit)
		if !ok {
			return false
		}
		if ov.Exit != nil {
			if eq, handled := ov.Exit(x, y); handled {
				return eq
			}
		}
		if x.At != y.At {
			return false
		}
		return true
	case RawCommand:
		y, ok := any(b).(RawCommand)
		if !ok {
			return false
		}
		if ov.RawCommand != nil {
			if eq, handled := ov.RawCommand(x, y); handled {
				return eq
			}
		}
		if x.Name != y.Name {
			return false
		}
		if len(x.Arguments) != len(y.Arguments) {
			return false
		}
		for i3 := range x.Arguments {
			if !SExprEqual(x.Arguments[i3], y.Arguments[i3]) {
				return false
			}
		}
		if x.At != y.At {
			return false
		}
		return true
	}
	return false
}

// CommandEqual reports structural equality of a and b.
func CommandEqual(a, b Command) bool {
	return CommandEqualWith(a, b, CommandEqOverrides{})
}

type ParseError struct {
	Message string
	At      Span
}

//goplus:enum ParseResult
type ParseResult interface{ isParseResult() }

//goplus:variant (ParseResult) Parsed(Commands []Command)
type Parsed struct {
	Commands []Command
}

func (Parsed) isParseResult() {}

//goplus:variant (ParseResult) Rejected(Errors []ParseError)
type Rejected struct {
	Errors []ParseError
}

func (Rejected) isParseResult() {}

// ParseResultCases selects one handler per ParseResult variant for ParseResultFold.
type ParseResultCases[R any] struct {
	Parsed   func(Commands []Command) R
	Rejected func(Errors []ParseError) R
}

// ParseResultFold reduces ParseResult by one-level case analysis.
func ParseResultFold[R any](p ParseResult, cs ParseResultCases[R]) R {
	switch m := any(p).(type) {
	case Parsed:
		return cs.Parsed(m.Commands)
	case Rejected:
		return cs.Rejected(m.Errors)
	default:
		panic("goplus: impossible enum value in ParseResultFold")
	}
}

// ParseResultEqOverrides carries optional per-variant hooks for ParseResultEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type ParseResultEqOverrides struct {
	Parsed   func(x, y Parsed) (eq, handled bool)
	Rejected func(x, y Rejected) (eq, handled bool)
}

// ParseResultEqualWith reports structural equality of a and b under ov.
func ParseResultEqualWith(a, b ParseResult, ov ParseResultEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case Parsed:
		y, ok := any(b).(Parsed)
		if !ok {
			return false
		}
		if ov.Parsed != nil {
			if eq, handled := ov.Parsed(x, y); handled {
				return eq
			}
		}
		if len(x.Commands) != len(y.Commands) {
			return false
		}
		for i0 := range x.Commands {
			if !CommandEqual(x.Commands[i0], y.Commands[i0]) {
				return false
			}
		}
		return true
	case Rejected:
		y, ok := any(b).(Rejected)
		if !ok {
			return false
		}
		if ov.Rejected != nil {
			if eq, handled := ov.Rejected(x, y); handled {
				return eq
			}
		}
		if len(x.Errors) != len(y.Errors) {
			return false
		}
		for i1 := range x.Errors {
			if x.Errors[i1] != y.Errors[i1] {
				return false
			}
		}
		return true
	}
	return false
}

// ParseResultEqual reports structural equality of a and b.
func ParseResultEqual(a, b ParseResult) bool {
	return ParseResultEqualWith(a, b, ParseResultEqOverrides{})
}

//goplus:enum Value
type Value interface{ isValue() }

//goplus:variant (Value) BooleanValue(Expression SExpr, Value bool)
type BooleanValue struct {
	Expression SExpr
	Value      bool
}

func (BooleanValue) isValue() {}

//goplus:variant (Value) IntegerValue(Expression SExpr, Value int64)
type IntegerValue struct {
	Expression SExpr
	Value      int64
}

func (IntegerValue) isValue() {}

//goplus:variant (Value) ArbitraryIntegerValue(Expression SExpr, Value smt.IntegerValue)
type ArbitraryIntegerValue struct {
	Expression SExpr
	Value      smt.IntegerValue
}

func (ArbitraryIntegerValue) isValue() {}

//goplus:variant (Value) RationalValue(Expression SExpr, Value smt.Rational)
type RationalValue struct {
	Expression SExpr
	Value      smt.Rational
}

func (RationalValue) isValue() {}

//goplus:variant (Value) BitVectorValue(Expression SExpr, Value smt.BitVectorValue)
type BitVectorValue struct {
	Expression SExpr
	Value      smt.BitVectorValue
}

func (BitVectorValue) isValue() {}

//goplus:variant (Value) DatatypeValue(Expression SExpr, Value smt.DatatypeValue)
type DatatypeValue struct {
	Expression SExpr
	Value      smt.DatatypeValue
}

func (DatatypeValue) isValue() {}

//goplus:variant (Value) UnavailableValue(Expression SExpr, Reason string)
type UnavailableValue struct {
	Expression SExpr
	Reason     string
}

func (UnavailableValue) isValue() {}

// ValueCases selects one handler per Value variant for ValueFold.
type ValueCases[R any] struct {
	BooleanValue          func(Expression SExpr, Value bool) R
	IntegerValue          func(Expression SExpr, Value int64) R
	ArbitraryIntegerValue func(Expression SExpr, Value smt.IntegerValue) R
	RationalValue         func(Expression SExpr, Value smt.Rational) R
	BitVectorValue        func(Expression SExpr, Value smt.BitVectorValue) R
	DatatypeValue         func(Expression SExpr, Value smt.DatatypeValue) R
	UnavailableValue      func(Expression SExpr, Reason string) R
}

// ValueFold reduces Value by one-level case analysis.
func ValueFold[R any](v Value, cs ValueCases[R]) R {
	switch m := any(v).(type) {
	case BooleanValue:
		return cs.BooleanValue(m.Expression, m.Value)
	case IntegerValue:
		return cs.IntegerValue(m.Expression, m.Value)
	case ArbitraryIntegerValue:
		return cs.ArbitraryIntegerValue(m.Expression, m.Value)
	case RationalValue:
		return cs.RationalValue(m.Expression, m.Value)
	case BitVectorValue:
		return cs.BitVectorValue(m.Expression, m.Value)
	case DatatypeValue:
		return cs.DatatypeValue(m.Expression, m.Value)
	case UnavailableValue:
		return cs.UnavailableValue(m.Expression, m.Reason)
	default:
		panic("goplus: impossible enum value in ValueFold")
	}
}

// ValueEqOverrides carries optional per-variant hooks for ValueEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type ValueEqOverrides struct {
	BooleanValue          func(x, y BooleanValue) (eq, handled bool)
	IntegerValue          func(x, y IntegerValue) (eq, handled bool)
	ArbitraryIntegerValue func(x, y ArbitraryIntegerValue) (eq, handled bool)
	RationalValue         func(x, y RationalValue) (eq, handled bool)
	BitVectorValue        func(x, y BitVectorValue) (eq, handled bool)
	DatatypeValue         func(x, y DatatypeValue) (eq, handled bool)
	UnavailableValue      func(x, y UnavailableValue) (eq, handled bool)
}

// ValueEqualWith reports structural equality of a and b under ov.
func ValueEqualWith(a, b Value, ov ValueEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case BooleanValue:
		y, ok := any(b).(BooleanValue)
		if !ok {
			return false
		}
		if ov.BooleanValue != nil {
			if eq, handled := ov.BooleanValue(x, y); handled {
				return eq
			}
		}
		if !SExprEqual(x.Expression, y.Expression) {
			return false
		}
		if x.Value != y.Value {
			return false
		}
		return true
	case IntegerValue:
		y, ok := any(b).(IntegerValue)
		if !ok {
			return false
		}
		if ov.IntegerValue != nil {
			if eq, handled := ov.IntegerValue(x, y); handled {
				return eq
			}
		}
		if !SExprEqual(x.Expression, y.Expression) {
			return false
		}
		if x.Value != y.Value {
			return false
		}
		return true
	case ArbitraryIntegerValue:
		y, ok := any(b).(ArbitraryIntegerValue)
		if !ok {
			return false
		}
		if ov.ArbitraryIntegerValue != nil {
			if eq, handled := ov.ArbitraryIntegerValue(x, y); handled {
				return eq
			}
		}
		if !SExprEqual(x.Expression, y.Expression) {
			return false
		}
		if x.Value != y.Value {
			return false
		}
		return true
	case RationalValue:
		y, ok := any(b).(RationalValue)
		if !ok {
			return false
		}
		if ov.RationalValue != nil {
			if eq, handled := ov.RationalValue(x, y); handled {
				return eq
			}
		}
		if !SExprEqual(x.Expression, y.Expression) {
			return false
		}
		if x.Value != y.Value {
			return false
		}
		return true
	case BitVectorValue:
		y, ok := any(b).(BitVectorValue)
		if !ok {
			return false
		}
		if ov.BitVectorValue != nil {
			if eq, handled := ov.BitVectorValue(x, y); handled {
				return eq
			}
		}
		if !SExprEqual(x.Expression, y.Expression) {
			return false
		}
		if x.Value != y.Value {
			return false
		}
		return true
	case DatatypeValue:
		y, ok := any(b).(DatatypeValue)
		if !ok {
			return false
		}
		if ov.DatatypeValue != nil {
			if eq, handled := ov.DatatypeValue(x, y); handled {
				return eq
			}
		}
		if !SExprEqual(x.Expression, y.Expression) {
			return false
		}
		if x.Value != y.Value {
			return false
		}
		return true
	case UnavailableValue:
		y, ok := any(b).(UnavailableValue)
		if !ok {
			return false
		}
		if ov.UnavailableValue != nil {
			if eq, handled := ov.UnavailableValue(x, y); handled {
				return eq
			}
		}
		if !SExprEqual(x.Expression, y.Expression) {
			return false
		}
		if x.Reason != y.Reason {
			return false
		}
		return true
	}
	return false
}

// ValueEqual reports structural equality of a and b.
func ValueEqual(a, b Value) bool {
	return ValueEqualWith(a, b, ValueEqOverrides{})
}

//goplus:enum Response
//goplus:derive off
type Response interface{ isResponse() }

//goplus:variant (Response) Acknowledged(CommandIndex int)
type Acknowledged struct {
	CommandIndex int
}

func (Acknowledged) isResponse() {}

//goplus:variant (Response) Satisfiable(Model smt.Model)
type Satisfiable struct {
	Model smt.Model
}

func (Satisfiable) isResponse() {}

//goplus:variant (Response) Unsatisfiable(Proof smt.Proof)
type Unsatisfiable struct {
	Proof smt.Proof
}

func (Unsatisfiable) isResponse() {}

//goplus:variant (Response) Unknown(Proof smt.Proof, Reason smt.UnknownReason)
type Unknown struct {
	Proof  smt.Proof
	Reason smt.UnknownReason
}

func (Unknown) isResponse() {}

//goplus:variant (Response) AssumptionsUnsatisfiable(Proof smt.Proof, Indices []int)
type AssumptionsUnsatisfiable struct {
	Proof   smt.Proof
	Indices []int
}

func (AssumptionsUnsatisfiable) isResponse() {}

//goplus:variant (Response) ModelAvailable(Model smt.Model)
type ModelAvailable struct {
	Model smt.Model
}

func (ModelAvailable) isResponse() {}

//goplus:variant (Response) ValuesAvailable(Values []Value)
type ValuesAvailable struct {
	Values []Value
}

func (ValuesAvailable) isResponse() {}

type ExecutionError struct {
	CommandIndex int
	Message      string
	At           Span
}

//goplus:enum ExecutionResult
//goplus:derive off
type ExecutionResult interface{ isExecutionResult() }

//goplus:variant (ExecutionResult) Executed(Responses []Response)
type Executed struct {
	Responses []Response
}

func (Executed) isExecutionResult() {}

//goplus:variant (ExecutionResult) ExecutionFailed(Responses []Response, Errors []ExecutionError)
type ExecutionFailed struct {
	Responses []Response
	Errors    []ExecutionError
}

func (ExecutionFailed) isExecutionResult() {}

//goplus:variant (ExecutionResult) ScriptRejected(Errors []ParseError)
type ScriptRejected struct {
	Errors []ParseError
}

func (ScriptRejected) isExecutionResult() {}

func Parse(source string) ParseResult {
	commands, errors := parseSMTLib(source)
	if len(errors) != 0 {
		return Rejected{Errors: errors}
	}
	return Parsed{Commands: commands}
}

func Format(commands []Command) string         { return formatCommands(commands) }
func FormatExpression(expression SExpr) string { return formatExpression(expression) }
func Execute(source string) ExecutionResult {
	switch __gp_m0 := any(Parse(source)).(type) {
	case Rejected:
		errors := __gp_m0.Errors
		return ScriptRejected{Errors: errors}
	case Parsed:
		commands := __gp_m0.Commands

		responses, errors := executeCommands(commands)
		if len(errors) != 0 {
			return ExecutionFailed{Responses: responses, Errors: errors}
		}
		return Executed{Responses: responses}
	default:
		panic("goplus: impossible enum value in match")
	}
}
