// Package emit assembles, formats, and writes generated Go files.
package emit

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// GeneratedSuffix is the filename suffix of emitted files: foo.gpp emits
// foo_gpp.go in the same directory.
const GeneratedSuffix = "_gpp.go"

// OutputPath returns the emitted filename for a .gpp source path.
func OutputPath(gppPath string) string {
	return strings.TrimSuffix(gppPath, ".gpp") + GeneratedSuffix
}

// Header renders the generated-code header for a source file basename. It
// matches the convention regexp in https://go.dev/s/generatedcode and
// carries no timestamps or versions, keeping output byte-stable.
func Header(gppBase string) string {
	return fmt.Sprintf("// Code generated by gpp from %s. DO NOT EDIT.\n\n", gppBase)
}

var headerRe = regexp.MustCompile(`^// Code generated by gpp from (\S+)\. DO NOT EDIT\.$`)

// GeneratedFrom reports whether src starts with a gpp header and, if so,
// which .gpp basename it was generated from.
func GeneratedFrom(src []byte) (string, bool) {
	firstLine, _, _ := strings.Cut(string(src), "\n")
	m := headerRe.FindStringSubmatch(firstLine)
	if m == nil {
		return "", false
	}
	return m[1], true
}

// Finish prepends the header and gofmt-formats the assembled output.
func Finish(gppBase string, body []byte) ([]byte, error) {
	out := append([]byte(Header(gppBase)), body...)
	formatted, err := format.Source(out)
	if err != nil {
		return nil, fmt.Errorf("internal error: generated output does not format: %w", err)
	}
	return formatted, nil
}

// WriteIfChanged writes content to path only when the on-disk bytes differ,
// avoiding mtime churn. It reports whether a write happened.
func WriteIfChanged(path string, content []byte) (bool, error) {
	if existing, err := os.ReadFile(path); err == nil && string(existing) == string(content) {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	return true, os.WriteFile(path, content, 0o644)
}

// Refusal explains why an output path cannot be written.
type Refusal struct {
	Path   string
	Reason string
}

// CheckOverwrite refuses to clobber a file that exists but does not carry a
// gpp header — it may be hand-written code whose name merely matches.
func CheckOverwrite(path string) *Refusal {
	src, err := os.ReadFile(path)
	if err != nil {
		return nil // absent or unreadable: writing will surface real errors
	}
	if _, ok := GeneratedFrom(src); !ok {
		return &Refusal{Path: path, Reason: "exists but was not generated by gpp; refusing to overwrite"}
	}
	return nil
}
