// Package emit assembles, formats, and writes generated Go files.
package emit

import (
	"goforge.dev/goplus/internal/version"

	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// GeneratedSuffix is the filename suffix of emitted files: foo.gp emits
// foo_gp.go in the same directory.
const GeneratedSuffix = "_gp.go"

// OutputPath returns the emitted filename for a .gp source path.
func OutputPath(goplusPath string) string {
	// Test sources stay test sources: foo_test.gp emits foo_gp_test.go
	// so the go tool still sees a _test.go file (v0.10.0).
	if base, ok := strings.CutSuffix(goplusPath, "_test.gp"); ok {
		return base + "_gp_test.go"
	}
	return strings.TrimSuffix(goplusPath, ".gp") + GeneratedSuffix
}

// Header renders the generated-code header for a source file basename. It
// matches the convention regexp in https://go.dev/s/generatedcode and
// carries no timestamps or versions, keeping output byte-stable.
func Header(goplusBase string) string {
	return fmt.Sprintf("// Code generated by goplus from %s. DO NOT EDIT.\n%s %s\n\n", goplusBase, VintagePrefix, version.Version)
}

// VintagePrefix marks the toolchain version that generated a file.
// Older toolchains ignore it; newer ones refuse files from the future.
const VintagePrefix = "//goplus:v"

// Vintage extracts a file's generation version ("" when unstamped —
// files from toolchains before v0.9.0).
func Vintage(src []byte) string {
	for _, line := range strings.SplitN(string(src), "\n", 4) {
		if rest, ok := strings.CutPrefix(line, VintagePrefix+" "); ok {
			return strings.TrimSpace(rest)
		}
	}
	return ""
}

var headerRe = regexp.MustCompile(`^// Code generated by goplus from (\S+)\. DO NOT EDIT\.$`)

// GeneratedFrom reports whether src starts with a goplus header and, if so,
// which .gp basename it was generated from.
func GeneratedFrom(src []byte) (string, bool) {
	firstLine, _, _ := strings.Cut(string(src), "\n")
	m := headerRe.FindStringSubmatch(firstLine)
	if m == nil {
		return "", false
	}
	return m[1], true
}

// Finish prepends the header and gofmt-formats the assembled output.
func Finish(goplusBase string, body []byte) ([]byte, error) {
	out := append([]byte(Header(goplusBase)), body...)
	formatted, err := format.Source(out)
	if err != nil {
		return nil, fmt.Errorf("internal error: generated output does not format: %w", err)
	}
	return formatted, nil
}

// WriteIfChanged writes content to path only when the on-disk bytes differ,
// avoiding mtime churn. It reports whether a write happened.
func WriteIfChanged(path string, content []byte) (bool, error) {
	if existing, err := os.ReadFile(path); err == nil && string(existing) == string(content) {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	return true, os.WriteFile(path, content, 0o644)
}

// Refusal explains why an output path cannot be written.
type Refusal struct {
	Path   string
	Reason string
}

// CheckOverwrite refuses to clobber a file that exists but does not carry a
// goplus header — it may be hand-written code whose name merely matches.
func CheckOverwrite(path string) *Refusal {
	src, err := os.ReadFile(path)
	if err != nil {
		return nil // absent or unreadable: writing will surface real errors
	}
	if _, ok := GeneratedFrom(src); !ok {
		return &Refusal{Path: path, Reason: "exists but was not generated by goplus; refusing to overwrite"}
	}
	return nil
}
