// Code generated by goplus from vec.gp. DO NOT EDIT.
//goplus:v v0.24.1

// Package vec is a length-indexed sequence: Vec[T, n] carries its
// length in its type, so First and Rest exist only for non-empty
// vectors — the checker proves it, erasure drops it, and the generated
// Go stays a plain cons-list any Go program can use (guarded at the
// exported boundary).
package vec

//goplus:enum Vec[T any, n nat]
type Vec[T any] interface{ isVec(T) }

//goplus:variant (Vec[T]) Nil() Vec[T, 0]
type Nil[T any] struct{}

func (Nil[T]) isVec(T) {}

//goplus:variant (Vec[T]) Cons(Head T, Tail Vec[T, n]) Vec[T, n+1]
type Cons[T any] struct {
	Head T
	Tail Vec[T]
}

func (Cons[T]) isVec(T) {}

// VecCases selects one handler per Vec variant for Fold.
type VecCases[T any, R any] struct {
	Nil  func() R
	Cons func(Head T, Tail Vec[T]) R
}

// Fold reduces Vec[T] by one-level case analysis.
func Fold[T any, R any](v Vec[T], cs VecCases[T, R]) R {
	switch m := any(v).(type) {
	case Nil[T]:
		return cs.Nil()
	case Cons[T]:
		return cs.Cons(m.Head, m.Tail)
	default:
		panic("goplus: impossible enum value in Fold")
	}
}

// First returns the head of a non-empty vector.
//
//goplus:dep First[T any](0 n nat, v Vec[T, n+1]) T
func First[T any](v Vec[T]) T {
	if _, ok := any(v).(Nil[T]); ok {
		panic("goplus: First: v with index n+1 cannot be Nil")
	}
	switch __gp_m0 := any(v).(type) {
	case Cons[T]:
		h := __gp_m0.Head
		t := __gp_m0.Tail

		_ = t
		return h
	default:
		panic("goplus: impossible enum value in match")
	}
}

// Rest returns everything after the head of a non-empty vector.
//
//goplus:dep Rest[T any](0 n nat, v Vec[T, n+1]) Vec[T, n]
func Rest[T any](v Vec[T]) Vec[T] {
	if _, ok := any(v).(Nil[T]); ok {
		panic("goplus: Rest: v with index n+1 cannot be Nil")
	}
	switch __gp_m1 := any(v).(type) {
	case Cons[T]:
		h := __gp_m1.Head
		t := __gp_m1.Tail

		_ = h
		return t
	default:
		panic("goplus: impossible enum value in match")
	}
}

// Length walks the spine; the result equals the index by construction.
//
//goplus:dep Length[T any](0 n nat, v Vec[T, n]) int
func Length[T any](v Vec[T]) int {
	total := 0
	switch __gp_m2 := any(v).(type) {
	case Nil[T]:

	case Cons[T]:
		h := __gp_m2.Head
		t := __gp_m2.Tail

		_ = h
		total = Length(t) + 1
	default:
		panic("goplus: impossible enum value in match")
	}
	return total
}

// Replicate builds the vector of n copies of x.
//
//goplus:dep Replicate[T any](n nat, x T) Vec[T, n]
func Replicate[T any](n int, x T) Vec[T] {
	if n == 0 {
		return Nil[T]{}
	}
	return Cons[T]{Head: x, Tail: Replicate(n-1, x)}
}

// Concat appends b to a; the indices add.
//
//goplus:dep Concat[T any](0 n nat, 0 m nat, a Vec[T, n], b Vec[T, m]) Vec[T, n+m]
func Concat[T any](a Vec[T], b Vec[T]) Vec[T] {
	switch __gp_m3 := any(a).(type) {
	case Nil[T]:

		return b
	case Cons[T]:
		h := __gp_m3.Head
		t := __gp_m3.Tail

		return Cons[T]{Head: h, Tail: Concat(t, b)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

// Map transforms every element, preserving the length.
//
//goplus:dep Map[T any, U any](0 n nat, f func(T) U, v Vec[T, n]) Vec[U, n]
func Map[T any, U any](f func(T) U, v Vec[T]) Vec[U] {
	switch __gp_m4 := any(v).(type) {
	case Nil[T]:

		return Nil[U]{}
	case Cons[T]:
		h := __gp_m4.Head
		t := __gp_m4.Tail

		return Cons[U]{Head: f(h), Tail: Map(f, t)}
	default:
		panic("goplus: impossible enum value in match")
	}
}
