// Code generated by goplus from floating_point.gp. DO NOT EDIT.
//goplus:v v0.28.0

package smt

// FloatingPointValue[e,s] is an exact SMT-LIB floating-point bit pattern.
// The exponent width e and significand width s (including the hidden bit) are
// retained as Go+ indices. The IEEE interchange encoding therefore has e+s
// bits: one sign bit, e exponent bits, and s-1 trailing significand bits.
//
// This is the ground-value foundation for floating-point support. It does not
// imply symbolic QF_FP arithmetic or rounding-mode support.
//
//goplus:enum FloatingPointValue[e nat, s nat]
//goplus:derive off
//goplus:repr transparent
type FloatingPointValue = floatingPointValue

//goplus:variant (FloatingPointValue) floatingPointValue(ExponentBits int, SignificandBits int, Bits BitVectorValue) FloatingPointValue[e, s]
type floatingPointValue struct {
	exponentBits    int
	significandBits int
	bits            BitVectorValue
}

func (floatingPointValue) isFloatingPointValue() {}

//goplus:dep FloatingPointFromBits(exponentBits nat, significandBits nat, bits BitVectorValue) FloatingPointValue[exponentBits, significandBits]
func FloatingPointFromBits(exponentBits int, significandBits int, bits BitVectorValue) FloatingPointValue {
	if exponentBits < 2 {
		panic("smt: floating-point exponent width must be at least 2")
	}
	if significandBits < 2 {
		panic("smt: floating-point significand width must be at least 2")
	}
	if bits.Width() != int(exponentBits+significandBits) {
		panic("smt: floating-point bit-pattern width mismatch")
	}
	return floatingPointValue{exponentBits: int(exponentBits), significandBits: int(significandBits), bits: bits}
}

//goplus:dep FloatingPointFromUint64(exponentBits nat, significandBits nat, bits uint64) FloatingPointValue[exponentBits, significandBits]
func FloatingPointFromUint64(exponentBits int, significandBits int, bits uint64) FloatingPointValue {
	return FloatingPointFromBits(exponentBits, significandBits, NewBitVectorUint64(int(exponentBits+significandBits), bits))
}

//goplus:dep FloatingPointBits(0 e nat, 0 s nat, value FloatingPointValue[e, s]) BitVectorValue
func FloatingPointBits(value FloatingPointValue) BitVectorValue {
	switch __gp_m0 := any(value).(type) {
	case floatingPointValue:
		bits := __gp_m0.bits
		return bits
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep FloatingPointExponentBits(0 e nat, 0 s nat, value FloatingPointValue[e, s]) int
func FloatingPointExponentBits(value FloatingPointValue) int {
	switch __gp_m1 := any(value).(type) {
	case floatingPointValue:
		exponentBits := __gp_m1.exponentBits
		return exponentBits
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep FloatingPointSignificandBits(0 e nat, 0 s nat, value FloatingPointValue[e, s]) int
func FloatingPointSignificandBits(value FloatingPointValue) int {
	switch __gp_m2 := any(value).(type) {
	case floatingPointValue:
		significandBits := __gp_m2.significandBits
		return significandBits
	default:
		panic("goplus: impossible enum value in match")
	}
}

// FloatingPointAbs implements SMT-LIB fp.abs exactly at the IEEE encoding
// boundary: it clears only the sign bit, including for zeros, infinities, and
// NaNs.
//
//goplus:dep FloatingPointAbs(0 e nat, 0 s nat, value FloatingPointValue[e, s]) FloatingPointValue[e, s]
func FloatingPointAbs(value FloatingPointValue) FloatingPointValue {
	switch __gp_m3 := any(value).(type) {
	case floatingPointValue:
		exponentBits := __gp_m3.exponentBits
		significandBits := __gp_m3.significandBits
		bits := __gp_m3.bits

		total := exponentBits + significandBits
		sign := ConcatBitVectorValue(NewBitVectorUint64(1, 1), NewBitVectorUint64(total-1, 0))
		return floatingPointValue{exponentBits: exponentBits, significandBits: significandBits, bits: AndBitVectorValue(bits, NotBitVectorValue(sign))}
	default:
		panic("goplus: impossible enum value in match")
	}
}

// FloatingPointNeg implements SMT-LIB fp.neg exactly at the IEEE encoding
// boundary by toggling only the sign bit.
//
//goplus:dep FloatingPointNeg(0 e nat, 0 s nat, value FloatingPointValue[e, s]) FloatingPointValue[e, s]
func FloatingPointNeg(value FloatingPointValue) FloatingPointValue {
	switch __gp_m4 := any(value).(type) {
	case floatingPointValue:
		exponentBits := __gp_m4.exponentBits
		significandBits := __gp_m4.significandBits
		bits := __gp_m4.bits

		total := exponentBits + significandBits
		sign := ConcatBitVectorValue(NewBitVectorUint64(1, 1), NewBitVectorUint64(total-1, 0))
		return floatingPointValue{exponentBits: exponentBits, significandBits: significandBits, bits: XorBitVectorValue(bits, sign)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep FloatingPointIsNegative(0 e nat, 0 s nat, value FloatingPointValue[e, s]) bool
func FloatingPointIsNegative(value FloatingPointValue) bool {
	switch __gp_m5 := any(value).(type) {
	case floatingPointValue:
		exponentBits := __gp_m5.exponentBits
		significandBits := __gp_m5.significandBits
		bits := __gp_m5.bits

		return !FloatingPointIsNaN(value) && bits.Bit(exponentBits+significandBits-1)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep FloatingPointIsPositive(0 e nat, 0 s nat, value FloatingPointValue[e, s]) bool
func FloatingPointIsPositive(value FloatingPointValue) bool {
	return !FloatingPointIsNaN(value) && !FloatingPointIsNegative(value)
}

//goplus:dep FloatingPointIsNaN(0 e nat, 0 s nat, value FloatingPointValue[e, s]) bool
func FloatingPointIsNaN(value FloatingPointValue) bool {
	switch __gp_m6 := any(value).(type) {
	case floatingPointValue:
		exponentBits := __gp_m6.exponentBits
		significandBits := __gp_m6.significandBits
		bits := __gp_m6.bits

		return floatingPointExponentAll(bits, significandBits, exponentBits) &&
			floatingPointSignificandNonzero(bits, significandBits)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep FloatingPointIsInfinite(0 e nat, 0 s nat, value FloatingPointValue[e, s]) bool
func FloatingPointIsInfinite(value FloatingPointValue) bool {
	switch __gp_m7 := any(value).(type) {
	case floatingPointValue:
		exponentBits := __gp_m7.exponentBits
		significandBits := __gp_m7.significandBits
		bits := __gp_m7.bits

		return floatingPointExponentAll(bits, significandBits, exponentBits) &&
			!floatingPointSignificandNonzero(bits, significandBits)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep FloatingPointIsZero(0 e nat, 0 s nat, value FloatingPointValue[e, s]) bool
func FloatingPointIsZero(value FloatingPointValue) bool {
	switch __gp_m8 := any(value).(type) {
	case floatingPointValue:
		exponentBits := __gp_m8.exponentBits
		significandBits := __gp_m8.significandBits
		bits := __gp_m8.bits

		return floatingPointExponentNone(bits, significandBits, exponentBits) &&
			!floatingPointSignificandNonzero(bits, significandBits)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep FloatingPointIsSubnormal(0 e nat, 0 s nat, value FloatingPointValue[e, s]) bool
func FloatingPointIsSubnormal(value FloatingPointValue) bool {
	switch __gp_m9 := any(value).(type) {
	case floatingPointValue:
		exponentBits := __gp_m9.exponentBits
		significandBits := __gp_m9.significandBits
		bits := __gp_m9.bits

		return floatingPointExponentNone(bits, significandBits, exponentBits) &&
			floatingPointSignificandNonzero(bits, significandBits)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep FloatingPointIsNormal(0 e nat, 0 s nat, value FloatingPointValue[e, s]) bool
func FloatingPointIsNormal(value FloatingPointValue) bool {
	switch __gp_m10 := any(value).(type) {
	case floatingPointValue:
		exponentBits := __gp_m10.exponentBits
		significandBits := __gp_m10.significandBits
		bits := __gp_m10.bits

		return !floatingPointExponentNone(bits, significandBits, exponentBits) &&
			!floatingPointExponentAll(bits, significandBits, exponentBits)
	default:
		panic("goplus: impossible enum value in match")
	}
}

// FloatingPointEqual implements SMT-LIB fp.eq: NaNs compare false and the two
// signed zeros compare true; all other values compare by exact bit pattern.
//
//goplus:dep FloatingPointEqual(0 e nat, 0 s nat, left FloatingPointValue[e, s], right FloatingPointValue[e, s]) bool
func FloatingPointEqual(left FloatingPointValue, right FloatingPointValue) bool {
	if FloatingPointIsNaN(left) || FloatingPointIsNaN(right) {
		return false
	}
	if FloatingPointIsZero(left) && FloatingPointIsZero(right) {
		return true
	}
	return EqualBitVectorValue(FloatingPointBits(left), FloatingPointBits(right))
}

// FloatingPointLessThan implements SMT-LIB fp.lt. NaNs are unordered and the
// two signed zeros compare equal.
//
//goplus:dep FloatingPointLessThan(0 e nat, 0 s nat, left FloatingPointValue[e, s], right FloatingPointValue[e, s]) bool
func FloatingPointLessThan(left FloatingPointValue, right FloatingPointValue) bool {
	if FloatingPointIsNaN(left) || FloatingPointIsNaN(right) {
		return false
	}
	if FloatingPointIsZero(left) && FloatingPointIsZero(right) {
		return false
	}
	leftNegative := FloatingPointBits(left).Bit(FloatingPointExponentBits(left) + FloatingPointSignificandBits(left) - 1)
	rightNegative := FloatingPointBits(right).Bit(FloatingPointExponentBits(right) + FloatingPointSignificandBits(right) - 1)
	if leftNegative != rightNegative {
		return leftNegative
	}
	comparison := CompareUnsignedBitVectorValue(FloatingPointBits(left), FloatingPointBits(right))
	if leftNegative {
		return comparison > 0
	}
	return comparison < 0
}

//goplus:dep FloatingPointLessOrEqual(0 e nat, 0 s nat, left FloatingPointValue[e, s], right FloatingPointValue[e, s]) bool
func FloatingPointLessOrEqual(left FloatingPointValue, right FloatingPointValue) bool {
	return FloatingPointLessThan(left, right) || FloatingPointEqual(left, right)
}

//goplus:dep FloatingPointGreaterThan(0 e nat, 0 s nat, left FloatingPointValue[e, s], right FloatingPointValue[e, s]) bool
func FloatingPointGreaterThan(left FloatingPointValue, right FloatingPointValue) bool {
	return FloatingPointLessThan(right, left)
}

//goplus:dep FloatingPointGreaterOrEqual(0 e nat, 0 s nat, left FloatingPointValue[e, s], right FloatingPointValue[e, s]) bool
func FloatingPointGreaterOrEqual(left FloatingPointValue, right FloatingPointValue) bool {
	return FloatingPointLessOrEqual(right, left)
}

// FloatingPointMin implements one deterministic result permitted by SMT-LIB
// fp.min: a sole NaN yields the numeric operand, two NaNs select the right
// payload, and equal signed zeros select the right operand.
//
//goplus:dep FloatingPointMin(0 e nat, 0 s nat, left FloatingPointValue[e, s], right FloatingPointValue[e, s]) FloatingPointValue[e, s]
func FloatingPointMin(left FloatingPointValue, right FloatingPointValue) FloatingPointValue {
	if FloatingPointIsNaN(left) {
		return right
	}
	if FloatingPointIsNaN(right) {
		return left
	}
	if FloatingPointLessThan(left, right) {
		return left
	}
	return right
}

// FloatingPointMax is the corresponding deterministic SMT-LIB fp.max result.
// Equal signed zeros select the left operand.
//
//goplus:dep FloatingPointMax(0 e nat, 0 s nat, left FloatingPointValue[e, s], right FloatingPointValue[e, s]) FloatingPointValue[e, s]
func FloatingPointMax(left FloatingPointValue, right FloatingPointValue) FloatingPointValue {
	if FloatingPointIsNaN(left) {
		return right
	}
	if FloatingPointIsNaN(right) {
		return left
	}
	if FloatingPointLessThan(left, right) {
		return right
	}
	return left
}

func floatingPointSignificandNonzero(bits BitVectorValue, significandBits int) bool {
	for index := 0; index < significandBits-1; index++ {
		if bits.Bit(index) {
			return true
		}
	}
	return false
}

func floatingPointExponentNone(bits BitVectorValue, significandBits int, exponentBits int) bool {
	for index := 0; index < exponentBits; index++ {
		if bits.Bit(significandBits - 1 + index) {
			return false
		}
	}
	return true
}

func floatingPointExponentAll(bits BitVectorValue, significandBits int, exponentBits int) bool {
	for index := 0; index < exponentBits; index++ {
		if !bits.Bit(significandBits - 1 + index) {
			return false
		}
	}
	return true
}
