// Code generated by goplus from floating_point.gp. DO NOT EDIT.
//goplus:v v0.28.0

package smt

// FloatingPointValue[e,s] is an exact SMT-LIB floating-point bit pattern.
// The exponent width e and significand width s (including the hidden bit) are
// retained as Go+ indices. The IEEE interchange encoding therefore has e+s
// bits: one sign bit, e exponent bits, and s-1 trailing significand bits.
//
// This is the ground-value foundation for floating-point support. It does not
// imply symbolic QF_FP arithmetic or rounding-mode support.
//
//goplus:enum FloatingPointValue[e nat, s nat]
//goplus:derive off
//goplus:repr transparent
type FloatingPointValue = floatingPointValue

//goplus:variant (FloatingPointValue) floatingPointValue(ExponentBits int, SignificandBits int, Bits BitVectorValue) FloatingPointValue[e, s]
type floatingPointValue struct {
	exponentBits    int
	significandBits int
	bits            BitVectorValue
}

func (floatingPointValue) isFloatingPointValue() {}

//goplus:enum FloatingPointRoundingMode
type FloatingPointRoundingMode interface{ isFloatingPointRoundingMode() }

//goplus:variant (FloatingPointRoundingMode) floatingPointRoundNearestTiesToEven
type floatingPointRoundNearestTiesToEven struct{}

func (floatingPointRoundNearestTiesToEven) isFloatingPointRoundingMode() {}

//goplus:variant (FloatingPointRoundingMode) floatingPointRoundNearestTiesToAway
type floatingPointRoundNearestTiesToAway struct{}

func (floatingPointRoundNearestTiesToAway) isFloatingPointRoundingMode() {}

//goplus:variant (FloatingPointRoundingMode) floatingPointRoundTowardPositive
type floatingPointRoundTowardPositive struct{}

func (floatingPointRoundTowardPositive) isFloatingPointRoundingMode() {}

//goplus:variant (FloatingPointRoundingMode) floatingPointRoundTowardNegative
type floatingPointRoundTowardNegative struct{}

func (floatingPointRoundTowardNegative) isFloatingPointRoundingMode() {}

//goplus:variant (FloatingPointRoundingMode) floatingPointRoundTowardZero
type floatingPointRoundTowardZero struct{}

func (floatingPointRoundTowardZero) isFloatingPointRoundingMode() {}

// FloatingPointRoundingModeCases selects one handler per FloatingPointRoundingMode variant for FloatingPointRoundingModeFold.
type FloatingPointRoundingModeCases[R any] struct {
	floatingPointRoundNearestTiesToEven func() R
	floatingPointRoundNearestTiesToAway func() R
	floatingPointRoundTowardPositive    func() R
	floatingPointRoundTowardNegative    func() R
	floatingPointRoundTowardZero        func() R
}

// FloatingPointRoundingModeFold reduces FloatingPointRoundingMode by one-level case analysis.
func FloatingPointRoundingModeFold[R any](f FloatingPointRoundingMode, cs FloatingPointRoundingModeCases[R]) R {
	switch any(f).(type) {
	case floatingPointRoundNearestTiesToEven:
		return cs.floatingPointRoundNearestTiesToEven()
	case floatingPointRoundNearestTiesToAway:
		return cs.floatingPointRoundNearestTiesToAway()
	case floatingPointRoundTowardPositive:
		return cs.floatingPointRoundTowardPositive()
	case floatingPointRoundTowardNegative:
		return cs.floatingPointRoundTowardNegative()
	case floatingPointRoundTowardZero:
		return cs.floatingPointRoundTowardZero()
	default:
		panic("goplus: impossible enum value in FloatingPointRoundingModeFold")
	}
}

// FloatingPointRoundingModeEqOverrides carries optional per-variant hooks for FloatingPointRoundingModeEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type FloatingPointRoundingModeEqOverrides struct {
	floatingPointRoundNearestTiesToEven func(x, y floatingPointRoundNearestTiesToEven) (eq, handled bool)
	floatingPointRoundNearestTiesToAway func(x, y floatingPointRoundNearestTiesToAway) (eq, handled bool)
	floatingPointRoundTowardPositive    func(x, y floatingPointRoundTowardPositive) (eq, handled bool)
	floatingPointRoundTowardNegative    func(x, y floatingPointRoundTowardNegative) (eq, handled bool)
	floatingPointRoundTowardZero        func(x, y floatingPointRoundTowardZero) (eq, handled bool)
}

// FloatingPointRoundingModeEqualWith reports structural equality of a and b under ov.
func FloatingPointRoundingModeEqualWith(a, b FloatingPointRoundingMode, ov FloatingPointRoundingModeEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case floatingPointRoundNearestTiesToEven:
		y, ok := any(b).(floatingPointRoundNearestTiesToEven)
		if !ok {
			return false
		}
		if ov.floatingPointRoundNearestTiesToEven != nil {
			if eq, handled := ov.floatingPointRoundNearestTiesToEven(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case floatingPointRoundNearestTiesToAway:
		y, ok := any(b).(floatingPointRoundNearestTiesToAway)
		if !ok {
			return false
		}
		if ov.floatingPointRoundNearestTiesToAway != nil {
			if eq, handled := ov.floatingPointRoundNearestTiesToAway(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case floatingPointRoundTowardPositive:
		y, ok := any(b).(floatingPointRoundTowardPositive)
		if !ok {
			return false
		}
		if ov.floatingPointRoundTowardPositive != nil {
			if eq, handled := ov.floatingPointRoundTowardPositive(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case floatingPointRoundTowardNegative:
		y, ok := any(b).(floatingPointRoundTowardNegative)
		if !ok {
			return false
		}
		if ov.floatingPointRoundTowardNegative != nil {
			if eq, handled := ov.floatingPointRoundTowardNegative(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case floatingPointRoundTowardZero:
		y, ok := any(b).(floatingPointRoundTowardZero)
		if !ok {
			return false
		}
		if ov.floatingPointRoundTowardZero != nil {
			if eq, handled := ov.floatingPointRoundTowardZero(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// FloatingPointRoundingModeEqual reports structural equality of a and b.
func FloatingPointRoundingModeEqual(a, b FloatingPointRoundingMode) bool {
	return FloatingPointRoundingModeEqualWith(a, b, FloatingPointRoundingModeEqOverrides{})
}

func RoundNearestTiesToEven() FloatingPointRoundingMode { return floatingPointRoundNearestTiesToEven{} }
func RoundNearestTiesToAway() FloatingPointRoundingMode { return floatingPointRoundNearestTiesToAway{} }
func RoundTowardPositive() FloatingPointRoundingMode    { return floatingPointRoundTowardPositive{} }
func RoundTowardNegative() FloatingPointRoundingMode    { return floatingPointRoundTowardNegative{} }
func RoundTowardZero() FloatingPointRoundingMode        { return floatingPointRoundTowardZero{} }

func floatingPointRoundingModeCode(mode FloatingPointRoundingMode) uint8 {
	switch any(mode).(type) {
	case floatingPointRoundNearestTiesToEven:
		return 1
	case floatingPointRoundNearestTiesToAway:
		return 2
	case floatingPointRoundTowardPositive:
		return 3
	case floatingPointRoundTowardNegative:
		return 4
	case floatingPointRoundTowardZero:
		return 5
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep FloatingPointFromBits(exponentBits nat, significandBits nat, bits BitVectorValue) FloatingPointValue[exponentBits, significandBits]
func FloatingPointFromBits(exponentBits int, significandBits int, bits BitVectorValue) FloatingPointValue {
	if exponentBits < 2 {
		panic("smt: floating-point exponent width must be at least 2")
	}
	if significandBits < 2 {
		panic("smt: floating-point significand width must be at least 2")
	}
	if bits.Width() != int(exponentBits+significandBits) {
		panic("smt: floating-point bit-pattern width mismatch")
	}
	return floatingPointValue{exponentBits: int(exponentBits), significandBits: int(significandBits), bits: bits}
}

//goplus:dep FloatingPointFromUint64(exponentBits nat, significandBits nat, bits uint64) FloatingPointValue[exponentBits, significandBits]
func FloatingPointFromUint64(exponentBits int, significandBits int, bits uint64) FloatingPointValue {
	return FloatingPointFromBits(exponentBits, significandBits, NewBitVectorUint64(int(exponentBits+significandBits), bits))
}

// FloatingPointFromComponents implements SMT-LIB's native
// (fp sign exponent significand) constructor. The significand argument contains
// the s-1 explicitly encoded trailing bits, not the hidden leading bit.
//
//goplus:dep FloatingPointFromComponents(exponentBits nat, significandBits nat, sign BitVectorValue, exponent BitVectorValue, significand BitVectorValue) FloatingPointValue[exponentBits, significandBits]
func FloatingPointFromComponents(exponentBits int, significandBits int, sign BitVectorValue, exponent BitVectorValue, significand BitVectorValue) FloatingPointValue {
	if sign.Width() != 1 {
		panic("smt: floating-point sign width must be 1")
	}
	if exponent.Width() != int(exponentBits) {
		panic("smt: floating-point exponent component width mismatch")
	}
	if significand.Width() != int(significandBits-1) {
		panic("smt: floating-point significand component width mismatch")
	}
	return FloatingPointFromBits(exponentBits, significandBits,
		ConcatBitVectorValue(sign, ConcatBitVectorValue(exponent, significand)))
}

//goplus:dep FloatingPointPositiveZero(exponentBits nat, significandBits nat) FloatingPointValue[exponentBits, significandBits]
func FloatingPointPositiveZero(exponentBits int, significandBits int) FloatingPointValue {
	return FloatingPointFromBits(exponentBits, significandBits, NewBitVectorUint64(int(exponentBits+significandBits), 0))
}

//goplus:dep FloatingPointNegativeZero(exponentBits nat, significandBits nat) FloatingPointValue[exponentBits, significandBits]
func FloatingPointNegativeZero(exponentBits int, significandBits int) FloatingPointValue {
	return FloatingPointFromComponents(exponentBits, significandBits,
		NewBitVectorUint64(1, 1), NewBitVectorUint64(int(exponentBits), 0),
		NewBitVectorUint64(int(significandBits-1), 0))
}

//goplus:dep FloatingPointPositiveInfinity(exponentBits nat, significandBits nat) FloatingPointValue[exponentBits, significandBits]
func FloatingPointPositiveInfinity(exponentBits int, significandBits int) FloatingPointValue {
	return FloatingPointFromComponents(exponentBits, significandBits,
		NewBitVectorUint64(1, 0), NotBitVectorValue(NewBitVectorUint64(int(exponentBits), 0)),
		NewBitVectorUint64(int(significandBits-1), 0))
}

//goplus:dep FloatingPointNegativeInfinity(exponentBits nat, significandBits nat) FloatingPointValue[exponentBits, significandBits]
func FloatingPointNegativeInfinity(exponentBits int, significandBits int) FloatingPointValue {
	return FloatingPointFromComponents(exponentBits, significandBits,
		NewBitVectorUint64(1, 1), NotBitVectorValue(NewBitVectorUint64(int(exponentBits), 0)),
		NewBitVectorUint64(int(significandBits-1), 0))
}

// FloatingPointNaN returns a deterministic positive quiet NaN. SMT-LIB leaves
// the sign and payload of its indexed NaN special value unspecified.
//
//goplus:dep FloatingPointNaN(exponentBits nat, significandBits nat) FloatingPointValue[exponentBits, significandBits]
func FloatingPointNaN(exponentBits int, significandBits int) FloatingPointValue {
	payload := ConcatBitVectorValue(NewBitVectorUint64(1, 1),
		NewBitVectorUint64(int(significandBits-2), 0))
	return FloatingPointFromComponents(exponentBits, significandBits,
		NewBitVectorUint64(1, 0), NotBitVectorValue(NewBitVectorUint64(int(exponentBits), 0)), payload)
}

//goplus:dep FloatingPointBits(0 e nat, 0 s nat, value FloatingPointValue[e, s]) BitVectorValue
func FloatingPointBits(value FloatingPointValue) BitVectorValue {
	switch __gp_m1 := any(value).(type) {
	case floatingPointValue:
		bits := __gp_m1.bits
		return bits
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep FloatingPointExponentBits(0 e nat, 0 s nat, value FloatingPointValue[e, s]) int
func FloatingPointExponentBits(value FloatingPointValue) int {
	switch __gp_m2 := any(value).(type) {
	case floatingPointValue:
		exponentBits := __gp_m2.exponentBits
		return exponentBits
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep FloatingPointSignificandBits(0 e nat, 0 s nat, value FloatingPointValue[e, s]) int
func FloatingPointSignificandBits(value FloatingPointValue) int {
	switch __gp_m3 := any(value).(type) {
	case floatingPointValue:
		significandBits := __gp_m3.significandBits
		return significandBits
	default:
		panic("goplus: impossible enum value in match")
	}
}

// FloatingPointAbs implements SMT-LIB fp.abs exactly at the IEEE encoding
// boundary: it clears only the sign bit, including for zeros, infinities, and
// NaNs.
//
//goplus:dep FloatingPointAbs(0 e nat, 0 s nat, value FloatingPointValue[e, s]) FloatingPointValue[e, s]
func FloatingPointAbs(value FloatingPointValue) FloatingPointValue {
	switch __gp_m4 := any(value).(type) {
	case floatingPointValue:
		exponentBits := __gp_m4.exponentBits
		significandBits := __gp_m4.significandBits
		bits := __gp_m4.bits

		total := exponentBits + significandBits
		sign := ConcatBitVectorValue(NewBitVectorUint64(1, 1), NewBitVectorUint64(total-1, 0))
		return floatingPointValue{exponentBits: exponentBits, significandBits: significandBits, bits: AndBitVectorValue(bits, NotBitVectorValue(sign))}
	default:
		panic("goplus: impossible enum value in match")
	}
}

// FloatingPointNeg implements SMT-LIB fp.neg exactly at the IEEE encoding
// boundary by toggling only the sign bit.
//
//goplus:dep FloatingPointNeg(0 e nat, 0 s nat, value FloatingPointValue[e, s]) FloatingPointValue[e, s]
func FloatingPointNeg(value FloatingPointValue) FloatingPointValue {
	switch __gp_m5 := any(value).(type) {
	case floatingPointValue:
		exponentBits := __gp_m5.exponentBits
		significandBits := __gp_m5.significandBits
		bits := __gp_m5.bits

		total := exponentBits + significandBits
		sign := ConcatBitVectorValue(NewBitVectorUint64(1, 1), NewBitVectorUint64(total-1, 0))
		return floatingPointValue{exponentBits: exponentBits, significandBits: significandBits, bits: XorBitVectorValue(bits, sign)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep FloatingPointIsNegative(0 e nat, 0 s nat, value FloatingPointValue[e, s]) bool
func FloatingPointIsNegative(value FloatingPointValue) bool {
	switch __gp_m6 := any(value).(type) {
	case floatingPointValue:
		exponentBits := __gp_m6.exponentBits
		significandBits := __gp_m6.significandBits
		bits := __gp_m6.bits

		return !FloatingPointIsNaN(value) && bits.Bit(exponentBits+significandBits-1)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep FloatingPointIsPositive(0 e nat, 0 s nat, value FloatingPointValue[e, s]) bool
func FloatingPointIsPositive(value FloatingPointValue) bool {
	return !FloatingPointIsNaN(value) && !FloatingPointIsNegative(value)
}

//goplus:dep FloatingPointIsNaN(0 e nat, 0 s nat, value FloatingPointValue[e, s]) bool
func FloatingPointIsNaN(value FloatingPointValue) bool {
	switch __gp_m7 := any(value).(type) {
	case floatingPointValue:
		exponentBits := __gp_m7.exponentBits
		significandBits := __gp_m7.significandBits
		bits := __gp_m7.bits

		return floatingPointExponentAll(bits, significandBits, exponentBits) &&
			floatingPointSignificandNonzero(bits, significandBits)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep FloatingPointIsInfinite(0 e nat, 0 s nat, value FloatingPointValue[e, s]) bool
func FloatingPointIsInfinite(value FloatingPointValue) bool {
	switch __gp_m8 := any(value).(type) {
	case floatingPointValue:
		exponentBits := __gp_m8.exponentBits
		significandBits := __gp_m8.significandBits
		bits := __gp_m8.bits

		return floatingPointExponentAll(bits, significandBits, exponentBits) &&
			!floatingPointSignificandNonzero(bits, significandBits)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep FloatingPointIsZero(0 e nat, 0 s nat, value FloatingPointValue[e, s]) bool
func FloatingPointIsZero(value FloatingPointValue) bool {
	switch __gp_m9 := any(value).(type) {
	case floatingPointValue:
		exponentBits := __gp_m9.exponentBits
		significandBits := __gp_m9.significandBits
		bits := __gp_m9.bits

		return floatingPointExponentNone(bits, significandBits, exponentBits) &&
			!floatingPointSignificandNonzero(bits, significandBits)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep FloatingPointIsSubnormal(0 e nat, 0 s nat, value FloatingPointValue[e, s]) bool
func FloatingPointIsSubnormal(value FloatingPointValue) bool {
	switch __gp_m10 := any(value).(type) {
	case floatingPointValue:
		exponentBits := __gp_m10.exponentBits
		significandBits := __gp_m10.significandBits
		bits := __gp_m10.bits

		return floatingPointExponentNone(bits, significandBits, exponentBits) &&
			floatingPointSignificandNonzero(bits, significandBits)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep FloatingPointIsNormal(0 e nat, 0 s nat, value FloatingPointValue[e, s]) bool
func FloatingPointIsNormal(value FloatingPointValue) bool {
	switch __gp_m11 := any(value).(type) {
	case floatingPointValue:
		exponentBits := __gp_m11.exponentBits
		significandBits := __gp_m11.significandBits
		bits := __gp_m11.bits

		return !floatingPointExponentNone(bits, significandBits, exponentBits) &&
			!floatingPointExponentAll(bits, significandBits, exponentBits)
	default:
		panic("goplus: impossible enum value in match")
	}
}

// FloatingPointEqual implements SMT-LIB fp.eq: NaNs compare false and the two
// signed zeros compare true; all other values compare by exact bit pattern.
//
//goplus:dep FloatingPointEqual(0 e nat, 0 s nat, left FloatingPointValue[e, s], right FloatingPointValue[e, s]) bool
func FloatingPointEqual(left FloatingPointValue, right FloatingPointValue) bool {
	if FloatingPointIsNaN(left) || FloatingPointIsNaN(right) {
		return false
	}
	if FloatingPointIsZero(left) && FloatingPointIsZero(right) {
		return true
	}
	return EqualBitVectorValue(FloatingPointBits(left), FloatingPointBits(right))
}

// FloatingPointLessThan implements SMT-LIB fp.lt. NaNs are unordered and the
// two signed zeros compare equal.
//
//goplus:dep FloatingPointLessThan(0 e nat, 0 s nat, left FloatingPointValue[e, s], right FloatingPointValue[e, s]) bool
func FloatingPointLessThan(left FloatingPointValue, right FloatingPointValue) bool {
	if FloatingPointIsNaN(left) || FloatingPointIsNaN(right) {
		return false
	}
	if FloatingPointIsZero(left) && FloatingPointIsZero(right) {
		return false
	}
	leftNegative := FloatingPointBits(left).Bit(FloatingPointExponentBits(left) + FloatingPointSignificandBits(left) - 1)
	rightNegative := FloatingPointBits(right).Bit(FloatingPointExponentBits(right) + FloatingPointSignificandBits(right) - 1)
	if leftNegative != rightNegative {
		return leftNegative
	}
	comparison := CompareUnsignedBitVectorValue(FloatingPointBits(left), FloatingPointBits(right))
	if leftNegative {
		return comparison > 0
	}
	return comparison < 0
}

//goplus:dep FloatingPointLessOrEqual(0 e nat, 0 s nat, left FloatingPointValue[e, s], right FloatingPointValue[e, s]) bool
func FloatingPointLessOrEqual(left FloatingPointValue, right FloatingPointValue) bool {
	return FloatingPointLessThan(left, right) || FloatingPointEqual(left, right)
}

//goplus:dep FloatingPointGreaterThan(0 e nat, 0 s nat, left FloatingPointValue[e, s], right FloatingPointValue[e, s]) bool
func FloatingPointGreaterThan(left FloatingPointValue, right FloatingPointValue) bool {
	return FloatingPointLessThan(right, left)
}

//goplus:dep FloatingPointGreaterOrEqual(0 e nat, 0 s nat, left FloatingPointValue[e, s], right FloatingPointValue[e, s]) bool
func FloatingPointGreaterOrEqual(left FloatingPointValue, right FloatingPointValue) bool {
	return FloatingPointLessOrEqual(right, left)
}

// FloatingPointMin implements one deterministic result permitted by SMT-LIB
// fp.min: a sole NaN yields the numeric operand, two NaNs select the right
// payload, and equal signed zeros select the right operand.
//
//goplus:dep FloatingPointMin(0 e nat, 0 s nat, left FloatingPointValue[e, s], right FloatingPointValue[e, s]) FloatingPointValue[e, s]
func FloatingPointMin(left FloatingPointValue, right FloatingPointValue) FloatingPointValue {
	if FloatingPointIsNaN(left) {
		return right
	}
	if FloatingPointIsNaN(right) {
		return left
	}
	if FloatingPointLessThan(left, right) {
		return left
	}
	return right
}

// FloatingPointMax is the corresponding deterministic SMT-LIB fp.max result.
// Equal signed zeros select the left operand.
//
//goplus:dep FloatingPointMax(0 e nat, 0 s nat, left FloatingPointValue[e, s], right FloatingPointValue[e, s]) FloatingPointValue[e, s]
func FloatingPointMax(left FloatingPointValue, right FloatingPointValue) FloatingPointValue {
	if FloatingPointIsNaN(left) {
		return right
	}
	if FloatingPointIsNaN(right) {
		return left
	}
	if FloatingPointLessThan(left, right) {
		return right
	}
	return left
}

//goplus:dep FloatingPointRoundToIntegral(0 e nat, 0 s nat, mode FloatingPointRoundingMode, value FloatingPointValue[e, s]) FloatingPointValue[e, s]
func FloatingPointRoundToIntegral(mode FloatingPointRoundingMode, value FloatingPointValue) FloatingPointValue {
	return floatingPointRoundToIntegral(floatingPointRoundingModeCode(mode), value)
}

func floatingPointSignificandNonzero(bits BitVectorValue, significandBits int) bool {
	for index := 0; index < significandBits-1; index++ {
		if bits.Bit(index) {
			return true
		}
	}
	return false
}

func floatingPointExponentNone(bits BitVectorValue, significandBits int, exponentBits int) bool {
	for index := 0; index < exponentBits; index++ {
		if bits.Bit(significandBits - 1 + index) {
			return false
		}
	}
	return true
}

func floatingPointExponentAll(bits BitVectorValue, significandBits int, exponentBits int) bool {
	for index := 0; index < exponentBits; index++ {
		if !bits.Bit(significandBits - 1 + index) {
			return false
		}
	}
	return true
}
