// Code generated by goplus from smt.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package smt provides the essential sorted-term and incremental-solver core
// shared by native Go+ theorem provers. It is intentionally independent of
// any one solver's compatibility API.
package smt

type BoolSort struct{}
type IntSort struct{}
type RealSort struct{}

//goplus:enum ArraySort[I any, E any]
//goplus:derive off
type ArraySort[I any, E any] interface{ isArraySort(I, E) }

//goplus:variant (ArraySort[I, E]) arraySort() ArraySort[I, E]
type arraySort[I any, E any] struct{}

func (arraySort[I, E]) isArraySort(I, E) {}

//goplus:enum BitVecSort[w nat]
//goplus:derive off
type BitVecSort interface{ isBitVecSort() }

//goplus:variant (BitVecSort) bitVecSort() BitVecSort[w]
type bitVecSort struct{}

func (bitVecSort) isBitVecSort() {}

//goplus:enum UninterpretedSort[s nat]
//goplus:derive off
type UninterpretedSort interface{ isUninterpretedSort() }

//goplus:variant (UninterpretedSort) uninterpretedSort() UninterpretedSort[s]
type uninterpretedSort struct{}

func (uninterpretedSort) isUninterpretedSort() {}

// UnaryFunction[d,r] retains its uninterpreted domain and range sorts. Go+
// rejects applying it to a term from another domain before Go generation.
//
//goplus:enum UnaryFunction[d nat, r nat]
//goplus:derive off
type UnaryFunction interface{ isUnaryFunction() }

//goplus:variant (UnaryFunction) unaryFunctionValue(DomainID int, RangeID int, ID int, Name string) UnaryFunction[d, r]
type unaryFunctionValue struct {
	domainID int
	rangeID  int
	iD       int
	name     string
}

func (unaryFunctionValue) isUnaryFunction() {}

// BinaryFunction[a,b,r] retains both argument sorts and its result sort.
// Go+ rejects swapped or otherwise ill-sorted applications before generation.
//
//goplus:enum BinaryFunction[a nat, b nat, r nat]
//goplus:derive off
type BinaryFunction interface{ isBinaryFunction() }

//goplus:variant (BinaryFunction) binaryFunctionValue(FirstID int, SecondID int, RangeID int, ID int, Name string) BinaryFunction[a, b, r]
type binaryFunctionValue struct {
	firstID  int
	secondID int
	rangeID  int
	iD       int
	name     string
}

func (binaryFunctionValue) isBinaryFunction() {}

// SortedUnaryFunction[D,R] extends typed EUF to built-in sorts. The type
// indices prevent applying a Real function to an Int or uninterpreted term.
//
//goplus:enum SortedUnaryFunction[D any, R any]
//goplus:derive off
type SortedUnaryFunction[D any, R any] interface{ isSortedUnaryFunction(D, R) }

//goplus:variant (SortedUnaryFunction[D, R]) sortedUnaryFunctionValue(DomainKind int, RangeKind int, ID int, Name string) SortedUnaryFunction[D, R]
type sortedUnaryFunctionValue[D any, R any] struct {
	domainKind int
	rangeKind  int
	iD         int
	name       string
}

func (sortedUnaryFunctionValue[D, R]) isSortedUnaryFunction(D, R) {}

// SortedBinaryFunction[A,B,R] extends typed binary EUF to built-in sorts.
// All three sort indices are checked before Go generation.
//
//goplus:enum SortedBinaryFunction[A any, B any, R any]
//goplus:derive off
type SortedBinaryFunction[A any, B any, R any] interface{ isSortedBinaryFunction(A, B, R) }

//goplus:variant (SortedBinaryFunction[A, B, R]) sortedBinaryFunctionValue(FirstKind int, SecondKind int, RangeKind int, ID int, Name string) SortedBinaryFunction[A, B, R]
type sortedBinaryFunctionValue[A any, B any, R any] struct {
	firstKind  int
	secondKind int
	rangeKind  int
	iD         int
	name       string
}

func (sortedBinaryFunctionValue[A, B, R]) isSortedBinaryFunction(A, B, R) {}

// Term[S] makes ill-sorted formulas unrepresentable in Go+.
//
//goplus:enum Term[S any]
type Term[S any] interface{ isTerm(S) }

//goplus:variant (Term[S]) Bool(Value bool) Term[BoolSort]
type Bool struct {
	Value bool
}

func (Bool) isTerm(BoolSort) {}

//goplus:variant (Term[S]) BoolSymbol(ID int, Name string) Term[BoolSort]
type BoolSymbol struct {
	ID   int
	Name string
}

func (BoolSymbol) isTerm(BoolSort) {}

//goplus:variant (Term[S]) BooleanVariable(ID int) Term[BoolSort]
type BooleanVariable struct {
	ID int
}

func (BooleanVariable) isTerm(BoolSort) {}

//goplus:variant (Term[S]) NegatedBooleanVariable(ID int) Term[BoolSort]
type NegatedBooleanVariable struct {
	ID int
}

func (NegatedBooleanVariable) isTerm(BoolSort) {}

//goplus:variant (Term[S]) BooleanClause(Literals []int) Term[BoolSort]
type BooleanClause struct {
	Literals []int
}

func (BooleanClause) isTerm(BoolSort) {}

//goplus:variant (Term[S]) BooleanCNF(Literals []int, ClauseEnds []int) Term[BoolSort]
type BooleanCNF struct {
	Literals   []int
	ClauseEnds []int
}

func (BooleanCNF) isTerm(BoolSort) {}

//goplus:variant (Term[S]) Not(Value Term[BoolSort]) Term[BoolSort]
type Not struct {
	Value Term[BoolSort]
}

func (Not) isTerm(BoolSort) {}

//goplus:variant (Term[S]) And(Values []Term[BoolSort]) Term[BoolSort]
type And struct {
	Values []Term[BoolSort]
}

func (And) isTerm(BoolSort) {}

//goplus:variant (Term[S]) Or(Values []Term[BoolSort]) Term[BoolSort]
type Or struct {
	Values []Term[BoolSort]
}

func (Or) isTerm(BoolSort) {}

//goplus:variant (Term[S]) Implies(Left Term[BoolSort], Right Term[BoolSort]) Term[BoolSort]
type Implies struct {
	Left  Term[BoolSort]
	Right Term[BoolSort]
}

func (Implies) isTerm(BoolSort) {}

//goplus:variant (Term[S]) Iff(Left Term[BoolSort], Right Term[BoolSort]) Term[BoolSort]
type Iff struct {
	Left  Term[BoolSort]
	Right Term[BoolSort]
}

func (Iff) isTerm(BoolSort) {}

//goplus:variant (Term[S]) If(Condition Term[BoolSort], Then Term[S], Else Term[S]) Term[S]
type If[S any] struct {
	Condition Term[BoolSort]
	Then      Term[S]
	Else      Term[S]
}

func (If[S]) isTerm(S) {}

//goplus:variant (Term[S]) Equal[X any](Left Term[X], Right Term[X]) Term[BoolSort]
type Equal struct {
	Left  any
	Right any
}

func (Equal) isTerm(BoolSort) {}

//goplus:variant (Term[S]) Integer(Value int64) Term[IntSort]
type Integer struct {
	Value int64
}

func (Integer) isTerm(IntSort) {}

//goplus:variant (Term[S]) integerExact(Value IntegerValue) Term[S]
type integerExact[S any] struct {
	value IntegerValue
}

func (integerExact[S]) isTerm(S) {}

//goplus:variant (Term[S]) IntSymbol(ID int, Name string) Term[IntSort]
type IntSymbol struct {
	ID   int
	Name string
}

func (IntSymbol) isTerm(IntSort) {}

//goplus:variant (Term[S]) integerVariable(ID int) Term[S]
type integerVariable[S any] struct {
	iD int
}

func (integerVariable[S]) isTerm(S) {}

//goplus:variant (Term[S]) Add(Values []Term[IntSort]) Term[IntSort]
type Add struct {
	Values []Term[IntSort]
}

func (Add) isTerm(IntSort) {}

//goplus:variant (Term[S]) Subtract(Left Term[IntSort], Right Term[IntSort]) Term[IntSort]
type Subtract struct {
	Left  Term[IntSort]
	Right Term[IntSort]
}

func (Subtract) isTerm(IntSort) {}

//goplus:variant (Term[S]) IntegerScale(Coefficient IntegerValue, Value Term[IntSort]) Term[IntSort]
type IntegerScale struct {
	Coefficient IntegerValue
	Value       Term[IntSort]
}

func (IntegerScale) isTerm(IntSort) {}

//goplus:variant (Term[S]) IntegerDiv(Dividend Term[IntSort], Divisor IntegerValue) Term[IntSort]
type IntegerDiv struct {
	Dividend Term[IntSort]
	Divisor  IntegerValue
}

func (IntegerDiv) isTerm(IntSort) {}

//goplus:variant (Term[S]) IntegerMod(Dividend Term[IntSort], Divisor IntegerValue) Term[IntSort]
type IntegerMod struct {
	Dividend Term[IntSort]
	Divisor  IntegerValue
}

func (IntegerMod) isTerm(IntSort) {}

//goplus:variant (Term[S]) LessEqual(Left Term[IntSort], Right Term[IntSort]) Term[BoolSort]
type LessEqual struct {
	Left  Term[IntSort]
	Right Term[IntSort]
}

func (LessEqual) isTerm(BoolSort) {}

//goplus:variant (Term[S]) Less(Left Term[IntSort], Right Term[IntSort]) Term[BoolSort]
type Less struct {
	Left  Term[IntSort]
	Right Term[IntSort]
}

func (Less) isTerm(BoolSort) {}

//goplus:variant (Term[S]) Real(Value Rational) Term[RealSort]
type Real struct {
	Value Rational
}

func (Real) isTerm(RealSort) {}

//goplus:variant (Term[S]) RealSymbol(ID int, Name string) Term[RealSort]
type RealSymbol struct {
	ID   int
	Name string
}

func (RealSymbol) isTerm(RealSort) {}

//goplus:variant (Term[S]) RealAdd(Values []Term[RealSort]) Term[RealSort]
type RealAdd struct {
	Values []Term[RealSort]
}

func (RealAdd) isTerm(RealSort) {}

//goplus:variant (Term[S]) RealSubtract(Left Term[RealSort], Right Term[RealSort]) Term[RealSort]
type RealSubtract struct {
	Left  Term[RealSort]
	Right Term[RealSort]
}

func (RealSubtract) isTerm(RealSort) {}

//goplus:variant (Term[S]) RealScale(Coefficient Rational, Value Term[RealSort]) Term[RealSort]
type RealScale struct {
	Coefficient Rational
	Value       Term[RealSort]
}

func (RealScale) isTerm(RealSort) {}

//goplus:variant (Term[S]) RealLessEqual(Left Term[RealSort], Right Term[RealSort]) Term[BoolSort]
type RealLessEqual struct {
	Left  Term[RealSort]
	Right Term[RealSort]
}

func (RealLessEqual) isTerm(BoolSort) {}

//goplus:variant (Term[S]) RealLess(Left Term[RealSort], Right Term[RealSort]) Term[BoolSort]
type RealLess struct {
	Left  Term[RealSort]
	Right Term[RealSort]
}

func (RealLess) isTerm(BoolSort) {}

//goplus:variant (Term[S]) uninterpretedValue(SortID int, ID int, Name string) Term[S]
type uninterpretedValue[S any] struct {
	sortID int
	iD     int
	name   string
}

func (uninterpretedValue[S]) isTerm(S) {}

//goplus:variant (Term[S]) unaryApplication(Function any, Argument any) Term[S]
type unaryApplication[S any] struct {
	function any
	argument any
}

func (unaryApplication[S]) isTerm(S) {}

//goplus:variant (Term[S]) binaryApplication(Function any, First any, Second any) Term[S]
type binaryApplication[S any] struct {
	function any
	first    any
	second   any
}

func (binaryApplication[S]) isTerm(S) {}

//goplus:variant (Term[S]) sortedUnaryApplication(Function any, Argument any, RangeKind int) Term[S]
type sortedUnaryApplication[S any] struct {
	function  any
	argument  any
	rangeKind int
}

func (sortedUnaryApplication[S]) isTerm(S) {}

//goplus:variant (Term[S]) sortedBinaryApplication(Function any, First any, Second any, RangeKind int) Term[S]
type sortedBinaryApplication[S any] struct {
	function  any
	first     any
	second    any
	rangeKind int
}

func (sortedBinaryApplication[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVector(Value BitVectorValue) Term[S]
type bitVector[S any] struct {
	value BitVectorValue
}

func (bitVector[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorSymbol(Width int, ID int, Name string) Term[S]
type bitVectorSymbol[S any] struct {
	width int
	iD    int
	name  string
}

func (bitVectorSymbol[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorNot(Value any) Term[S]
type bitVectorNot[S any] struct {
	value any
}

func (bitVectorNot[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorAnd(Left any, Right any) Term[S]
type bitVectorAnd[S any] struct {
	left  any
	right any
}

func (bitVectorAnd[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorOr(Left any, Right any) Term[S]
type bitVectorOr[S any] struct {
	left  any
	right any
}

func (bitVectorOr[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorXor(Left any, Right any) Term[S]
type bitVectorXor[S any] struct {
	left  any
	right any
}

func (bitVectorXor[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorAdd(Left any, Right any) Term[S]
type bitVectorAdd[S any] struct {
	left  any
	right any
}

func (bitVectorAdd[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorSub(Left any, Right any) Term[S]
type bitVectorSub[S any] struct {
	left  any
	right any
}

func (bitVectorSub[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorMul(Left any, Right any) Term[S]
type bitVectorMul[S any] struct {
	left  any
	right any
}

func (bitVectorMul[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorShiftLeft(Value any, Amount any) Term[S]
type bitVectorShiftLeft[S any] struct {
	value  any
	amount any
}

func (bitVectorShiftLeft[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorLogicalShiftRight(Value any, Amount any) Term[S]
type bitVectorLogicalShiftRight[S any] struct {
	value  any
	amount any
}

func (bitVectorLogicalShiftRight[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorArithmeticShiftRight(Value any, Amount any) Term[S]
type bitVectorArithmeticShiftRight[S any] struct {
	value  any
	amount any
}

func (bitVectorArithmeticShiftRight[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorUnsignedDiv(Left any, Right any) Term[S]
type bitVectorUnsignedDiv[S any] struct {
	left  any
	right any
}

func (bitVectorUnsignedDiv[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorUnsignedRem(Left any, Right any) Term[S]
type bitVectorUnsignedRem[S any] struct {
	left  any
	right any
}

func (bitVectorUnsignedRem[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorSignedDiv(Left any, Right any) Term[S]
type bitVectorSignedDiv[S any] struct {
	left  any
	right any
}

func (bitVectorSignedDiv[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorSignedRem(Left any, Right any) Term[S]
type bitVectorSignedRem[S any] struct {
	left  any
	right any
}

func (bitVectorSignedRem[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorConcat(First any, Second any, FirstWidth int, SecondWidth int) Term[S]
type bitVectorConcat[S any] struct {
	first       any
	second      any
	firstWidth  int
	secondWidth int
}

func (bitVectorConcat[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorExtract(Value any, High int, Low int) Term[S]
type bitVectorExtract[S any] struct {
	value any
	high  int
	low   int
}

func (bitVectorExtract[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorZeroExtend(Value any, Additional int) Term[S]
type bitVectorZeroExtend[S any] struct {
	value      any
	additional int
}

func (bitVectorZeroExtend[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorSignExtend(Value any, Additional int) Term[S]
type bitVectorSignExtend[S any] struct {
	value      any
	additional int
}

func (bitVectorSignExtend[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorRotateLeft(Value any, Amount int) Term[S]
type bitVectorRotateLeft[S any] struct {
	value  any
	amount int
}

func (bitVectorRotateLeft[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorRotateRight(Value any, Amount int) Term[S]
type bitVectorRotateRight[S any] struct {
	value  any
	amount int
}

func (bitVectorRotateRight[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorRepeat(Value any, Count int) Term[S]
type bitVectorRepeat[S any] struct {
	value any
	count int
}

func (bitVectorRepeat[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorUnsignedLess(Left any, Right any, OrEqual bool) Term[S]
type bitVectorUnsignedLess[S any] struct {
	left    any
	right   any
	orEqual bool
}

func (bitVectorUnsignedLess[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorSignedLess(Left any, Right any, OrEqual bool) Term[S]
type bitVectorSignedLess[S any] struct {
	left    any
	right   any
	orEqual bool
}

func (bitVectorSignedLess[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorUnsignedAddOverflow(Left any, Right any) Term[S]
type bitVectorUnsignedAddOverflow[S any] struct {
	left  any
	right any
}

func (bitVectorUnsignedAddOverflow[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorSignedAddOverflow(Left any, Right any) Term[S]
type bitVectorSignedAddOverflow[S any] struct {
	left  any
	right any
}

func (bitVectorSignedAddOverflow[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorUnsignedSubOverflow(Left any, Right any) Term[S]
type bitVectorUnsignedSubOverflow[S any] struct {
	left  any
	right any
}

func (bitVectorUnsignedSubOverflow[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorSignedSubOverflow(Left any, Right any) Term[S]
type bitVectorSignedSubOverflow[S any] struct {
	left  any
	right any
}

func (bitVectorSignedSubOverflow[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorUnsignedMulOverflow(Left any, Right any) Term[S]
type bitVectorUnsignedMulOverflow[S any] struct {
	left  any
	right any
}

func (bitVectorUnsignedMulOverflow[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorSignedMulOverflow(Left any, Right any) Term[S]
type bitVectorSignedMulOverflow[S any] struct {
	left  any
	right any
}

func (bitVectorSignedMulOverflow[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorSignedDivOverflow(Left any, Right any) Term[S]
type bitVectorSignedDivOverflow[S any] struct {
	left  any
	right any
}

func (bitVectorSignedDivOverflow[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorNegOverflow(Value any) Term[S]
type bitVectorNegOverflow[S any] struct {
	value any
}

func (bitVectorNegOverflow[S]) isTerm(S) {}

//goplus:variant (Term[S]) bitVectorToInteger(Value any, Signed bool) Term[S]
type bitVectorToInteger[S any] struct {
	value  any
	signed bool
}

func (bitVectorToInteger[S]) isTerm(S) {}

//goplus:variant (Term[S]) integerToBitVector(Value any, Width int) Term[S]
type integerToBitVector[S any] struct {
	value any
	width int
}

func (integerToBitVector[S]) isTerm(S) {}

//goplus:variant (Term[S]) arraySymbol(ID int, Name string) Term[S]
type arraySymbol[S any] struct {
	iD   int
	name string
}

func (arraySymbol[S]) isTerm(S) {}

//goplus:variant (Term[S]) constantArray(DefaultValue any) Term[S]
type constantArray[S any] struct {
	defaultValue any
}

func (constantArray[S]) isTerm(S) {}

//goplus:variant (Term[S]) arraySelect(Array any, Index any) Term[S]
type arraySelect[S any] struct {
	array any
	index any
}

func (arraySelect[S]) isTerm(S) {}

//goplus:variant (Term[S]) arrayStore(Array any, Index any, Value any) Term[S]
type arrayStore[S any] struct {
	array any
	index any
	value any
}

func (arrayStore[S]) isTerm(S) {}

//goplus:variant (Term[S]) arrayReadInteger(ArrayID int, Index IntegerValue) Term[S]
type arrayReadInteger[S any] struct {
	arrayID int
	index   IntegerValue
}

func (arrayReadInteger[S]) isTerm(S) {}

//goplus:variant (Term[S]) arrayStoreReadInteger(ArrayID int, StoreIndexID int, ReadIndexID int, Value IntegerValue) Term[S]
type arrayStoreReadInteger[S any] struct {
	arrayID      int
	storeIndexID int
	readIndexID  int
	value        IntegerValue
}

func (arrayStoreReadInteger[S]) isTerm(S) {}

// TermCases selects one handler per Term variant for TermFold.
type TermCases[S any, R any] struct {
	Bool                          func(Value bool) R
	BoolSymbol                    func(ID int, Name string) R
	BooleanVariable               func(ID int) R
	NegatedBooleanVariable        func(ID int) R
	BooleanClause                 func(Literals []int) R
	BooleanCNF                    func(Literals []int, ClauseEnds []int) R
	Not                           func(Value Term[BoolSort]) R
	And                           func(Values []Term[BoolSort]) R
	Or                            func(Values []Term[BoolSort]) R
	Implies                       func(Left Term[BoolSort], Right Term[BoolSort]) R
	Iff                           func(Left Term[BoolSort], Right Term[BoolSort]) R
	If                            func(Condition Term[BoolSort], Then Term[S], Else Term[S]) R
	Equal                         func(Left any, Right any) R
	Integer                       func(Value int64) R
	integerExact                  func(Value IntegerValue) R
	IntSymbol                     func(ID int, Name string) R
	integerVariable               func(ID int) R
	Add                           func(Values []Term[IntSort]) R
	Subtract                      func(Left Term[IntSort], Right Term[IntSort]) R
	IntegerScale                  func(Coefficient IntegerValue, Value Term[IntSort]) R
	IntegerDiv                    func(Dividend Term[IntSort], Divisor IntegerValue) R
	IntegerMod                    func(Dividend Term[IntSort], Divisor IntegerValue) R
	LessEqual                     func(Left Term[IntSort], Right Term[IntSort]) R
	Less                          func(Left Term[IntSort], Right Term[IntSort]) R
	Real                          func(Value Rational) R
	RealSymbol                    func(ID int, Name string) R
	RealAdd                       func(Values []Term[RealSort]) R
	RealSubtract                  func(Left Term[RealSort], Right Term[RealSort]) R
	RealScale                     func(Coefficient Rational, Value Term[RealSort]) R
	RealLessEqual                 func(Left Term[RealSort], Right Term[RealSort]) R
	RealLess                      func(Left Term[RealSort], Right Term[RealSort]) R
	uninterpretedValue            func(SortID int, ID int, Name string) R
	unaryApplication              func(Function any, Argument any) R
	binaryApplication             func(Function any, First any, Second any) R
	sortedUnaryApplication        func(Function any, Argument any, RangeKind int) R
	sortedBinaryApplication       func(Function any, First any, Second any, RangeKind int) R
	bitVector                     func(Value BitVectorValue) R
	bitVectorSymbol               func(Width int, ID int, Name string) R
	bitVectorNot                  func(Value any) R
	bitVectorAnd                  func(Left any, Right any) R
	bitVectorOr                   func(Left any, Right any) R
	bitVectorXor                  func(Left any, Right any) R
	bitVectorAdd                  func(Left any, Right any) R
	bitVectorSub                  func(Left any, Right any) R
	bitVectorMul                  func(Left any, Right any) R
	bitVectorShiftLeft            func(Value any, Amount any) R
	bitVectorLogicalShiftRight    func(Value any, Amount any) R
	bitVectorArithmeticShiftRight func(Value any, Amount any) R
	bitVectorUnsignedDiv          func(Left any, Right any) R
	bitVectorUnsignedRem          func(Left any, Right any) R
	bitVectorSignedDiv            func(Left any, Right any) R
	bitVectorSignedRem            func(Left any, Right any) R
	bitVectorConcat               func(First any, Second any, FirstWidth int, SecondWidth int) R
	bitVectorExtract              func(Value any, High int, Low int) R
	bitVectorZeroExtend           func(Value any, Additional int) R
	bitVectorSignExtend           func(Value any, Additional int) R
	bitVectorRotateLeft           func(Value any, Amount int) R
	bitVectorRotateRight          func(Value any, Amount int) R
	bitVectorRepeat               func(Value any, Count int) R
	bitVectorUnsignedLess         func(Left any, Right any, OrEqual bool) R
	bitVectorSignedLess           func(Left any, Right any, OrEqual bool) R
	bitVectorUnsignedAddOverflow  func(Left any, Right any) R
	bitVectorSignedAddOverflow    func(Left any, Right any) R
	bitVectorUnsignedSubOverflow  func(Left any, Right any) R
	bitVectorSignedSubOverflow    func(Left any, Right any) R
	bitVectorUnsignedMulOverflow  func(Left any, Right any) R
	bitVectorSignedMulOverflow    func(Left any, Right any) R
	bitVectorSignedDivOverflow    func(Left any, Right any) R
	bitVectorNegOverflow          func(Value any) R
	bitVectorToInteger            func(Value any, Signed bool) R
	integerToBitVector            func(Value any, Width int) R
	arraySymbol                   func(ID int, Name string) R
	constantArray                 func(DefaultValue any) R
	arraySelect                   func(Array any, Index any) R
	arrayStore                    func(Array any, Index any, Value any) R
	arrayReadInteger              func(ArrayID int, Index IntegerValue) R
	arrayStoreReadInteger         func(ArrayID int, StoreIndexID int, ReadIndexID int, Value IntegerValue) R
}

// TermFold reduces Term[S] by one-level case analysis.
func TermFold[S any, R any](t Term[S], cs TermCases[S, R]) R {
	switch m := any(t).(type) {
	case Bool:
		return cs.Bool(m.Value)
	case BoolSymbol:
		return cs.BoolSymbol(m.ID, m.Name)
	case BooleanVariable:
		return cs.BooleanVariable(m.ID)
	case NegatedBooleanVariable:
		return cs.NegatedBooleanVariable(m.ID)
	case BooleanClause:
		return cs.BooleanClause(m.Literals)
	case BooleanCNF:
		return cs.BooleanCNF(m.Literals, m.ClauseEnds)
	case Not:
		return cs.Not(m.Value)
	case And:
		return cs.And(m.Values)
	case Or:
		return cs.Or(m.Values)
	case Implies:
		return cs.Implies(m.Left, m.Right)
	case Iff:
		return cs.Iff(m.Left, m.Right)
	case If[S]:
		return cs.If(m.Condition, m.Then, m.Else)
	case Equal:
		return cs.Equal(m.Left, m.Right)
	case Integer:
		return cs.Integer(m.Value)
	case integerExact[S]:
		return cs.integerExact(m.value)
	case IntSymbol:
		return cs.IntSymbol(m.ID, m.Name)
	case integerVariable[S]:
		return cs.integerVariable(m.iD)
	case Add:
		return cs.Add(m.Values)
	case Subtract:
		return cs.Subtract(m.Left, m.Right)
	case IntegerScale:
		return cs.IntegerScale(m.Coefficient, m.Value)
	case IntegerDiv:
		return cs.IntegerDiv(m.Dividend, m.Divisor)
	case IntegerMod:
		return cs.IntegerMod(m.Dividend, m.Divisor)
	case LessEqual:
		return cs.LessEqual(m.Left, m.Right)
	case Less:
		return cs.Less(m.Left, m.Right)
	case Real:
		return cs.Real(m.Value)
	case RealSymbol:
		return cs.RealSymbol(m.ID, m.Name)
	case RealAdd:
		return cs.RealAdd(m.Values)
	case RealSubtract:
		return cs.RealSubtract(m.Left, m.Right)
	case RealScale:
		return cs.RealScale(m.Coefficient, m.Value)
	case RealLessEqual:
		return cs.RealLessEqual(m.Left, m.Right)
	case RealLess:
		return cs.RealLess(m.Left, m.Right)
	case uninterpretedValue[S]:
		return cs.uninterpretedValue(m.sortID, m.iD, m.name)
	case unaryApplication[S]:
		return cs.unaryApplication(m.function, m.argument)
	case binaryApplication[S]:
		return cs.binaryApplication(m.function, m.first, m.second)
	case sortedUnaryApplication[S]:
		return cs.sortedUnaryApplication(m.function, m.argument, m.rangeKind)
	case sortedBinaryApplication[S]:
		return cs.sortedBinaryApplication(m.function, m.first, m.second, m.rangeKind)
	case bitVector[S]:
		return cs.bitVector(m.value)
	case bitVectorSymbol[S]:
		return cs.bitVectorSymbol(m.width, m.iD, m.name)
	case bitVectorNot[S]:
		return cs.bitVectorNot(m.value)
	case bitVectorAnd[S]:
		return cs.bitVectorAnd(m.left, m.right)
	case bitVectorOr[S]:
		return cs.bitVectorOr(m.left, m.right)
	case bitVectorXor[S]:
		return cs.bitVectorXor(m.left, m.right)
	case bitVectorAdd[S]:
		return cs.bitVectorAdd(m.left, m.right)
	case bitVectorSub[S]:
		return cs.bitVectorSub(m.left, m.right)
	case bitVectorMul[S]:
		return cs.bitVectorMul(m.left, m.right)
	case bitVectorShiftLeft[S]:
		return cs.bitVectorShiftLeft(m.value, m.amount)
	case bitVectorLogicalShiftRight[S]:
		return cs.bitVectorLogicalShiftRight(m.value, m.amount)
	case bitVectorArithmeticShiftRight[S]:
		return cs.bitVectorArithmeticShiftRight(m.value, m.amount)
	case bitVectorUnsignedDiv[S]:
		return cs.bitVectorUnsignedDiv(m.left, m.right)
	case bitVectorUnsignedRem[S]:
		return cs.bitVectorUnsignedRem(m.left, m.right)
	case bitVectorSignedDiv[S]:
		return cs.bitVectorSignedDiv(m.left, m.right)
	case bitVectorSignedRem[S]:
		return cs.bitVectorSignedRem(m.left, m.right)
	case bitVectorConcat[S]:
		return cs.bitVectorConcat(m.first, m.second, m.firstWidth, m.secondWidth)
	case bitVectorExtract[S]:
		return cs.bitVectorExtract(m.value, m.high, m.low)
	case bitVectorZeroExtend[S]:
		return cs.bitVectorZeroExtend(m.value, m.additional)
	case bitVectorSignExtend[S]:
		return cs.bitVectorSignExtend(m.value, m.additional)
	case bitVectorRotateLeft[S]:
		return cs.bitVectorRotateLeft(m.value, m.amount)
	case bitVectorRotateRight[S]:
		return cs.bitVectorRotateRight(m.value, m.amount)
	case bitVectorRepeat[S]:
		return cs.bitVectorRepeat(m.value, m.count)
	case bitVectorUnsignedLess[S]:
		return cs.bitVectorUnsignedLess(m.left, m.right, m.orEqual)
	case bitVectorSignedLess[S]:
		return cs.bitVectorSignedLess(m.left, m.right, m.orEqual)
	case bitVectorUnsignedAddOverflow[S]:
		return cs.bitVectorUnsignedAddOverflow(m.left, m.right)
	case bitVectorSignedAddOverflow[S]:
		return cs.bitVectorSignedAddOverflow(m.left, m.right)
	case bitVectorUnsignedSubOverflow[S]:
		return cs.bitVectorUnsignedSubOverflow(m.left, m.right)
	case bitVectorSignedSubOverflow[S]:
		return cs.bitVectorSignedSubOverflow(m.left, m.right)
	case bitVectorUnsignedMulOverflow[S]:
		return cs.bitVectorUnsignedMulOverflow(m.left, m.right)
	case bitVectorSignedMulOverflow[S]:
		return cs.bitVectorSignedMulOverflow(m.left, m.right)
	case bitVectorSignedDivOverflow[S]:
		return cs.bitVectorSignedDivOverflow(m.left, m.right)
	case bitVectorNegOverflow[S]:
		return cs.bitVectorNegOverflow(m.value)
	case bitVectorToInteger[S]:
		return cs.bitVectorToInteger(m.value, m.signed)
	case integerToBitVector[S]:
		return cs.integerToBitVector(m.value, m.width)
	case arraySymbol[S]:
		return cs.arraySymbol(m.iD, m.name)
	case constantArray[S]:
		return cs.constantArray(m.defaultValue)
	case arraySelect[S]:
		return cs.arraySelect(m.array, m.index)
	case arrayStore[S]:
		return cs.arrayStore(m.array, m.index, m.value)
	case arrayReadInteger[S]:
		return cs.arrayReadInteger(m.arrayID, m.index)
	case arrayStoreReadInteger[S]:
		return cs.arrayStoreReadInteger(m.arrayID, m.storeIndexID, m.readIndexID, m.value)
	default:
		panic("goplus: impossible enum value in TermFold")
	}
}

//goplus:enum AnyTerm
type AnyTerm interface{ isAnyTerm() }

//goplus:variant (AnyTerm) SomeBool(Value Term[BoolSort])
type SomeBool struct {
	Value Term[BoolSort]
}

func (SomeBool) isAnyTerm() {}

//goplus:variant (AnyTerm) SomeInt(Value Term[IntSort])
type SomeInt struct {
	Value Term[IntSort]
}

func (SomeInt) isAnyTerm() {}

//goplus:variant (AnyTerm) SomeReal(Value Term[RealSort])
type SomeReal struct {
	Value Term[RealSort]
}

func (SomeReal) isAnyTerm() {}

// AnyTermCases selects one handler per AnyTerm variant for AnyTermFold.
type AnyTermCases[R any] struct {
	SomeBool func(Value Term[BoolSort]) R
	SomeInt  func(Value Term[IntSort]) R
	SomeReal func(Value Term[RealSort]) R
}

// AnyTermFold reduces AnyTerm by one-level case analysis.
func AnyTermFold[R any](a AnyTerm, cs AnyTermCases[R]) R {
	switch m := any(a).(type) {
	case SomeBool:
		return cs.SomeBool(m.Value)
	case SomeInt:
		return cs.SomeInt(m.Value)
	case SomeReal:
		return cs.SomeReal(m.Value)
	default:
		panic("goplus: impossible enum value in AnyTermFold")
	}
}

// AnyTermEqOverrides carries optional per-variant hooks for AnyTermEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type AnyTermEqOverrides struct {
	SomeBool func(x, y SomeBool) (eq, handled bool)
	SomeInt  func(x, y SomeInt) (eq, handled bool)
	SomeReal func(x, y SomeReal) (eq, handled bool)
}

// AnyTermEqualWith reports structural equality of a and b under ov.
func AnyTermEqualWith(a, b AnyTerm, ov AnyTermEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case SomeBool:
		y, ok := any(b).(SomeBool)
		if !ok {
			return false
		}
		if ov.SomeBool != nil {
			if eq, handled := ov.SomeBool(x, y); handled {
				return eq
			}
		}
		if x.Value != y.Value {
			return false
		}
		return true
	case SomeInt:
		y, ok := any(b).(SomeInt)
		if !ok {
			return false
		}
		if ov.SomeInt != nil {
			if eq, handled := ov.SomeInt(x, y); handled {
				return eq
			}
		}
		if x.Value != y.Value {
			return false
		}
		return true
	case SomeReal:
		y, ok := any(b).(SomeReal)
		if !ok {
			return false
		}
		if ov.SomeReal != nil {
			if eq, handled := ov.SomeReal(x, y); handled {
				return eq
			}
		}
		if x.Value != y.Value {
			return false
		}
		return true
	}
	return false
}

// AnyTermEqual reports structural equality of a and b.
func AnyTermEqual(a, b AnyTerm) bool {
	return AnyTermEqualWith(a, b, AnyTermEqOverrides{})
}

//goplus:enum UnknownReason
type UnknownReason interface{ isUnknownReason() }

//goplus:variant (UnknownReason) UnsupportedTheory(Name string)
type UnsupportedTheory struct {
	Name string
}

func (UnsupportedTheory) isUnknownReason() {}

//goplus:variant (UnknownReason) ResourceLimit(Limit int)
type ResourceLimit struct {
	Limit int
}

func (ResourceLimit) isUnknownReason() {}

//goplus:variant (UnknownReason) Canceled()
type Canceled struct{}

func (Canceled) isUnknownReason() {}

// UnknownReasonCases selects one handler per UnknownReason variant for UnknownReasonFold.
type UnknownReasonCases[R any] struct {
	UnsupportedTheory func(Name string) R
	ResourceLimit     func(Limit int) R
	Canceled          func() R
}

// UnknownReasonFold reduces UnknownReason by one-level case analysis.
func UnknownReasonFold[R any](u UnknownReason, cs UnknownReasonCases[R]) R {
	switch m := any(u).(type) {
	case UnsupportedTheory:
		return cs.UnsupportedTheory(m.Name)
	case ResourceLimit:
		return cs.ResourceLimit(m.Limit)
	case Canceled:
		return cs.Canceled()
	default:
		panic("goplus: impossible enum value in UnknownReasonFold")
	}
}

// UnknownReasonEqOverrides carries optional per-variant hooks for UnknownReasonEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type UnknownReasonEqOverrides struct {
	UnsupportedTheory func(x, y UnsupportedTheory) (eq, handled bool)
	ResourceLimit     func(x, y ResourceLimit) (eq, handled bool)
	Canceled          func(x, y Canceled) (eq, handled bool)
}

// UnknownReasonEqualWith reports structural equality of a and b under ov.
func UnknownReasonEqualWith(a, b UnknownReason, ov UnknownReasonEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case UnsupportedTheory:
		y, ok := any(b).(UnsupportedTheory)
		if !ok {
			return false
		}
		if ov.UnsupportedTheory != nil {
			if eq, handled := ov.UnsupportedTheory(x, y); handled {
				return eq
			}
		}
		if x.Name != y.Name {
			return false
		}
		return true
	case ResourceLimit:
		y, ok := any(b).(ResourceLimit)
		if !ok {
			return false
		}
		if ov.ResourceLimit != nil {
			if eq, handled := ov.ResourceLimit(x, y); handled {
				return eq
			}
		}
		if x.Limit != y.Limit {
			return false
		}
		return true
	case Canceled:
		y, ok := any(b).(Canceled)
		if !ok {
			return false
		}
		if ov.Canceled != nil {
			if eq, handled := ov.Canceled(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// UnknownReasonEqual reports structural equality of a and b.
func UnknownReasonEqual(a, b UnknownReason) bool {
	return UnknownReasonEqualWith(a, b, UnknownReasonEqOverrides{})
}

// Solver[c,d] has assertion fingerprint c and scope depth d. Constructors are
// sealed so generated Go callers cross runtime witness checks.
//
//goplus:enum Solver[c nat, d nat]
//goplus:derive off
//goplus:repr transparent
type Solver = solverValue

//goplus:variant (Solver) solverValue(ContextID int, Depth int, State *engine) Solver[c, d]
type solverValue struct {
	contextID int
	depth     int
	state     *engine
}

func (solverValue) isSolver() {}

// Model[c] and Proof[c] can only be consumed with terms/assertions from the
// checked solver context that produced them.
//
//goplus:enum Model[c nat]
//goplus:derive off
//goplus:repr transparent
type Model = modelValue

//goplus:variant (Model) modelValue(ContextID int, Booleans booleanModel, Integers integerModel, Reals rationalModel, BitVectors bitVectorModel, Arrays *integerArrayModel, BitVectorArrays *bitVectorArrayModel) Model[c]
type modelValue struct {
	contextID       int
	booleans        booleanModel
	integers        integerModel
	reals           rationalModel
	bitVectors      bitVectorModel
	arrays          *integerArrayModel
	bitVectorArrays *bitVectorArrayModel
}

func (modelValue) isModel() {}

//goplus:enum Proof[c nat]
//goplus:derive off
//goplus:repr transparent
type Proof = proofValue

//goplus:variant (Proof) proofValue(ContextID int, Assertions int) Proof[c]
type proofValue struct {
	contextID  int
	assertions int
}

func (proofValue) isProof() {}

//goplus:enum CheckResult[c nat]
type CheckResult interface{ isCheckResult() }

//goplus:variant (CheckResult) Satisfiable(Value Model[c])
type Satisfiable struct {
	Value Model
}

func (Satisfiable) isCheckResult() {}

//goplus:variant (CheckResult) Unsatisfiable(Value Proof[c])
type Unsatisfiable struct {
	Value Proof
}

func (Unsatisfiable) isCheckResult() {}

//goplus:variant (CheckResult) Unknown(Context Proof[c], Reason UnknownReason)
type Unknown struct {
	Context Proof
	Reason  UnknownReason
}

func (Unknown) isCheckResult() {}

// CheckResultCases selects one handler per CheckResult variant for CheckResultFold.
type CheckResultCases[R any] struct {
	Satisfiable   func(Value Model) R
	Unsatisfiable func(Value Proof) R
	Unknown       func(Context Proof, Reason UnknownReason) R
}

// CheckResultFold reduces CheckResult by one-level case analysis.
func CheckResultFold[R any](v CheckResult, cs CheckResultCases[R]) R {
	switch m := any(v).(type) {
	case Satisfiable:
		return cs.Satisfiable(m.Value)
	case Unsatisfiable:
		return cs.Unsatisfiable(m.Value)
	case Unknown:
		return cs.Unknown(m.Context, m.Reason)
	default:
		panic("goplus: impossible enum value in CheckResultFold")
	}
}

//goplus:enum AssumptionCheckResult[c nat]
type AssumptionCheckResult interface{ isAssumptionCheckResult() }

//goplus:variant (AssumptionCheckResult) AssumptionsSatisfiable(Value Model[c])
type AssumptionsSatisfiable struct {
	Value Model
}

func (AssumptionsSatisfiable) isAssumptionCheckResult() {}

//goplus:variant (AssumptionCheckResult) AssumptionsUnsatisfiable(Value Proof[c], Indices []int)
type AssumptionsUnsatisfiable struct {
	Value   Proof
	Indices []int
}

func (AssumptionsUnsatisfiable) isAssumptionCheckResult() {}

//goplus:variant (AssumptionCheckResult) AssumptionsUnknown(Context Proof[c], Reason UnknownReason)
type AssumptionsUnknown struct {
	Context Proof
	Reason  UnknownReason
}

func (AssumptionsUnknown) isAssumptionCheckResult() {}

// AssumptionCheckResultCases selects one handler per AssumptionCheckResult variant for AssumptionCheckResultFold.
type AssumptionCheckResultCases[R any] struct {
	AssumptionsSatisfiable   func(Value Model) R
	AssumptionsUnsatisfiable func(Value Proof, Indices []int) R
	AssumptionsUnknown       func(Context Proof, Reason UnknownReason) R
}

// AssumptionCheckResultFold reduces AssumptionCheckResult by one-level case analysis.
func AssumptionCheckResultFold[R any](a AssumptionCheckResult, cs AssumptionCheckResultCases[R]) R {
	switch m := any(a).(type) {
	case AssumptionsSatisfiable:
		return cs.AssumptionsSatisfiable(m.Value)
	case AssumptionsUnsatisfiable:
		return cs.AssumptionsUnsatisfiable(m.Value, m.Indices)
	case AssumptionsUnknown:
		return cs.AssumptionsUnknown(m.Context, m.Reason)
	default:
		panic("goplus: impossible enum value in AssumptionCheckResultFold")
	}
}

// Checkpoint packages the pre-push context. Restore requires the exact
// checkpoint rather than accepting an untyped integer depth.
//
//goplus:enum Checkpoint[c nat, d nat]
//goplus:derive off
//goplus:repr transparent
type Checkpoint = checkpointValue

//goplus:variant (Checkpoint) checkpointValue(ContextID int, Depth int, State *engine) Checkpoint[c, d]
type checkpointValue struct {
	contextID int
	depth     int
	state     *engine
}

func (checkpointValue) isCheckpoint() {}

//goplus:enum Pushed[c nat, d nat]
//goplus:derive off
//goplus:repr transparent
type Pushed = PushResult

//goplus:variant (Pushed) PushResult(Current Solver[c, d+1], Previous Checkpoint[c, d])
type PushResult struct {
	Current  Solver
	Previous Checkpoint
}

func (PushResult) isPushed() {}

//goplus:total ContextID(context nat, assertion nat) nat
func ContextID(context int, assertion int) int {
	return ((context+assertion)*(context+assertion+1) + assertion) + 1
}

//goplus:dep New() Solver[0, 0]
func New() Solver { return solverValue{contextID: 0, depth: 0, state: newEngine()} }

func IntegerTerm(value IntegerValue) Term[IntSort] { return integerExact[IntSort]{value: value} }
func IntegerVariable(id int) Term[IntSort]         { return integerVariable[IntSort]{iD: id} }
func ScaleInteger(coefficient IntegerValue, value Term[IntSort]) Term[IntSort] {
	return IntegerScale{Coefficient: coefficient, Value: value}
}
func DivInteger(dividend Term[IntSort], divisor IntegerValue) Term[IntSort] {
	return IntegerDiv{Dividend: dividend, Divisor: divisor}
}
func ModInteger(dividend Term[IntSort], divisor IntegerValue) Term[IntSort] {
	return IntegerMod{Dividend: dividend, Divisor: divisor}
}

func IntegerVariableID(term Term[IntSort]) (int, bool) {
	switch __gp_m0 := any(term).(type) {
	case IntSymbol:
		id := __gp_m0.ID

		return id, true
	case integerVariable[IntSort]:
		id := __gp_m0.iD

		return id, true
	default:

		return 0, false
	}
}

func ArrayConst[I any, E any](id int, name string) Term[ArraySort[I, E]] {
	return arraySymbol[ArraySort[I, E]]{iD: id, name: name}
}

func ConstArray[I any, E any](value Term[E]) Term[ArraySort[I, E]] {
	return constantArray[ArraySort[I, E]]{defaultValue: value}
}

func Select[I any, E any](array Term[ArraySort[I, E]], index Term[I]) Term[E] {
	return arraySelect[E]{array: array, index: index}
}

func Store[I any, E any](array Term[ArraySort[I, E]], index Term[I], value Term[E]) Term[ArraySort[I, E]] {
	return arrayStore[ArraySort[I, E]]{array: array, index: index, value: value}
}

func IntegerArrayRead(arrayID int, index IntegerValue) Term[IntSort] {
	return arrayReadInteger[IntSort]{arrayID: arrayID, index: index}
}

func SymbolicIntegerArrayStoreRead(arrayID int, storeIndexID int, readIndexID int, value IntegerValue) Term[IntSort] {
	return arrayStoreReadInteger[IntSort]{arrayID: arrayID, storeIndexID: storeIndexID, readIndexID: readIndexID, value: value}
}

//goplus:dep UninterpretedConstant(sort nat, id int, name string) Term[UninterpretedSort[sort]]
func UninterpretedConstant(sort int, id int, name string) Term[UninterpretedSort] {
	if sort < 0 {
		panic("smt: negative uninterpreted sort identity")
	}
	return uninterpretedValue[UninterpretedSort]{sortID: sort, iD: id, name: name}
}

//goplus:dep DeclareUnaryFunction(domain nat, codomain nat, id int, name string) UnaryFunction[domain, codomain]
func DeclareUnaryFunction(domain int, codomain int, id int, name string) UnaryFunction {
	if domain < 0 || codomain < 0 {
		panic("smt: negative uninterpreted function sort identity")
	}
	return unaryFunctionValue{domainID: int(domain), rangeID: int(codomain), iD: id, name: name}
}

//goplus:dep ApplyUnary(0 domain nat, 0 codomain nat, function UnaryFunction[domain, codomain], argument Term[UninterpretedSort[domain]]) Term[UninterpretedSort[codomain]]
func ApplyUnary(function UnaryFunction, argument Term[UninterpretedSort]) Term[UninterpretedSort] {
	return unaryApplication[UninterpretedSort]{function: function, argument: argument}
}

//goplus:dep DeclareBinaryFunction(first nat, second nat, codomain nat, id int, name string) BinaryFunction[first, second, codomain]
func DeclareBinaryFunction(first int, second int, codomain int, id int, name string) BinaryFunction {
	if first < 0 || second < 0 || codomain < 0 {
		panic("smt: negative uninterpreted function sort identity")
	}
	return binaryFunctionValue{firstID: int(first), secondID: int(second), rangeID: int(codomain), iD: id, name: name}
}

//goplus:dep ApplyBinary(0 first nat, 0 second nat, 0 codomain nat, function BinaryFunction[first, second, codomain], left Term[UninterpretedSort[first]], right Term[UninterpretedSort[second]]) Term[UninterpretedSort[codomain]]
func ApplyBinary(function BinaryFunction, left Term[UninterpretedSort], right Term[UninterpretedSort]) Term[UninterpretedSort] {
	return binaryApplication[UninterpretedSort]{function: function, first: left, second: right}
}

func DeclareRealUnaryFunction(id int, name string) SortedUnaryFunction[RealSort, RealSort] {
	return sortedUnaryFunctionValue[RealSort, RealSort]{domainKind: -1, rangeKind: -1, iD: id, name: name}
}

func ApplySortedUnary[D any, R any](function SortedUnaryFunction[D, R], argument Term[D]) Term[R] {
	return sortedUnaryApplication[R]{function: function, argument: argument, rangeKind: -1}
}

func DeclareRealBinaryFunction(id int, name string) SortedBinaryFunction[RealSort, RealSort, RealSort] {
	return sortedBinaryFunctionValue[RealSort, RealSort, RealSort]{firstKind: -1, secondKind: -1, rangeKind: -1, iD: id, name: name}
}

func ApplySortedBinary[A any, B any, R any](function SortedBinaryFunction[A, B, R], first Term[A], second Term[B]) Term[R] {
	return sortedBinaryApplication[R]{function: function, first: first, second: second, rangeKind: -1}
}

//goplus:dep DeclareBitVecUnaryFunction(domainWidth nat, rangeWidth nat, id int, name string) SortedUnaryFunction[BitVecSort[domainWidth], BitVecSort[rangeWidth]]
func DeclareBitVecUnaryFunction(domainWidth int, rangeWidth int, id int, name string) SortedUnaryFunction[BitVecSort, BitVecSort] {
	if domainWidth <= 0 || rangeWidth <= 0 {
		panic("smt: bit-vector function widths must be positive")
	}
	return sortedUnaryFunctionValue[BitVecSort, BitVecSort]{domainKind: int(domainWidth), rangeKind: int(rangeWidth), iD: id, name: name}
}

//goplus:dep ApplyBitVecUnary(0 domainWidth nat, 0 rangeWidth nat, function SortedUnaryFunction[BitVecSort[domainWidth], BitVecSort[rangeWidth]], argument Term[BitVecSort[domainWidth]]) Term[BitVecSort[rangeWidth]]
func ApplyBitVecUnary(function SortedUnaryFunction[BitVecSort, BitVecSort], argument Term[BitVecSort]) Term[BitVecSort] {
	return sortedUnaryApplication[BitVecSort]{function: function, argument: argument, rangeKind: 0}
}

func BitVecUnaryFunctionInfo[D any, R any](function SortedUnaryFunction[D, R]) (int, int, int) {
	switch __gp_m1 := any(function).(type) {
	case sortedUnaryFunctionValue[D, R]:
		domain := __gp_m1.domainKind
		rangeKind := __gp_m1.rangeKind
		id := __gp_m1.iD
		return domain, rangeKind, id
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep DeclareBitVecBinaryFunction(firstWidth nat, secondWidth nat, rangeWidth nat, id int, name string) SortedBinaryFunction[BitVecSort[firstWidth], BitVecSort[secondWidth], BitVecSort[rangeWidth]]
func DeclareBitVecBinaryFunction(firstWidth int, secondWidth int, rangeWidth int, id int, name string) SortedBinaryFunction[BitVecSort, BitVecSort, BitVecSort] {
	if firstWidth <= 0 || secondWidth <= 0 || rangeWidth <= 0 {
		panic("smt: bit-vector function widths must be positive")
	}
	return sortedBinaryFunctionValue[BitVecSort, BitVecSort, BitVecSort]{firstKind: int(firstWidth), secondKind: int(secondWidth), rangeKind: int(rangeWidth), iD: id, name: name}
}

//goplus:dep ApplyBitVecBinary(0 firstWidth nat, 0 secondWidth nat, 0 rangeWidth nat, function SortedBinaryFunction[BitVecSort[firstWidth], BitVecSort[secondWidth], BitVecSort[rangeWidth]], first Term[BitVecSort[firstWidth]], second Term[BitVecSort[secondWidth]]) Term[BitVecSort[rangeWidth]]
func ApplyBitVecBinary(function SortedBinaryFunction[BitVecSort, BitVecSort, BitVecSort], first Term[BitVecSort], second Term[BitVecSort]) Term[BitVecSort] {
	return sortedBinaryApplication[BitVecSort]{function: function, first: first, second: second, rangeKind: 0}
}

//goplus:dep BitVecVal(width nat, value uint64) Term[BitVecSort[width]]
func BitVecVal(width int, value uint64) Term[BitVecSort] {
	return bitVector[BitVecSort]{value: NewBitVectorUint64(int(width), value)}
}

//goplus:dep BitVecConst(width nat, id int, name string) Term[BitVecSort[width]]
func BitVecConst(width int, id int, name string) Term[BitVecSort] {
	if width <= 0 {
		panic("smt: bit-vector width must be positive")
	}
	return bitVectorSymbol[BitVecSort]{width: int(width), iD: id, name: name}
}

//goplus:dep BitVecNot(0 width nat, value Term[BitVecSort[width]]) Term[BitVecSort[width]]
func BitVecNot(value Term[BitVecSort]) Term[BitVecSort] {
	return bitVectorNot[BitVecSort]{value: value}
}

//goplus:dep BitVecAnd(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BitVecSort[width]]
func BitVecAnd(left Term[BitVecSort], right Term[BitVecSort]) Term[BitVecSort] {
	return bitVectorAnd[BitVecSort]{left: left, right: right}
}

//goplus:dep BitVecOr(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BitVecSort[width]]
func BitVecOr(left Term[BitVecSort], right Term[BitVecSort]) Term[BitVecSort] {
	return bitVectorOr[BitVecSort]{left: left, right: right}
}

//goplus:dep BitVecXor(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BitVecSort[width]]
func BitVecXor(left Term[BitVecSort], right Term[BitVecSort]) Term[BitVecSort] {
	return bitVectorXor[BitVecSort]{left: left, right: right}
}

//goplus:dep BitVecAdd(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BitVecSort[width]]
func BitVecAdd(left Term[BitVecSort], right Term[BitVecSort]) Term[BitVecSort] {
	return bitVectorAdd[BitVecSort]{left: left, right: right}
}

//goplus:dep BitVecSub(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BitVecSort[width]]
func BitVecSub(left Term[BitVecSort], right Term[BitVecSort]) Term[BitVecSort] {
	return bitVectorSub[BitVecSort]{left: left, right: right}
}

//goplus:dep BitVecMul(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BitVecSort[width]]
func BitVecMul(left Term[BitVecSort], right Term[BitVecSort]) Term[BitVecSort] {
	return bitVectorMul[BitVecSort]{left: left, right: right}
}

//goplus:dep BitVecSHL(0 width nat, value Term[BitVecSort[width]], amount Term[BitVecSort[width]]) Term[BitVecSort[width]]
func BitVecSHL(value Term[BitVecSort], amount Term[BitVecSort]) Term[BitVecSort] {
	return bitVectorShiftLeft[BitVecSort]{value: value, amount: amount}
}

//goplus:dep BitVecLSHR(0 width nat, value Term[BitVecSort[width]], amount Term[BitVecSort[width]]) Term[BitVecSort[width]]
func BitVecLSHR(value Term[BitVecSort], amount Term[BitVecSort]) Term[BitVecSort] {
	return bitVectorLogicalShiftRight[BitVecSort]{value: value, amount: amount}
}

//goplus:dep BitVecASHR(0 width nat, value Term[BitVecSort[width]], amount Term[BitVecSort[width]]) Term[BitVecSort[width]]
func BitVecASHR(value Term[BitVecSort], amount Term[BitVecSort]) Term[BitVecSort] {
	return bitVectorArithmeticShiftRight[BitVecSort]{value: value, amount: amount}
}

//goplus:dep BitVecUDiv(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BitVecSort[width]]
func BitVecUDiv(left Term[BitVecSort], right Term[BitVecSort]) Term[BitVecSort] {
	return bitVectorUnsignedDiv[BitVecSort]{left: left, right: right}
}

//goplus:dep BitVecURem(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BitVecSort[width]]
func BitVecURem(left Term[BitVecSort], right Term[BitVecSort]) Term[BitVecSort] {
	return bitVectorUnsignedRem[BitVecSort]{left: left, right: right}
}

//goplus:dep BitVecSDiv(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BitVecSort[width]]
func BitVecSDiv(left Term[BitVecSort], right Term[BitVecSort]) Term[BitVecSort] {
	return bitVectorSignedDiv[BitVecSort]{left: left, right: right}
}

//goplus:dep BitVecSRem(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BitVecSort[width]]
func BitVecSRem(left Term[BitVecSort], right Term[BitVecSort]) Term[BitVecSort] {
	return bitVectorSignedRem[BitVecSort]{left: left, right: right}
}

//goplus:dep BitVecConcat(firstWidth nat, secondWidth nat, first Term[BitVecSort[firstWidth]], second Term[BitVecSort[secondWidth]]) Term[BitVecSort[firstWidth+secondWidth]]
func BitVecConcat(firstWidth int, secondWidth int, first Term[BitVecSort], second Term[BitVecSort]) Term[BitVecSort] {
	return bitVectorConcat[BitVecSort]{first: first, second: second, firstWidth: int(firstWidth), secondWidth: int(secondWidth)}
}

//goplus:dep BitVecExtract(high nat, low nat, 0 width nat, value Term[BitVecSort[width]]) Term[BitVecSort[high-low+1]]
func BitVecExtract(high int, low int, value Term[BitVecSort]) Term[BitVecSort] {
	if low < 0 || high < low {
		panic("smt: invalid bit-vector extraction range")
	}
	return bitVectorExtract[BitVecSort]{value: value, high: int(high), low: int(low)}
}

//goplus:dep BitVecZeroExtend(additional nat, 0 width nat, value Term[BitVecSort[width]]) Term[BitVecSort[width+additional]]
func BitVecZeroExtend(additional int, value Term[BitVecSort]) Term[BitVecSort] {
	if additional < 0 {
		panic("smt: negative bit-vector extension")
	}
	return bitVectorZeroExtend[BitVecSort]{value: value, additional: int(additional)}
}

//goplus:dep BitVecSignExtend(additional nat, 0 width nat, value Term[BitVecSort[width]]) Term[BitVecSort[width+additional]]
func BitVecSignExtend(additional int, value Term[BitVecSort]) Term[BitVecSort] {
	if additional < 0 {
		panic("smt: negative bit-vector extension")
	}
	return bitVectorSignExtend[BitVecSort]{value: value, additional: int(additional)}
}

//goplus:dep BitVecRotateLeft(amount nat, 0 width nat, value Term[BitVecSort[width]]) Term[BitVecSort[width]]
func BitVecRotateLeft(amount int, value Term[BitVecSort]) Term[BitVecSort] {
	if amount < 0 {
		panic("smt: negative bit-vector rotation")
	}
	return bitVectorRotateLeft[BitVecSort]{value: value, amount: int(amount)}
}

//goplus:dep BitVecRotateRight(amount nat, 0 width nat, value Term[BitVecSort[width]]) Term[BitVecSort[width]]
func BitVecRotateRight(amount int, value Term[BitVecSort]) Term[BitVecSort] {
	if amount < 0 {
		panic("smt: negative bit-vector rotation")
	}
	return bitVectorRotateRight[BitVecSort]{value: value, amount: int(amount)}
}

//goplus:dep BitVecRepeat(count nat, 0 width nat, value Term[BitVecSort[width]]) Term[BitVecSort[width*count]]
func BitVecRepeat(count int, value Term[BitVecSort]) Term[BitVecSort] {
	if count <= 0 {
		panic("smt: bit-vector repeat count must be positive")
	}
	return bitVectorRepeat[BitVecSort]{value: value, count: int(count)}
}

//goplus:dep BitVecULT(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BoolSort]
func BitVecULT(left Term[BitVecSort], right Term[BitVecSort]) Term[BoolSort] {
	return bitVectorUnsignedLess[BoolSort]{left: left, right: right, orEqual: false}
}

//goplus:dep BitVecULE(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BoolSort]
func BitVecULE(left Term[BitVecSort], right Term[BitVecSort]) Term[BoolSort] {
	return bitVectorUnsignedLess[BoolSort]{left: left, right: right, orEqual: true}
}

//goplus:dep BitVecSLT(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BoolSort]
func BitVecSLT(left Term[BitVecSort], right Term[BitVecSort]) Term[BoolSort] {
	return bitVectorSignedLess[BoolSort]{left: left, right: right, orEqual: false}
}

//goplus:dep BitVecSLE(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BoolSort]
func BitVecSLE(left Term[BitVecSort], right Term[BitVecSort]) Term[BoolSort] {
	return bitVectorSignedLess[BoolSort]{left: left, right: right, orEqual: true}
}

//goplus:dep BitVecUAddOverflow(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BoolSort]
func BitVecUAddOverflow(left Term[BitVecSort], right Term[BitVecSort]) Term[BoolSort] {
	return bitVectorUnsignedAddOverflow[BoolSort]{left: left, right: right}
}

//goplus:dep BitVecSAddOverflow(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BoolSort]
func BitVecSAddOverflow(left Term[BitVecSort], right Term[BitVecSort]) Term[BoolSort] {
	return bitVectorSignedAddOverflow[BoolSort]{left: left, right: right}
}

//goplus:dep BitVecUSubOverflow(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BoolSort]
func BitVecUSubOverflow(left Term[BitVecSort], right Term[BitVecSort]) Term[BoolSort] {
	return bitVectorUnsignedSubOverflow[BoolSort]{left: left, right: right}
}

//goplus:dep BitVecSSubOverflow(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BoolSort]
func BitVecSSubOverflow(left Term[BitVecSort], right Term[BitVecSort]) Term[BoolSort] {
	return bitVectorSignedSubOverflow[BoolSort]{left: left, right: right}
}

//goplus:dep BitVecUMulOverflow(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BoolSort]
func BitVecUMulOverflow(left Term[BitVecSort], right Term[BitVecSort]) Term[BoolSort] {
	return bitVectorUnsignedMulOverflow[BoolSort]{left: left, right: right}
}

//goplus:dep BitVecSMulOverflow(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BoolSort]
func BitVecSMulOverflow(left Term[BitVecSort], right Term[BitVecSort]) Term[BoolSort] {
	return bitVectorSignedMulOverflow[BoolSort]{left: left, right: right}
}

//goplus:dep BitVecSDivOverflow(0 width nat, left Term[BitVecSort[width]], right Term[BitVecSort[width]]) Term[BoolSort]
func BitVecSDivOverflow(left Term[BitVecSort], right Term[BitVecSort]) Term[BoolSort] {
	return bitVectorSignedDivOverflow[BoolSort]{left: left, right: right}
}

//goplus:dep BitVecNegOverflow(0 width nat, value Term[BitVecSort[width]]) Term[BoolSort]
func BitVecNegOverflow(value Term[BitVecSort]) Term[BoolSort] {
	return bitVectorNegOverflow[BoolSort]{value: value}
}

//goplus:dep BitVecToNat(0 width nat, value Term[BitVecSort[width]]) Term[IntSort]
func BitVecToNat(value Term[BitVecSort]) Term[IntSort] {
	return bitVectorToInteger[IntSort]{value: value, signed: false}
}

//goplus:dep BitVecToInt(0 width nat, value Term[BitVecSort[width]]) Term[IntSort]
func BitVecToInt(value Term[BitVecSort]) Term[IntSort] {
	return bitVectorToInteger[IntSort]{value: value, signed: true}
}

//goplus:dep IntToBitVec(width nat, value Term[IntSort]) Term[BitVecSort[width]]
func IntToBitVec(width int, value Term[IntSort]) Term[BitVecSort] {
	if width <= 0 {
		panic("smt: bit-vector width must be positive")
	}
	return integerToBitVector[BitVecSort]{value: value, width: int(width)}
}

//goplus:dep Assert(assertion nat, 0 c nat, 0 d nat, solver Solver[c, d], formula Term[BoolSort]) Solver[ContextID(c, assertion), d]
func Assert(assertion int, solver Solver, formula Term[BoolSort]) Solver {
	switch __gp_m2 := any(solver).(type) {
	case solverValue:
		context := __gp_m2.contextID
		depth := __gp_m2.depth
		state := __gp_m2.state

		if assertion < 0 {
			panic("smt: negative assertion identity")
		}
		nextContext := runtimeContextID(context, int(assertion))
		return solverValue{contextID: nextContext, depth: depth, state: state.asserted(formula)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep Push(0 c nat, 0 d nat, solver Solver[c, d]) Pushed[c, d]
func Push(solver Solver) Pushed {
	switch __gp_m3 := any(solver).(type) {
	case solverValue:
		context := __gp_m3.contextID
		depth := __gp_m3.depth
		state := __gp_m3.state

		return PushResult{Current: solverValue{contextID: context, depth: depth + 1, state: state}, Previous: checkpointValue{contextID: context, depth: depth, state: state}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep Current(0 c nat, 0 d nat, pushed Pushed[c, d]) Solver[c, d+1]
func Current(pushed Pushed) Solver {
	switch __gp_m4 := any(pushed).(type) {
	case PushResult:
		current := __gp_m4.Current
		return current
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep Previous(0 c nat, 0 d nat, pushed Pushed[c, d]) Checkpoint[c, d]
func Previous(pushed Pushed) Checkpoint {
	switch __gp_m5 := any(pushed).(type) {
	case PushResult:
		previous := __gp_m5.Previous
		return previous
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep Restore(0 current nat, 0 parent nat, 0 d nat, solver Solver[current, d+1], checkpoint Checkpoint[parent, d]) Solver[parent, d]
func Restore(solver Solver, checkpoint Checkpoint) Solver {
	switch __gp_m6 := any(solver).(type) {
	case solverValue:
		depth := __gp_m6.depth

		switch __gp_m7 := any(checkpoint).(type) {
		case checkpointValue:
			context := __gp_m7.contextID
			previousDepth := __gp_m7.depth
			state := __gp_m7.state

			if depth != previousDepth+1 {
				panic("smt: checkpoint depth mismatch")
			}
			return solverValue{contextID: context, depth: previousDepth, state: state}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep Check(0 c nat, 0 d nat, solver Solver[c, d]) CheckResult[c]
func Check(solver Solver) CheckResult {
	switch __gp_m8 := any(solver).(type) {
	case solverValue:
		context := __gp_m8.contextID
		depth := __gp_m8.depth
		state := __gp_m8.state

		if depth < 0 {
			panic("smt: invalid depth")
		}
		return runtimeCheckResult(context, state)
	default:
		panic("goplus: impossible enum value in match")
	}
}

// CheckAssuming solves with temporary Boolean assumptions. An unsatisfiable
// result carries a deletion-minimized set of indices into assumptions.
//
//goplus:dep CheckAssuming(0 c nat, 0 d nat, solver Solver[c, d], assumptions ...Term[BoolSort]) AssumptionCheckResult[c]
func CheckAssuming(solver Solver, assumptions ...Term[BoolSort]) AssumptionCheckResult {
	switch __gp_m9 := any(solver).(type) {
	case solverValue:
		context := __gp_m9.contextID
		depth := __gp_m9.depth
		state := __gp_m9.state

		if depth < 0 {
			panic("smt: invalid depth")
		}
		status, booleans, integers, reals, bitVectors, core, reason := state.checkAssuming(assumptions)
		switch status {
		case checkSat:
			return AssumptionsSatisfiable{Value: modelValue{contextID: context, booleans: booleans, integers: integers, reals: reals, bitVectors: bitVectors, arrays: nil, bitVectorArrays: nil}}
		case checkUnsat:
			return AssumptionsUnsatisfiable{Value: proofValue{contextID: context, assertions: len(state.assertions)}, Indices: core}
		default:
			return AssumptionsUnknown{Context: proofValue{contextID: context, assertions: len(state.assertions)}, Reason: reason}
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep BoolValue(0 c nat, model Model[c], term Term[BoolSort]) (bool, bool)
func BoolValue(model Model, term Term[BoolSort]) (bool, bool) {
	switch __gp_m10 := any(model).(type) {
	case modelValue:
		booleans := __gp_m10.booleans
		integers := __gp_m10.integers
		reals := __gp_m10.reals
		return evaluateBool(term, booleans, integers, reals)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep IntValue(0 c nat, model Model[c], term Term[IntSort]) (int64, bool)
func IntValue(model Model, term Term[IntSort]) (int64, bool) {
	switch __gp_m11 := any(model).(type) {
	case modelValue:
		booleans := __gp_m11.booleans
		integers := __gp_m11.integers
		reals := __gp_m11.reals
		return evaluateInt(term, booleans, integers, reals)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep ExactIntValue(0 c nat, model Model[c], term Term[IntSort]) (IntegerValue, bool)
func ExactIntValue(model Model, term Term[IntSort]) (IntegerValue, bool) {
	switch __gp_m12 := any(model).(type) {
	case modelValue:
		booleans := __gp_m12.booleans
		integers := __gp_m12.integers
		reals := __gp_m12.reals
		bitVectors := __gp_m12.bitVectors
		return evaluateIntegerWithBitVectors(term, booleans, integers, reals, bitVectors)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep IntegerModelValue(0 c nat, model Model[c], term Term[IntSort]) (IntegerValue, bool)
func IntegerModelValue(model Model, term Term[IntSort]) (IntegerValue, bool) {
	switch __gp_m13 := any(model).(type) {
	case modelValue:
		booleans := __gp_m13.booleans
		integers := __gp_m13.integers
		reals := __gp_m13.reals
		bitVectors := __gp_m13.bitVectors
		arrays := __gp_m13.arrays
		return evaluateIntegerModelTerm(term, booleans, integers, reals, bitVectors, arrays)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep RealValue(0 c nat, model Model[c], term Term[RealSort]) (Rational, bool)
func RealValue(model Model, term Term[RealSort]) (Rational, bool) {
	switch __gp_m14 := any(model).(type) {
	case modelValue:
		booleans := __gp_m14.booleans
		integers := __gp_m14.integers
		reals := __gp_m14.reals
		return evaluateReal(term, booleans, integers, reals)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep BitVecModelValue(0 c nat, 0 width nat, model Model[c], term Term[BitVecSort[width]]) (BitVectorValue, bool)
func BitVecModelValue(model Model, term Term[BitVecSort]) (BitVectorValue, bool) {
	switch __gp_m15 := any(model).(type) {
	case modelValue:
		integers := __gp_m15.integers
		bitVectors := __gp_m15.bitVectors
		arrays := __gp_m15.bitVectorArrays
		return evaluateBitVectorModelTerm(term, bitVectors, integers, arrays)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep IntegerArrayValue(0 c nat, model Model[c], array Term[ArraySort[IntSort, IntSort]], index IntegerValue) (IntegerValue, bool)
func IntegerArrayValue(model Model, array Term[ArraySort[IntSort, IntSort]], index IntegerValue) (IntegerValue, bool) {
	switch __gp_m16 := any(model).(type) {
	case modelValue:
		integers := __gp_m16.integers
		arrays := __gp_m16.arrays
		return evaluateIntegerArray(array, index, integers, arrays)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep BitVectorArrayValue(0 c nat, 0 indexWidth nat, 0 elementWidth nat, model Model[c], array Term[ArraySort[BitVecSort[indexWidth], BitVecSort[elementWidth]]], index BitVectorValue) (BitVectorValue, bool)
func BitVectorArrayValue(model Model, array Term[ArraySort[BitVecSort, BitVecSort]], index BitVectorValue) (BitVectorValue, bool) {
	switch __gp_m17 := any(model).(type) {
	case modelValue:
		arrays := __gp_m17.bitVectorArrays
		return evaluateBitVectorArray(array, index, arrays)
	default:
		panic("goplus: impossible enum value in match")
	}
}
