// Code generated by goplus from option.gp. DO NOT EDIT.
//goplus:v v0.25.0

// Package option is the presence type of Go+: a value that is there
// (Some) or absent (None). It is authored in Go+ and distributed as
// generated Go — consumers never need the goplus toolchain.
package option

// Option carries at most one value.
//
//goplus:enum Option[T any]
type Option[T any] interface{ isOption(T) }

//goplus:variant (Option[T]) Some(value T)
type Some[T any] struct {
	Value T
}

func (Some[T]) isOption(T) {}

//goplus:variant (Option[T]) None
type None[T any] struct{}

func (None[T]) isOption(T) {}

// OptionCases selects one handler per Option variant for Fold.
type OptionCases[T any, R any] struct {
	Some func(value T) R
	None func() R
}

// Fold reduces Option[T] by one-level case analysis.
func Fold[T any, R any](o Option[T], cs OptionCases[T, R]) R {
	switch m := any(o).(type) {
	case Some[T]:
		return cs.Some(m.Value)
	case None[T]:
		return cs.None()
	default:
		panic("goplus: impossible enum value in Fold")
	}
}

// Of enters from Go's comma-ok shape.
func Of[T any](v T, ok bool) Option[T] {
	if !ok {
		return None[T]{}
	}
	return Some[T]{Value: v}
}

// IsSome reports presence.
//
//goplus:method (Option[T]) IsSome
func IsSome[T any](o Option[T]) bool {
	switch any(o).(type) {
	case Some[T]:

		return true
	case None[T]:

		return false
	default:
		panic("goplus: impossible enum value in match")
	}
}

// IsNone reports absence.
//
//goplus:method (Option[T]) IsNone
func IsNone[T any](o Option[T]) bool {
	switch any(o).(type) {
	case Some[T]:

		return false
	case None[T]:

		return true
	default:
		panic("goplus: impossible enum value in match")
	}
}

// Map lifts a plain function over the value; None passes through.
//
//goplus:method (Option[T]) Map[U]
func Map[T any, U any](o Option[T], f func(T) U) Option[U] {
	switch __gp_m2 := any(o).(type) {
	case Some[T]:
		v := __gp_m2.Value

		return Some[U]{Value: f(v)}
	case None[T]:

		return None[U]{}
	default:
		panic("goplus: impossible enum value in match")
	}
}

// Bind chains an option-producing function; None bypasses it.
//
//goplus:method (Option[T]) Bind[U]
func Bind[T any, U any](o Option[T], f func(T) Option[U]) Option[U] {
	switch __gp_m3 := any(o).(type) {
	case Some[T]:
		v := __gp_m3.Value

		return f(v)
	case None[T]:

		return None[U]{}
	default:
		panic("goplus: impossible enum value in match")
	}
}

// UnwrapOr yields the value or a fallback.
//
//goplus:method (Option[T]) UnwrapOr
func UnwrapOr[T any](o Option[T], fallback T) T {
	switch __gp_m4 := any(o).(type) {
	case Some[T]:
		v := __gp_m4.Value

		return v
	case None[T]:

		return fallback
	default:
		panic("goplus: impossible enum value in match")
	}
}

// OrElse yields the option itself when present, otherwise the
// alternative.
//
//goplus:method (Option[T]) OrElse
func OrElse[T any](o Option[T], alt Option[T]) Option[T] {
	switch any(o).(type) {
	case Some[T]:

		return o
	case None[T]:

		return alt
	default:
		panic("goplus: impossible enum value in match")
	}
}

// Get leaves in Go's comma-ok shape.
//
//goplus:method (Option[T]) Get
func Get[T any](o Option[T]) (T, bool) {
	switch __gp_m6 := any(o).(type) {
	case Some[T]:
		v := __gp_m6.Value

		return v, true
	case None[T]:

		var zero T
		return zero, false
	default:
		panic("goplus: impossible enum value in match")
	}
}
