// Code generated by gpp from guarded.gpp. DO NOT EDIT.
//gpp:v v0.13.0

// Package guarded makes locking discipline structural: a Guarded[T] owns
// both the mutex and the value it protects, so the value is reachable only
// through With/Get — there is no way to touch it outside the lock. The
// convention "fields below mu are guarded by mu" becomes a type.
//
// Authored in G++ and distributed as generated Go — consumers never need
// the gpp toolchain.
package guarded

import "sync"

// Guarded is a mutex-owning cell. The zero value is usable when T's zero
// value is.
type Guarded[T any] struct {
	mu sync.Mutex
	v  T
}

// New constructs a Guarded holding v.
func New[T any](v T) *Guarded[T] {
	return &Guarded[T]{v: v}
}

// With runs f over the value under the lock. f receives a pointer so it can
// mutate in place; the pointer must not escape f.
func (g *Guarded[T]) With(f func(*T)) {
	g.mu.Lock()
	defer g.mu.Unlock()
	f(&g.v)
}

// Get returns a copy of the value taken under the lock.
func (g *Guarded[T]) Get() T {
	g.mu.Lock()
	defer g.mu.Unlock()
	return g.v
}

// Set replaces the value under the lock.
func (g *Guarded[T]) Set(v T) {
	g.mu.Lock()
	defer g.mu.Unlock()
	g.v = v
}

// RWGuarded is Guarded with reader/writer locking: RWith serializes against
// With/Set but not against other RWith calls.
type RWGuarded[T any] struct {
	mu sync.RWMutex
	v  T
}

// NewRW constructs an RWGuarded holding v.
func NewRW[T any](v T) *RWGuarded[T] {
	return &RWGuarded[T]{v: v}
}

// With runs f over the value under the write lock.
func (g *RWGuarded[T]) With(f func(*T)) {
	g.mu.Lock()
	defer g.mu.Unlock()
	f(&g.v)
}

// RWith runs f over the value under the read lock. f must not mutate
// through aliases it retains; the value must be treated as read-only.
func (g *RWGuarded[T]) RWith(f func(T)) {
	g.mu.RLock()
	defer g.mu.RUnlock()
	f(g.v)
}

// Get returns a copy of the value taken under the read lock.
func (g *RWGuarded[T]) Get() T {
	g.mu.RLock()
	defer g.mu.RUnlock()
	return g.v
}

// Set replaces the value under the write lock.
func (g *RWGuarded[T]) Set(v T) {
	g.mu.Lock()
	defer g.mu.Unlock()
	g.v = v
}
