// Code generated by goplus from canonical.gp. DO NOT EDIT.
//goplus:v v0.15.0

// Package canonical defines law-bearing normalization: reducing values to a
// deterministic representative without changing their semantic equivalence.
//
//goplus:laws out=lawtest
package canonical

import "reflect"

// Canonical is a normalizer together with the equivalence relation whose
// classes it represents. Normalize must be idempotent, and two values are
// equivalent exactly when their canonical representatives are structurally
// equal.
//
//goplus:class Canonical[T any]
type Canonical[T any] struct {
	Normalize  func(value T) T
	Equivalent func(a, b T) bool
}

//goplus:law (Canonical[T]) Idempotent(value T)
func (m Canonical[T]) LawIdempotent(value T) bool {
	return reflect.DeepEqual(m.Normalize(m.Normalize(value)), m.Normalize(value))
}

//goplus:law (Canonical[T]) Sound(a, b T)
func (m Canonical[T]) LawSound(a, b T) bool {
	if !reflect.DeepEqual(m.Normalize(a), m.Normalize(b)) {
		return true
	}
	return m.Equivalent(a, b)
}

//goplus:law (Canonical[T]) Complete(a, b T)
func (m Canonical[T]) LawComplete(a, b T) bool {
	if !m.Equivalent(a, b) {
		return true
	}
	return reflect.DeepEqual(m.Normalize(a), m.Normalize(b))
}
