// Code generated by goplus from config.gp. DO NOT EDIT.
//goplus:v v0.25.0

// Package config layers defaults, decoding, and semantic validation while
// retaining field paths in diagnostics.
package config

import (
	"fmt"
	"strings"
)

// Decoder overlays serialized fields onto base. This lets format adapters
// preserve schema defaults without coupling this package to JSON, YAML, etc.
type Decoder[T any] interface{ Decode([]byte, T) (T, error) }
type Validator[T any] interface{ Validate(T) error }
type ValidateFunc[T any] func(T) error

func (f ValidateFunc[T]) Validate(v T) error { return f(v) }

type FieldError struct {
	Path string
	Err  error
}

func (e *FieldError) Error() string {
	if e.Path == "" {
		return e.Err.Error()
	}
	return e.Path + ": " + e.Err.Error()
}
func (e *FieldError) Unwrap() error { return e.Err }
func At(path string, err error) error {
	if err == nil {
		return nil
	}
	return &FieldError{Path: path, Err: err}
}

type Schema[T any] struct {
	Defaults   func() T
	Decoder    Decoder[T]
	Validators []Validator[T]
}

func (s Schema[T]) Load(data []byte) (T, error) {
	var zero T
	if s.Decoder == nil {
		return zero, fmt.Errorf("config: nil decoder")
	}
	base := zero
	if s.Defaults != nil {
		base = s.Defaults()
	}
	v, err := s.Decoder.Decode(data, base)
	if err != nil {
		return zero, err
	}
	for _, validator := range s.Validators {
		if err := validator.Validate(v); err != nil {
			return zero, err
		}
	}
	return v, nil
}

type Errors []error

func (e Errors) Error() string {
	parts := make([]string, 0, len(e))
	for _, err := range e {
		if err != nil {
			parts = append(parts, err.Error())
		}
	}
	return strings.Join(parts, "; ")
}
func Collect(errs ...error) error {
	out := Errors{}
	for _, err := range errs {
		if err != nil {
			out = append(out, err)
		}
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

// Source identifies the winning layer for a resolved value. The declaration
// order is also the precedence order used by Resolve.
//
//goplus:enum Source
type Source interface{ isSource() }

//goplus:variant (Source) DefaultSource()
type DefaultSource struct{}

func (DefaultSource) isSource() {}

//goplus:variant (Source) RemoteSource()
type RemoteSource struct{}

func (RemoteSource) isSource() {}

//goplus:variant (Source) FileSource()
type FileSource struct{}

func (FileSource) isSource() {}

//goplus:variant (Source) EnvironmentSource()
type EnvironmentSource struct{}

func (EnvironmentSource) isSource() {}

//goplus:variant (Source) FlagSource()
type FlagSource struct{}

func (FlagSource) isSource() {}

//goplus:variant (Source) OverrideSource()
type OverrideSource struct{}

func (OverrideSource) isSource() {}

// SourceCases selects one handler per Source variant for SourceFold.
type SourceCases[R any] struct {
	DefaultSource     func() R
	RemoteSource      func() R
	FileSource        func() R
	EnvironmentSource func() R
	FlagSource        func() R
	OverrideSource    func() R
}

// SourceFold reduces Source by one-level case analysis.
func SourceFold[R any](s Source, cs SourceCases[R]) R {
	switch any(s).(type) {
	case DefaultSource:
		return cs.DefaultSource()
	case RemoteSource:
		return cs.RemoteSource()
	case FileSource:
		return cs.FileSource()
	case EnvironmentSource:
		return cs.EnvironmentSource()
	case FlagSource:
		return cs.FlagSource()
	case OverrideSource:
		return cs.OverrideSource()
	default:
		panic("goplus: impossible enum value in SourceFold")
	}
}

// SourceEqOverrides carries optional per-variant hooks for SourceEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type SourceEqOverrides struct {
	DefaultSource     func(x, y DefaultSource) (eq, handled bool)
	RemoteSource      func(x, y RemoteSource) (eq, handled bool)
	FileSource        func(x, y FileSource) (eq, handled bool)
	EnvironmentSource func(x, y EnvironmentSource) (eq, handled bool)
	FlagSource        func(x, y FlagSource) (eq, handled bool)
	OverrideSource    func(x, y OverrideSource) (eq, handled bool)
}

// SourceEqualWith reports structural equality of a and b under ov.
func SourceEqualWith(a, b Source, ov SourceEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case DefaultSource:
		y, ok := any(b).(DefaultSource)
		if !ok {
			return false
		}
		if ov.DefaultSource != nil {
			if eq, handled := ov.DefaultSource(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case RemoteSource:
		y, ok := any(b).(RemoteSource)
		if !ok {
			return false
		}
		if ov.RemoteSource != nil {
			if eq, handled := ov.RemoteSource(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case FileSource:
		y, ok := any(b).(FileSource)
		if !ok {
			return false
		}
		if ov.FileSource != nil {
			if eq, handled := ov.FileSource(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case EnvironmentSource:
		y, ok := any(b).(EnvironmentSource)
		if !ok {
			return false
		}
		if ov.EnvironmentSource != nil {
			if eq, handled := ov.EnvironmentSource(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case FlagSource:
		y, ok := any(b).(FlagSource)
		if !ok {
			return false
		}
		if ov.FlagSource != nil {
			if eq, handled := ov.FlagSource(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case OverrideSource:
		y, ok := any(b).(OverrideSource)
		if !ok {
			return false
		}
		if ov.OverrideSource != nil {
			if eq, handled := ov.OverrideSource(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// SourceEqual reports structural equality of a and b.
func SourceEqual(a, b Source) bool {
	return SourceEqualWith(a, b, SourceEqOverrides{})
}

// Entry retains both the value and its provenance.
type Entry struct {
	Value  any
	Source Source
}

// Layer is one immutable input to resolution. Resolve copies every map, so a
// Snapshot never aliases caller-owned mutable configuration.
type Layer struct {
	Source Source
	Values map[string]any
}

// Snapshot[s] is a resolved immutable configuration for schema s. The schema
// witness is retained for ordinary-Go boundary checks and erased from Go+
// call sites after dependent checking.
//
//goplus:enum Snapshot[s nat]
//goplus:derive off
type Snapshot interface{ isSnapshot() }

//goplus:variant (Snapshot) snapshotValue(Schema int, Entries map[string]Entry) Snapshot[s]
type snapshotValue struct {
	schema  int
	entries map[string]Entry
}

func (snapshotValue) isSnapshot() {}

// Key[T,s] is the only typed way to read T from Snapshot[s]. Independently
// constructed keys from another schema cannot be used with the snapshot.
//
//goplus:enum Key[T any, s nat]
//goplus:derive off
type Key[T any] interface{ isKey(T) }

//goplus:variant (Key[T]) keyValue(Schema int, Name string, Decode func(any) (T, bool)) Key[T, s]
type keyValue[T any] struct {
	schema int
	name   string
	decode func(any) (T, bool)
}

func (keyValue[T]) isKey(T) {}

// Lookup distinguishes missing keys from values of the wrong runtime shape.
//
//goplus:enum Lookup[T any]
type Lookup[T any] interface{ isLookup(T) }

//goplus:variant (Lookup[T]) Missing()
type Missing[T any] struct{}

func (Missing[T]) isLookup(T) {}

//goplus:variant (Lookup[T]) WrongType(Value any, Source Source)
type WrongType[T any] struct {
	Value  any
	Source Source
}

func (WrongType[T]) isLookup(T) {}

//goplus:variant (Lookup[T]) Found(Value T, Source Source)
type Found[T any] struct {
	Value  T
	Source Source
}

func (Found[T]) isLookup(T) {}

// LookupCases selects one handler per Lookup variant for LookupFold.
type LookupCases[T any, R any] struct {
	Missing   func() R
	WrongType func(Value any, Source Source) R
	Found     func(Value T, Source Source) R
}

// LookupFold reduces Lookup[T] by one-level case analysis.
func LookupFold[T any, R any](l Lookup[T], cs LookupCases[T, R]) R {
	switch m := any(l).(type) {
	case Missing[T]:
		return cs.Missing()
	case WrongType[T]:
		return cs.WrongType(m.Value, m.Source)
	case Found[T]:
		return cs.Found(m.Value, m.Source)
	default:
		panic("goplus: impossible enum value in LookupFold")
	}
}

// Present[T,s] is evidence that a particular typed key was present and
// decoded in schema s. It retains the key, value, and originating snapshot.
//
//goplus:enum Present[T any, s nat]
//goplus:derive off
type Present[T any] interface{ isPresent(T) }

//goplus:variant (Present[T]) presentValue(Snapshot Snapshot[s], Key Key[T, s], Value T, Source Source) Present[T, s]
type presentValue[T any] struct {
	snapshot Snapshot
	key      Key[T]
	value    T
	source   Source
}

func (presentValue[T]) isPresent(T) {}

// Requirement makes absence and malformed values explicit while producing a
// proof object on success.
//
//goplus:enum Requirement[T any, s nat]
type Requirement[T any] interface{ isRequirement(T) }

//goplus:variant (Requirement[T]) Available(Present Present[T, s])
type Available[T any] struct {
	Present Present[T]
}

func (Available[T]) isRequirement(T) {}

//goplus:variant (Requirement[T]) RequiredMissing()
type RequiredMissing[T any] struct{}

func (RequiredMissing[T]) isRequirement(T) {}

//goplus:variant (Requirement[T]) RequiredWrongType(Value any, Source Source)
type RequiredWrongType[T any] struct {
	Value  any
	Source Source
}

func (RequiredWrongType[T]) isRequirement(T) {}

// RequirementCases selects one handler per Requirement variant for RequirementFold.
type RequirementCases[T any, R any] struct {
	Available         func(Present Present[T]) R
	RequiredMissing   func() R
	RequiredWrongType func(Value any, Source Source) R
}

// RequirementFold reduces Requirement[T] by one-level case analysis.
func RequirementFold[T any, R any](v Requirement[T], cs RequirementCases[T, R]) R {
	switch m := any(v).(type) {
	case Available[T]:
		return cs.Available(m.Present)
	case RequiredMissing[T]:
		return cs.RequiredMissing()
	case RequiredWrongType[T]:
		return cs.RequiredWrongType(m.Value, m.Source)
	default:
		panic("goplus: impossible enum value in RequirementFold")
	}
}

// Subset[s,sub] is evidence that a named projection from schema s to schema
// sub has been declared. Runtime schema IDs defend the erased Go boundary.
//
//goplus:enum Subset[s nat, sub nat]
//goplus:derive off
type Subset interface{ isSubset() }

//goplus:variant (Subset) subsetValue(SourceSchema int, TargetSchema int, Names []string) Subset[s, sub]
type subsetValue struct {
	sourceSchema int
	targetSchema int
	names        []string
}

func (subsetValue) isSubset() {}

//goplus:dep NewKey[T any](schema nat, name string, decode func(any) (T, bool)) Key[T, schema]
func NewKey[T any](schema int, name string, decode func(any) (T, bool)) Key[T] {
	if schema < 0 {
		panic("config: negative schema ID")
	}
	if name == "" {
		panic("config: empty key")
	}
	if decode == nil {
		panic("config: nil key decoder")
	}
	return keyValue[T]{schema: int(schema), name: strings.ToLower(name), decode: decode}
}

// Resolve deterministically applies layers from lowest to highest precedence.
// Repeated source kinds retain caller order within that precedence level.
//
//goplus:dep Resolve(schema nat, layers ...Layer) Snapshot[schema]
func Resolve(schema int, layers ...Layer) Snapshot {
	if schema < 0 {
		panic("config: negative schema ID")
	}
	entries := make(map[string]Entry)
	sources := []Source{DefaultSource{}, RemoteSource{}, FileSource{}, EnvironmentSource{}, FlagSource{}, OverrideSource{}}
	for _, source := range sources {
		for _, layer := range layers {
			if !SourceEqual(layer.Source, source) {
				continue
			}
			for name, value := range layer.Values {
				entries[strings.ToLower(name)] = Entry{Value: cloneConfigValue(value), Source: source}
			}
		}
	}
	return snapshotValue{schema: int(schema), entries: entries}
}

//goplus:dep Get[T any](0 s nat, snapshot Snapshot[s], key Key[T, s]) Lookup[T]
func Get[T any](snapshot Snapshot, key Key[T]) Lookup[T] {
	switch __gp_m0 := any(snapshot).(type) {
	case snapshotValue:
		schema := __gp_m0.schema
		entries := __gp_m0.entries

		switch __gp_m1 := any(key).(type) {
		case keyValue[T]:
			keySchema := __gp_m1.schema
			name := __gp_m1.name
			decode := __gp_m1.decode

			if schema != keySchema {
				panic("config: key belongs to a different schema")
			}
			entry, ok := entries[name]
			if !ok {
				return Missing[T]{}
			}
			owned := cloneConfigValue(entry.Value)
			value, ok := decode(owned)
			if !ok {
				return WrongType[T]{Value: owned, Source: entry.Source}
			}
			return Found[T]{Value: value, Source: entry.Source}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep Untyped(0 s nat, snapshot Snapshot[s], name string) (Entry, bool)
func Untyped(snapshot Snapshot, name string) (Entry, bool) {
	switch __gp_m2 := any(snapshot).(type) {
	case snapshotValue:
		entries := __gp_m2.entries

		entry, ok := entries[strings.ToLower(name)]
		entry.Value = cloneConfigValue(entry.Value)
		return entry, ok
	default:
		panic("goplus: impossible enum value in match")
	}
}

func cloneConfigValue(value any) any {
	switch x := value.(type) {
	case map[string]any:
		out := make(map[string]any, len(x))
		for key, item := range x {
			out[key] = cloneConfigValue(item)
		}
		return out
	case []any:
		out := make([]any, len(x))
		for i, item := range x {
			out[i] = cloneConfigValue(item)
		}
		return out
	case []string:
		return append([]string(nil), x...)
	case []int:
		return append([]int(nil), x...)
	default:
		return value
	}
}

//goplus:dep Require[T any](0 s nat, snapshot Snapshot[s], key Key[T, s]) Requirement[T, s]
func Require[T any](snapshot Snapshot, key Key[T]) Requirement[T] {
	switch __gp_m3 := any(Get(snapshot, key)).(type) {
	case Missing[T]:
		return RequiredMissing[T]{}
	case WrongType[T]:
		value := __gp_m3.Value
		source := __gp_m3.Source
		return RequiredWrongType[T]{Value: value, Source: source}
	case Found[T]:
		value := __gp_m3.Value
		source := __gp_m3.Source
		return Available[T]{Present: presentValue[T]{snapshot: snapshot, key: key, value: value, source: source}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep RequiredValue[T any](0 s nat, proof Present[T, s]) T
func RequiredValue[T any](proof Present[T]) T {
	switch __gp_m4 := any(proof).(type) {
	case presentValue[T]:
		value := __gp_m4.value
		return value
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep NewSubset(sourceSchema nat, targetSchema nat, names ...string) Subset[sourceSchema, targetSchema]
func NewSubset(sourceSchema int, targetSchema int, names ...string) Subset {
	if sourceSchema < 0 || targetSchema < 0 {
		panic("config: negative schema ID")
	}
	owned := make([]string, len(names))
	for i, name := range names {
		if name == "" {
			panic("config: empty subset key")
		}
		owned[i] = strings.ToLower(name)
	}
	return subsetValue{sourceSchema: int(sourceSchema), targetSchema: int(targetSchema), names: owned}
}

//goplus:dep Project(0 s nat, 0 sub nat, snapshot Snapshot[s], subset Subset[s, sub]) Snapshot[sub]
func Project(snapshot Snapshot, subset Subset) Snapshot {
	switch __gp_m5 := any(snapshot).(type) {
	case snapshotValue:
		schema := __gp_m5.schema
		entries := __gp_m5.entries

		switch __gp_m6 := any(subset).(type) {
		case subsetValue:
			sourceSchema := __gp_m6.sourceSchema
			targetSchema := __gp_m6.targetSchema
			names := __gp_m6.names

			if schema != sourceSchema {
				panic("config: subset belongs to a different source schema")
			}
			projected := make(map[string]Entry)
			for _, name := range names {
				if entry, ok := entries[name]; ok {
					projected[name] = entry
				}
			}
			return snapshotValue{schema: targetSchema, entries: projected}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}
