id = "goplus"
name = "Go+"
description = "Go+ language support: goplus language server and syntax."
version = "0.9.0"
schema_version = 1
authors = ["Matt Laine"]
repository = "https://github.com/brain-fuel/goplus"

[language_servers.gp]
name = "goplus language server"
languages = ["Go+"]

[language_servers.gp.binary]
path = "goplus"
arguments = ["lsp"]
