// Code generated by goplus from deepmap.gp. DO NOT EDIT.
//goplus:v v0.15.0

// Package deepmap is a generic two-level map — the (outer key, inner key) →
// value shape that shows up wherever state is namespaced per owner
// (per-filter metadata, per-tenant settings, per-connection registries).
// Snapshot returns a defensive copy of both levels so callers can iterate
// without holding a reference into the live map; values are shallow-shared.
//
// Not safe for concurrent use; the owner provides synchronization (or wraps
// it in a guarded cell).
//
// Authored in Go+ and distributed as generated Go — consumers never need
// the goplus toolchain.
package deepmap

// Map2 is the two-level map. The zero value is NOT usable; construct with
// New (methods on a nil *Map2 are safe no-ops/zero-values, the guard-free
// call-site affordance).
type Map2[K1 comparable, K2 comparable, V any] struct {
	m map[K1]map[K2]V
}

// New constructs an empty Map2.
func New[K1 comparable, K2 comparable, V any]() *Map2[K1, K2, V] {
	return &Map2[K1, K2, V]{m: make(map[K1]map[K2]V)}
}

// Get returns the value at (k1, k2); ok=false if absent. Nil-receiver
// tolerant: returns the zero value and false.
func (m *Map2[K1, K2, V]) Get(k1 K1, k2 K2) (V, bool) {
	if m == nil || m.m == nil {
		var zero V
		return zero, false
	}
	inner, ok := m.m[k1]
	if !ok {
		var zero V
		return zero, false
	}
	v, ok := inner[k2]
	return v, ok
}

// Set writes the value at (k1, k2), overwriting any prior value and
// auto-initializing the inner map at first write under k1. Nil-receiver
// tolerant: no-op.
func (m *Map2[K1, K2, V]) Set(k1 K1, k2 K2, v V) {
	if m == nil {
		return
	}
	if m.m == nil {
		m.m = make(map[K1]map[K2]V)
	}
	inner, ok := m.m[k1]
	if !ok {
		inner = make(map[K2]V)
		m.m[k1] = inner
	}
	inner[k2] = v
}

// Delete removes the entry at (k1, k2), dropping the inner map when it
// empties. Nil-receiver tolerant: no-op.
func (m *Map2[K1, K2, V]) Delete(k1 K1, k2 K2) {
	if m == nil || m.m == nil {
		return
	}
	inner, ok := m.m[k1]
	if !ok {
		return
	}
	delete(inner, k2)
	if len(inner) == 0 {
		delete(m.m, k1)
	}
}

// Len returns the total number of (k1, k2) entries. Nil-receiver tolerant:
// returns 0.
func (m *Map2[K1, K2, V]) Len() int {
	if m == nil {
		return 0
	}
	n := 0
	for _, inner := range m.m {
		n += len(inner)
	}
	return n
}

// Snapshot returns a defensive copy of the outer + inner maps for
// iteration; mutating the snapshot does not mutate the Map2. Values are
// shallow-shared. Nil-receiver tolerant: returns nil.
func (m *Map2[K1, K2, V]) Snapshot() map[K1]map[K2]V {
	if m == nil || m.m == nil {
		return nil
	}
	out := make(map[K1]map[K2]V, len(m.m))
	for k1, inner := range m.m {
		innerCopy := make(map[K2]V, len(inner))
		for k2, v := range inner {
			innerCopy[k2] = v
		}
		out[k1] = innerCopy
	}
	return out
}

// Reset clears all entries; the Map2 stays usable. Nil-receiver tolerant:
// no-op.
func (m *Map2[K1, K2, V]) Reset() {
	if m == nil {
		return
	}
	m.m = make(map[K1]map[K2]V)
}
