// Code generated by gpp from instances.gpp. DO NOT EDIT.
//gpp:v v0.13.0

package lawtest

import (
	"testing"

	"goforge.dev/gpp/std/algebra"

	"pgregory.net/rapid"
)

func TestIntAddLaws(t *testing.T) {
	t.Run("Group.LeftInverse", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[int]().Draw(rt, "a")
			if !algebra.IntAdd.LawLeftInverse(a) {
				rt.Fatalf("law LeftInverse violated: a=%v", a)
			}
		})
	})
	t.Run("Group.RightInverse", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[int]().Draw(rt, "a")
			if !algebra.IntAdd.LawRightInverse(a) {
				rt.Fatalf("law RightInverse violated: a=%v", a)
			}
		})
	})
	t.Run("Semigroup.Assoc", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[int]().Draw(rt, "a")
			b := rapid.Make[int]().Draw(rt, "b")
			c := rapid.Make[int]().Draw(rt, "c")
			if !algebra.IntAdd.AsSemigroup().LawAssoc(a, b, c) {
				rt.Fatalf("law Assoc violated: a=%v b=%v c=%v", a, b, c)
			}
		})
	})
	t.Run("UnitalMagma.LeftId", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[int]().Draw(rt, "a")
			if !algebra.IntAdd.AsUnitalMagma().LawLeftId(a) {
				rt.Fatalf("law LeftId violated: a=%v", a)
			}
		})
	})
	t.Run("UnitalMagma.RightId", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[int]().Draw(rt, "a")
			if !algebra.IntAdd.AsUnitalMagma().LawRightId(a) {
				rt.Fatalf("law RightId violated: a=%v", a)
			}
		})
	})
	t.Run("Quasigroup.LeftDivCancels", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[int]().Draw(rt, "a")
			b := rapid.Make[int]().Draw(rt, "b")
			if !algebra.IntAdd.AsQuasigroup().LawLeftDivCancels(a, b) {
				rt.Fatalf("law LeftDivCancels violated: a=%v b=%v", a, b)
			}
		})
	})
	t.Run("Quasigroup.RightDivCancels", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[int]().Draw(rt, "a")
			b := rapid.Make[int]().Draw(rt, "b")
			if !algebra.IntAdd.AsQuasigroup().LawRightDivCancels(a, b) {
				rt.Fatalf("law RightDivCancels violated: a=%v b=%v", a, b)
			}
		})
	})
}

func TestIntMulLaws(t *testing.T) {
	t.Run("Semigroup.Assoc", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[int]().Draw(rt, "a")
			b := rapid.Make[int]().Draw(rt, "b")
			c := rapid.Make[int]().Draw(rt, "c")
			if !algebra.IntMul.AsSemigroup().LawAssoc(a, b, c) {
				rt.Fatalf("law Assoc violated: a=%v b=%v c=%v", a, b, c)
			}
		})
	})
	t.Run("UnitalMagma.LeftId", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[int]().Draw(rt, "a")
			if !algebra.IntMul.AsUnitalMagma().LawLeftId(a) {
				rt.Fatalf("law LeftId violated: a=%v", a)
			}
		})
	})
	t.Run("UnitalMagma.RightId", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[int]().Draw(rt, "a")
			if !algebra.IntMul.AsUnitalMagma().LawRightId(a) {
				rt.Fatalf("law RightId violated: a=%v", a)
			}
		})
	})
}

func TestStringConcatLaws(t *testing.T) {
	t.Run("Semigroup.Assoc", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[string]().Draw(rt, "a")
			b := rapid.Make[string]().Draw(rt, "b")
			c := rapid.Make[string]().Draw(rt, "c")
			if !algebra.StringConcat.AsSemigroup().LawAssoc(a, b, c) {
				rt.Fatalf("law Assoc violated: a=%v b=%v c=%v", a, b, c)
			}
		})
	})
	t.Run("UnitalMagma.LeftId", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[string]().Draw(rt, "a")
			if !algebra.StringConcat.AsUnitalMagma().LawLeftId(a) {
				rt.Fatalf("law LeftId violated: a=%v", a)
			}
		})
	})
	t.Run("UnitalMagma.RightId", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[string]().Draw(rt, "a")
			if !algebra.StringConcat.AsUnitalMagma().LawRightId(a) {
				rt.Fatalf("law RightId violated: a=%v", a)
			}
		})
	})
}

func TestBoolAndLaws(t *testing.T) {
	t.Run("Semigroup.Assoc", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[bool]().Draw(rt, "a")
			b := rapid.Make[bool]().Draw(rt, "b")
			c := rapid.Make[bool]().Draw(rt, "c")
			if !algebra.BoolAnd.AsSemigroup().LawAssoc(a, b, c) {
				rt.Fatalf("law Assoc violated: a=%v b=%v c=%v", a, b, c)
			}
		})
	})
	t.Run("UnitalMagma.LeftId", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[bool]().Draw(rt, "a")
			if !algebra.BoolAnd.AsUnitalMagma().LawLeftId(a) {
				rt.Fatalf("law LeftId violated: a=%v", a)
			}
		})
	})
	t.Run("UnitalMagma.RightId", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[bool]().Draw(rt, "a")
			if !algebra.BoolAnd.AsUnitalMagma().LawRightId(a) {
				rt.Fatalf("law RightId violated: a=%v", a)
			}
		})
	})
}

func TestBoolOrLaws(t *testing.T) {
	t.Run("Semigroup.Assoc", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[bool]().Draw(rt, "a")
			b := rapid.Make[bool]().Draw(rt, "b")
			c := rapid.Make[bool]().Draw(rt, "c")
			if !algebra.BoolOr.AsSemigroup().LawAssoc(a, b, c) {
				rt.Fatalf("law Assoc violated: a=%v b=%v c=%v", a, b, c)
			}
		})
	})
	t.Run("UnitalMagma.LeftId", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[bool]().Draw(rt, "a")
			if !algebra.BoolOr.AsUnitalMagma().LawLeftId(a) {
				rt.Fatalf("law LeftId violated: a=%v", a)
			}
		})
	})
	t.Run("UnitalMagma.RightId", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[bool]().Draw(rt, "a")
			if !algebra.BoolOr.AsUnitalMagma().LawRightId(a) {
				rt.Fatalf("law RightId violated: a=%v", a)
			}
		})
	})
}

func TestSliceConcatLaws(t *testing.T) {
	t.Run("Semigroup.Assoc[int]", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[[]int]().Draw(rt, "a")
			b := rapid.Make[[]int]().Draw(rt, "b")
			c := rapid.Make[[]int]().Draw(rt, "c")
			if !algebra.SliceConcat[int]().AsSemigroup().LawAssoc(a, b, c) {
				rt.Fatalf("law Assoc violated: a=%v b=%v c=%v", a, b, c)
			}
		})
	})
	t.Run("UnitalMagma.LeftId[int]", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[[]int]().Draw(rt, "a")
			if !algebra.SliceConcat[int]().AsUnitalMagma().LawLeftId(a) {
				rt.Fatalf("law LeftId violated: a=%v", a)
			}
		})
	})
	t.Run("UnitalMagma.RightId[int]", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[[]int]().Draw(rt, "a")
			if !algebra.SliceConcat[int]().AsUnitalMagma().LawRightId(a) {
				rt.Fatalf("law RightId violated: a=%v", a)
			}
		})
	})
	t.Run("Semigroup.Assoc[string]", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[[]string]().Draw(rt, "a")
			b := rapid.Make[[]string]().Draw(rt, "b")
			c := rapid.Make[[]string]().Draw(rt, "c")
			if !algebra.SliceConcat[string]().AsSemigroup().LawAssoc(a, b, c) {
				rt.Fatalf("law Assoc violated: a=%v b=%v c=%v", a, b, c)
			}
		})
	})
	t.Run("UnitalMagma.LeftId[string]", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[[]string]().Draw(rt, "a")
			if !algebra.SliceConcat[string]().AsUnitalMagma().LawLeftId(a) {
				rt.Fatalf("law LeftId violated: a=%v", a)
			}
		})
	})
	t.Run("UnitalMagma.RightId[string]", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[[]string]().Draw(rt, "a")
			if !algebra.SliceConcat[string]().AsUnitalMagma().LawRightId(a) {
				rt.Fatalf("law RightId violated: a=%v", a)
			}
		})
	})
}

func TestMinIntLaws(t *testing.T) {
	t.Run("Semigroup.Assoc", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[int]().Draw(rt, "a")
			b := rapid.Make[int]().Draw(rt, "b")
			c := rapid.Make[int]().Draw(rt, "c")
			if !algebra.MinInt.LawAssoc(a, b, c) {
				rt.Fatalf("law Assoc violated: a=%v b=%v c=%v", a, b, c)
			}
		})
	})
}

func TestMaxIntLaws(t *testing.T) {
	t.Run("Semigroup.Assoc", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[int]().Draw(rt, "a")
			b := rapid.Make[int]().Draw(rt, "b")
			c := rapid.Make[int]().Draw(rt, "c")
			if !algebra.MaxInt.LawAssoc(a, b, c) {
				rt.Fatalf("law Assoc violated: a=%v b=%v c=%v", a, b, c)
			}
		})
	})
}
