// Code generated by goplus from protocol.gp. DO NOT EDIT.
//goplus:v v0.23.0

// Package websocket implements RFC 6455 WebSocket framing and transport.
// The semantic layer is authored in Go+; hot framing paths remain small,
// allocation-free Go functions so both Go+ and Go callers get the same wire.
package websocket

import "sync/atomic"

// Message is the complete application/control message vocabulary.
//
//goplus:enum Message
//goplus:derive off
type Message interface{ isMessage() }

//goplus:variant (Message) TextMessage(payload []byte)
type TextMessage struct {
	Payload []byte
}

func (TextMessage) isMessage() {}

//goplus:variant (Message) BinaryMessage(payload []byte)
type BinaryMessage struct {
	Payload []byte
}

func (BinaryMessage) isMessage() {}

//goplus:variant (Message) PingMessage(payload []byte)
type PingMessage struct {
	Payload []byte
}

func (PingMessage) isMessage() {}

//goplus:variant (Message) PongMessage(payload []byte)
type PongMessage struct {
	Payload []byte
}

func (PongMessage) isMessage() {}

//goplus:variant (Message) CloseMessage(code CloseCode, reason string)
type CloseMessage struct {
	Code   CloseCode
	Reason string
}

func (CloseMessage) isMessage() {}

// Failure classifies protocol failure without string matching.
//
//goplus:enum Failure
type Failure interface{ isFailure() }

//goplus:variant (Failure) NeedMoreData
type NeedMoreData struct{}

func (NeedMoreData) isFailure() {}

//goplus:variant (Failure) InvalidOpcode(opcode byte)
type InvalidOpcode struct {
	Opcode byte
}

func (InvalidOpcode) isFailure() {}

//goplus:variant (Failure) ReservedBits(bits byte)
type ReservedBits struct {
	Bits byte
}

func (ReservedBits) isFailure() {}

//goplus:variant (Failure) WrongMask(expectMasked bool)
type WrongMask struct {
	ExpectMasked bool
}

func (WrongMask) isFailure() {}

//goplus:variant (Failure) NonCanonicalLength
type NonCanonicalLength struct{}

func (NonCanonicalLength) isFailure() {}

//goplus:variant (Failure) ControlFragmented
type ControlFragmented struct{}

func (ControlFragmented) isFailure() {}

//goplus:variant (Failure) ControlTooLarge
type ControlTooLarge struct{}

func (ControlTooLarge) isFailure() {}

//goplus:variant (Failure) UnexpectedContinuation
type UnexpectedContinuation struct{}

func (UnexpectedContinuation) isFailure() {}

//goplus:variant (Failure) ExpectedContinuation
type ExpectedContinuation struct{}

func (ExpectedContinuation) isFailure() {}

//goplus:variant (Failure) InvalidUTF8
type InvalidUTF8 struct{}

func (InvalidUTF8) isFailure() {}

//goplus:variant (Failure) InvalidClosePayload
type InvalidClosePayload struct{}

func (InvalidClosePayload) isFailure() {}

//goplus:variant (Failure) InvalidCloseCode(code CloseCode)
type InvalidCloseCode struct {
	Code CloseCode
}

func (InvalidCloseCode) isFailure() {}

//goplus:variant (Failure) MessageTooLarge(limit int64)
type MessageTooLarge struct {
	Limit int64
}

func (MessageTooLarge) isFailure() {}

//goplus:variant (Failure) HandshakeRejected(status int, reason string)
type HandshakeRejected struct {
	Status int
	Reason string
}

func (HandshakeRejected) isFailure() {}

//goplus:variant (Failure) TransportFailed(err error)
type TransportFailed struct {
	Err error
}

func (TransportFailed) isFailure() {}

// FailureCases selects one handler per Failure variant for FailureFold.
type FailureCases[R any] struct {
	NeedMoreData           func() R
	InvalidOpcode          func(opcode byte) R
	ReservedBits           func(bits byte) R
	WrongMask              func(expectMasked bool) R
	NonCanonicalLength     func() R
	ControlFragmented      func() R
	ControlTooLarge        func() R
	UnexpectedContinuation func() R
	ExpectedContinuation   func() R
	InvalidUTF8            func() R
	InvalidClosePayload    func() R
	InvalidCloseCode       func(code CloseCode) R
	MessageTooLarge        func(limit int64) R
	HandshakeRejected      func(status int, reason string) R
	TransportFailed        func(err error) R
}

// FailureFold reduces Failure by one-level case analysis.
func FailureFold[R any](f Failure, cs FailureCases[R]) R {
	switch m := any(f).(type) {
	case NeedMoreData:
		return cs.NeedMoreData()
	case InvalidOpcode:
		return cs.InvalidOpcode(m.Opcode)
	case ReservedBits:
		return cs.ReservedBits(m.Bits)
	case WrongMask:
		return cs.WrongMask(m.ExpectMasked)
	case NonCanonicalLength:
		return cs.NonCanonicalLength()
	case ControlFragmented:
		return cs.ControlFragmented()
	case ControlTooLarge:
		return cs.ControlTooLarge()
	case UnexpectedContinuation:
		return cs.UnexpectedContinuation()
	case ExpectedContinuation:
		return cs.ExpectedContinuation()
	case InvalidUTF8:
		return cs.InvalidUTF8()
	case InvalidClosePayload:
		return cs.InvalidClosePayload()
	case InvalidCloseCode:
		return cs.InvalidCloseCode(m.Code)
	case MessageTooLarge:
		return cs.MessageTooLarge(m.Limit)
	case HandshakeRejected:
		return cs.HandshakeRejected(m.Status, m.Reason)
	case TransportFailed:
		return cs.TransportFailed(m.Err)
	default:
		panic("goplus: impossible enum value in FailureFold")
	}
}

// FailureEqOverrides carries optional per-variant hooks for FailureEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type FailureEqOverrides struct {
	NeedMoreData           func(x, y NeedMoreData) (eq, handled bool)
	InvalidOpcode          func(x, y InvalidOpcode) (eq, handled bool)
	ReservedBits           func(x, y ReservedBits) (eq, handled bool)
	WrongMask              func(x, y WrongMask) (eq, handled bool)
	NonCanonicalLength     func(x, y NonCanonicalLength) (eq, handled bool)
	ControlFragmented      func(x, y ControlFragmented) (eq, handled bool)
	ControlTooLarge        func(x, y ControlTooLarge) (eq, handled bool)
	UnexpectedContinuation func(x, y UnexpectedContinuation) (eq, handled bool)
	ExpectedContinuation   func(x, y ExpectedContinuation) (eq, handled bool)
	InvalidUTF8            func(x, y InvalidUTF8) (eq, handled bool)
	InvalidClosePayload    func(x, y InvalidClosePayload) (eq, handled bool)
	InvalidCloseCode       func(x, y InvalidCloseCode) (eq, handled bool)
	MessageTooLarge        func(x, y MessageTooLarge) (eq, handled bool)
	HandshakeRejected      func(x, y HandshakeRejected) (eq, handled bool)
	TransportFailed        func(x, y TransportFailed) (eq, handled bool)
}

// FailureEqualWith reports structural equality of a and b under ov.
func FailureEqualWith(a, b Failure, ov FailureEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case NeedMoreData:
		y, ok := any(b).(NeedMoreData)
		if !ok {
			return false
		}
		if ov.NeedMoreData != nil {
			if eq, handled := ov.NeedMoreData(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case InvalidOpcode:
		y, ok := any(b).(InvalidOpcode)
		if !ok {
			return false
		}
		if ov.InvalidOpcode != nil {
			if eq, handled := ov.InvalidOpcode(x, y); handled {
				return eq
			}
		}
		if x.Opcode != y.Opcode {
			return false
		}
		return true
	case ReservedBits:
		y, ok := any(b).(ReservedBits)
		if !ok {
			return false
		}
		if ov.ReservedBits != nil {
			if eq, handled := ov.ReservedBits(x, y); handled {
				return eq
			}
		}
		if x.Bits != y.Bits {
			return false
		}
		return true
	case WrongMask:
		y, ok := any(b).(WrongMask)
		if !ok {
			return false
		}
		if ov.WrongMask != nil {
			if eq, handled := ov.WrongMask(x, y); handled {
				return eq
			}
		}
		if x.ExpectMasked != y.ExpectMasked {
			return false
		}
		return true
	case NonCanonicalLength:
		y, ok := any(b).(NonCanonicalLength)
		if !ok {
			return false
		}
		if ov.NonCanonicalLength != nil {
			if eq, handled := ov.NonCanonicalLength(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ControlFragmented:
		y, ok := any(b).(ControlFragmented)
		if !ok {
			return false
		}
		if ov.ControlFragmented != nil {
			if eq, handled := ov.ControlFragmented(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ControlTooLarge:
		y, ok := any(b).(ControlTooLarge)
		if !ok {
			return false
		}
		if ov.ControlTooLarge != nil {
			if eq, handled := ov.ControlTooLarge(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case UnexpectedContinuation:
		y, ok := any(b).(UnexpectedContinuation)
		if !ok {
			return false
		}
		if ov.UnexpectedContinuation != nil {
			if eq, handled := ov.UnexpectedContinuation(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ExpectedContinuation:
		y, ok := any(b).(ExpectedContinuation)
		if !ok {
			return false
		}
		if ov.ExpectedContinuation != nil {
			if eq, handled := ov.ExpectedContinuation(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case InvalidUTF8:
		y, ok := any(b).(InvalidUTF8)
		if !ok {
			return false
		}
		if ov.InvalidUTF8 != nil {
			if eq, handled := ov.InvalidUTF8(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case InvalidClosePayload:
		y, ok := any(b).(InvalidClosePayload)
		if !ok {
			return false
		}
		if ov.InvalidClosePayload != nil {
			if eq, handled := ov.InvalidClosePayload(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case InvalidCloseCode:
		y, ok := any(b).(InvalidCloseCode)
		if !ok {
			return false
		}
		if ov.InvalidCloseCode != nil {
			if eq, handled := ov.InvalidCloseCode(x, y); handled {
				return eq
			}
		}
		if x.Code != y.Code {
			return false
		}
		return true
	case MessageTooLarge:
		y, ok := any(b).(MessageTooLarge)
		if !ok {
			return false
		}
		if ov.MessageTooLarge != nil {
			if eq, handled := ov.MessageTooLarge(x, y); handled {
				return eq
			}
		}
		if x.Limit != y.Limit {
			return false
		}
		return true
	case HandshakeRejected:
		y, ok := any(b).(HandshakeRejected)
		if !ok {
			return false
		}
		if ov.HandshakeRejected != nil {
			if eq, handled := ov.HandshakeRejected(x, y); handled {
				return eq
			}
		}
		if x.Status != y.Status {
			return false
		}
		if x.Reason != y.Reason {
			return false
		}
		return true
	case TransportFailed:
		y, ok := any(b).(TransportFailed)
		if !ok {
			return false
		}
		if ov.TransportFailed != nil {
			if eq, handled := ov.TransportFailed(x, y); handled {
				return eq
			}
		}
		if (x.Err == nil) != (y.Err == nil) {
			return false
		}
		if x.Err != nil && x.Err.Error() != y.Err.Error() {
			return false
		}
		return true
	}
	return false
}

// FailureEqual reports structural equality of a and b.
func FailureEqual(a, b Failure) bool {
	return FailureEqualWith(a, b, FailureEqOverrides{})
}

// Phase indexes the protocol transitions that are valid for a connection.
//
//goplus:enum Phase
type Phase interface{ isPhase() }

//goplus:variant (Phase) ConnectingPhase
type ConnectingPhase struct{}

func (ConnectingPhase) isPhase() {}

//goplus:variant (Phase) OpenPhase
type OpenPhase struct{}

func (OpenPhase) isPhase() {}

//goplus:variant (Phase) CloseSentPhase
type CloseSentPhase struct{}

func (CloseSentPhase) isPhase() {}

//goplus:variant (Phase) CloseReceivedPhase
type CloseReceivedPhase struct{}

func (CloseReceivedPhase) isPhase() {}

//goplus:variant (Phase) ClosedPhase
type ClosedPhase struct{}

func (ClosedPhase) isPhase() {}

// PhaseCases selects one handler per Phase variant for PhaseFold.
type PhaseCases[R any] struct {
	ConnectingPhase    func() R
	OpenPhase          func() R
	CloseSentPhase     func() R
	CloseReceivedPhase func() R
	ClosedPhase        func() R
}

// PhaseFold reduces Phase by one-level case analysis.
func PhaseFold[R any](p Phase, cs PhaseCases[R]) R {
	switch any(p).(type) {
	case ConnectingPhase:
		return cs.ConnectingPhase()
	case OpenPhase:
		return cs.OpenPhase()
	case CloseSentPhase:
		return cs.CloseSentPhase()
	case CloseReceivedPhase:
		return cs.CloseReceivedPhase()
	case ClosedPhase:
		return cs.ClosedPhase()
	default:
		panic("goplus: impossible enum value in PhaseFold")
	}
}

// PhaseEqOverrides carries optional per-variant hooks for PhaseEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type PhaseEqOverrides struct {
	ConnectingPhase    func(x, y ConnectingPhase) (eq, handled bool)
	OpenPhase          func(x, y OpenPhase) (eq, handled bool)
	CloseSentPhase     func(x, y CloseSentPhase) (eq, handled bool)
	CloseReceivedPhase func(x, y CloseReceivedPhase) (eq, handled bool)
	ClosedPhase        func(x, y ClosedPhase) (eq, handled bool)
}

// PhaseEqualWith reports structural equality of a and b under ov.
func PhaseEqualWith(a, b Phase, ov PhaseEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case ConnectingPhase:
		y, ok := any(b).(ConnectingPhase)
		if !ok {
			return false
		}
		if ov.ConnectingPhase != nil {
			if eq, handled := ov.ConnectingPhase(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case OpenPhase:
		y, ok := any(b).(OpenPhase)
		if !ok {
			return false
		}
		if ov.OpenPhase != nil {
			if eq, handled := ov.OpenPhase(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case CloseSentPhase:
		y, ok := any(b).(CloseSentPhase)
		if !ok {
			return false
		}
		if ov.CloseSentPhase != nil {
			if eq, handled := ov.CloseSentPhase(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case CloseReceivedPhase:
		y, ok := any(b).(CloseReceivedPhase)
		if !ok {
			return false
		}
		if ov.CloseReceivedPhase != nil {
			if eq, handled := ov.CloseReceivedPhase(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ClosedPhase:
		y, ok := any(b).(ClosedPhase)
		if !ok {
			return false
		}
		if ov.ClosedPhase != nil {
			if eq, handled := ov.ClosedPhase(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// PhaseEqual reports structural equality of a and b.
func PhaseEqual(a, b Phase) bool {
	return PhaseEqualWith(a, b, PhaseEqOverrides{})
}

// Session is the lightweight proof-token API retained for v0.18
// compatibility. New Go+ orchestration should prefer Capability, which also
// carries linear connection ownership.
//
//goplus:enum Session[p Phase]
//goplus:derive off
type Session interface{ isSession() }

//goplus:variant (Session) ConnectingSession() Session[ConnectingPhase]
type ConnectingSession struct{}

func (ConnectingSession) isSession() {}

//goplus:variant (Session) OpenSession() Session[OpenPhase]
type OpenSession struct{}

func (OpenSession) isSession() {}

//goplus:variant (Session) CloseSentSession() Session[CloseSentPhase]
type CloseSentSession struct{}

func (CloseSentSession) isSession() {}

//goplus:variant (Session) CloseReceivedSession() Session[CloseReceivedPhase]
type CloseReceivedSession struct{}

func (CloseReceivedSession) isSession() {}

//goplus:variant (Session) ClosedSession() Session[ClosedPhase]
type ClosedSession struct{}

func (ClosedSession) isSession() {}

func Open(_ Session) Session           { return OpenSession{} }
func SentClose(_ Session) Session      { return CloseSentSession{} }
func ReceivedClose(_ Session) Session  { return CloseReceivedSession{} }
func FinishSent(_ Session) Session     { return ClosedSession{} }
func FinishReceived(_ Session) Session { return ClosedSession{} }

// Capability is the Go+ ownership-oriented API. Go callers that do not want
// typestate use Conn directly.
//
//goplus:enum Capability[p Phase]
type Capability interface{ isCapability() }

//goplus:variant (Capability) OpenCapability(conn *Conn) Capability[OpenPhase]
type OpenCapability struct {
	Conn *Conn
}

func (OpenCapability) isCapability() {}

//goplus:variant (Capability) CloseSentCapability(conn *Conn) Capability[CloseSentPhase]
type CloseSentCapability struct {
	Conn *Conn
}

func (CloseSentCapability) isCapability() {}

//goplus:variant (Capability) ClosedCapability(conn *Conn) Capability[ClosedPhase]
type ClosedCapability struct {
	Conn *Conn
}

func (ClosedCapability) isCapability() {}

// CapabilityCases selects one handler per Capability variant for CapabilityFold.
type CapabilityCases[R any] struct {
	OpenCapability      func(conn *Conn) R
	CloseSentCapability func(conn *Conn) R
	ClosedCapability    func(conn *Conn) R
}

// CapabilityFold reduces Capability by one-level case analysis.
func CapabilityFold[R any](v Capability, cs CapabilityCases[R]) R {
	switch m := any(v).(type) {
	case OpenCapability:
		return cs.OpenCapability(m.Conn)
	case CloseSentCapability:
		return cs.CloseSentCapability(m.Conn)
	case ClosedCapability:
		return cs.ClosedCapability(m.Conn)
	default:
		panic("goplus: impossible enum value in CapabilityFold")
	}
}

// CloseAttempt preserves ownership on both the success and failure paths.
//
//goplus:enum CloseAttempt
//goplus:derive off
type CloseAttempt interface{ isCloseAttempt() }

//goplus:variant (CloseAttempt) CloseStarted(capability Capability[CloseSentPhase])
type CloseStarted struct {
	Capability Capability
}

func (CloseStarted) isCloseAttempt() {}

//goplus:variant (CloseAttempt) CloseFailed(capability Capability[OpenPhase], err error)
type CloseFailed struct {
	Capability Capability
	Err        error
}

func (CloseFailed) isCloseAttempt() {}

// Send consumes and returns the open capability, preventing concurrent or
// accidental duplicated ownership in Go+ orchestration.
//
//goplus:dep Send(1 capability Capability[OpenPhase], message Message) (Capability[OpenPhase], error)
func Send(capability Lin[Capability], message Message) (Capability, error) {
	if _, ok := any(capability.peek()).(CloseSentCapability); ok {
		panic("goplus: Send: capability with index OpenPhase cannot be CloseSentCapability")
	}
	if _, ok := any(capability.peek()).(ClosedCapability); ok {
		panic("goplus: Send: capability with index OpenPhase cannot be ClosedCapability")
	}
	conn := capabilityConn(capability.Use())
	err := conn.WriteMessage(message)
	return OpenCapability{Conn: conn}, err
}

//goplus:dep BeginClose(1 capability Capability[OpenPhase], code CloseCode, reason string) CloseAttempt
func BeginClose(capability Lin[Capability], code CloseCode, reason string) CloseAttempt {
	if _, ok := any(capability.peek()).(CloseSentCapability); ok {
		panic("goplus: BeginClose: capability with index OpenPhase cannot be CloseSentCapability")
	}
	if _, ok := any(capability.peek()).(ClosedCapability); ok {
		panic("goplus: BeginClose: capability with index OpenPhase cannot be ClosedCapability")
	}
	conn := capabilityConn(capability.Use())
	err := conn.WriteClose(code, reason)
	if err != nil {
		return CloseFailed{Capability: OpenCapability{Conn: conn}, Err: err}
	}
	return CloseStarted{Capability: CloseSentCapability{Conn: conn}}
}

//goplus:dep FinishClose(1 capability Capability[CloseSentPhase]) (Capability[ClosedPhase], error)
func FinishClose(capability Lin[Capability]) (Capability, error) {
	if _, ok := any(capability.peek()).(OpenCapability); ok {
		panic("goplus: FinishClose: capability with index CloseSentPhase cannot be OpenCapability")
	}
	if _, ok := any(capability.peek()).(ClosedCapability); ok {
		panic("goplus: FinishClose: capability with index CloseSentPhase cannot be ClosedCapability")
	}
	conn := capabilityConn(capability.Use())
	err := conn.Close()
	return ClosedCapability{Conn: conn}, err
}

// Lin carries a linear (use-exactly-once) value across the erased
// boundary; Use panics on reuse.
//
//goplus:once
type Lin[T any] struct {
	v     T
	taken *atomic.Bool
}

// LinOf wraps a value for a linear parameter.
func LinOf[T any](v T) Lin[T] { return Lin[T]{v: v, taken: new(atomic.Bool)} }

// peek supports generated runtime index guards without consuming the cell.
func (c Lin[T]) peek() T { return c.v }

// Use consumes the value; a second Use panics.
func (c Lin[T]) Use() T {
	if !c.taken.CompareAndSwap(false, true) {
		panic("goplus: linear value used more than once")
	}
	return c.v
}
