// Code generated by goplus from validate.gp. DO NOT EDIT.
//goplus:v v0.25.0

// Package validate provides typed, composable validation rules whose
// predicates survive successful validation as erased dependent indices.
package validate

import "strings"

// Predicate is first-order index data. Named identifies an atomic proposition;
// Both is an ordered, collision-free conjunction.
//
//goplus:enum Predicate
//goplus:derive off
type Predicate interface{ isPredicate() }

//goplus:variant (Predicate) Named(ID int)
type Named struct {
	ID int
}

func (Named) isPredicate() {}

//goplus:variant (Predicate) Both(Left Predicate, Right Predicate)
type Both struct {
	Left  Predicate
	Right Predicate
}

func (Both) isPredicate() {}

// PredicateAtomID and PredicateBothID form a disjoint, collision-free natural
// encoding: atoms are even and ordered conjunctions are odd Cantor pairs
// (multiplied by two to avoid division).
//
//goplus:total PredicateAtomID(id nat) nat
func PredicateAtomID(id int) int { return id * 2 }

//goplus:total PredicateBothID(left nat, right nat) nat
func PredicateBothID(left int, right int) int {
	return ((left+right)*(left+right+1)+right)*2 + 1
}

// Failure describes one failed atomic rule. Path uses dotted Go/JSON field
// notation and Code/Param retain machine-readable validation semantics.
type Failure struct {
	Path  string
	Code  string
	Param string
}

func (f Failure) Error() string {
	message := f.Code
	if f.Param != "" {
		message += "=" + f.Param
	}
	if f.Path == "" {
		return message
	}
	return f.Path + ": " + message
}

// Failures is stable in rule declaration order.
type Failures []Failure

func (failures Failures) Error() string {
	parts := make([]string, len(failures))
	for i, failure := range failures {
		parts[i] = failure.Error()
	}
	return strings.Join(parts, "; ")
}

type runner[T any] func(value T, path string, failures Failures) Failures

// Rule is an immutable executable witness for predicate p.
//
//goplus:enum Rule[T any, p nat]
//goplus:derive off
type Rule[T any] interface{ isRule(T) }

//goplus:variant (Rule[T]) ruleValue(Predicate Predicate, Run runner[T]) Rule[T, p]
type ruleValue[T any] struct {
	predicate Predicate
	run       runner[T]
}

func (ruleValue[T]) isRule(T) {}

// Validated can only be constructed by this package after a rule succeeds.
//
//goplus:enum Validated[T any, p nat]
//goplus:derive off
type Validated[T any] interface{ isValidated(T) }

//goplus:variant (Validated[T]) validatedValue(Predicate Predicate, Value T, Rule Rule[T, p]) Validated[T, p]
type validatedValue[T any] struct {
	predicate Predicate
	value     T
	rule      Rule[T]
}

func (validatedValue[T]) isValidated(T) {}

// Outcome forces callers to handle validation failure explicitly.
//
//goplus:enum Outcome[T any, p nat]
//goplus:derive off
type Outcome[T any] interface{ isOutcome(T) }

//goplus:variant (Outcome[T]) Accepted(Value Validated[T, p])
type Accepted[T any] struct {
	Value Validated[T]
}

func (Accepted[T]) isOutcome(T) {}

//goplus:variant (Outcome[T]) Rejected(Failures Failures)
type Rejected[T any] struct {
	Failures Failures
}

func (Rejected[T]) isOutcome(T) {}

// Path is a typed field projection used to attach precise failure namespaces.
type Path[T any, V any] struct {
	Name string
	Get  func(T) V
}

//goplus:dep makeRule[T any](0 p nat, predicate Predicate, run runner[T]) Rule[T, p]
func makeRule[T any](predicate Predicate, run runner[T]) Rule[T] {
	return ruleValue[T]{predicate: predicate, run: run}
}

func Field[T any, V any](name string, get func(T) V) Path[T, V] {
	if name == "" {
		panic("validate: empty field path")
	}
	if get == nil {
		panic("validate: nil field projection")
	}
	return Path[T, V]{Name: name, Get: get}
}

func joinPath(prefix string, field string) string {
	if prefix == "" {
		return field
	}
	if field == "" {
		return prefix
	}
	return prefix + "." + field
}

// Atom constructs an atomic predicate. IDs are application-owned stable
// non-negative integers and become part of the dependent result index.
//
//goplus:dep Atom[T any](id nat, code string, param string, check func(T) bool) Rule[T, PredicateAtomID(id)]
func Atom[T any](id int, code string, param string, check func(T) bool) Rule[T] {
	if id < 0 {
		panic("validate: negative predicate ID")
	}
	if code == "" {
		panic("validate: empty rule code")
	}
	if check == nil {
		panic("validate: nil rule check")
	}
	predicate := Named{ID: int(id)}
	run := func(value T, path string, failures Failures) Failures {
		if check(value) {
			return failures
		}
		return append(failures, Failure{Path: path, Code: code, Param: param})
	}
	return makeRule(predicate, run)
}

// At lifts a value rule through a typed field projection without changing its
// proposition.
//
//goplus:dep At[T any, V any](0 p nat, path Path[T, V], rule Rule[V, p]) Rule[T, p]
func At[T any, V any](path Path[T, V], rule Rule[V]) Rule[T] {
	switch __gp_m0 := any(rule).(type) {
	case ruleValue[V]:
		predicate := __gp_m0.predicate
		run := __gp_m0.run

		lifted := func(value T, prefix string, failures Failures) Failures {
			return run(path.Get(value), joinPath(prefix, path.Name), failures)
		}
		return ruleValue[T]{predicate: predicate, run: lifted}
	default:
		panic("goplus: impossible enum value in match")
	}
}

// And forms conjunction and evaluates both sides in declaration order.
//
//goplus:dep And[T any](0 p nat, 0 q nat, left Rule[T, p], right Rule[T, q]) Rule[T, PredicateBothID(p, q)]
func And[T any](left Rule[T], right Rule[T]) Rule[T] {
	switch __gp_m1 := any(left).(type) {
	case ruleValue[T]:
		leftPredicate := __gp_m1.predicate
		leftRun := __gp_m1.run

		switch __gp_m2 := any(right).(type) {
		case ruleValue[T]:
			rightPredicate := __gp_m2.predicate
			rightRun := __gp_m2.run

			run := func(value T, path string, failures Failures) Failures {
				failures = leftRun(value, path, failures)
				return rightRun(value, path, failures)
			}
			return makeRule(Both{Left: leftPredicate, Right: rightPredicate}, run)
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

// Validate executes rule and seals successful values with predicate p.
//
//goplus:dep Validate[T any](0 p nat, rule Rule[T, p], value T) Outcome[T, p]
func Validate[T any](rule Rule[T], value T) Outcome[T] {
	switch __gp_m3 := any(rule).(type) {
	case ruleValue[T]:
		predicate := __gp_m3.predicate
		run := __gp_m3.run

		failures := run(value, "", nil)
		if len(failures) != 0 {
			return Rejected[T]{Failures: failures}
		}
		return Accepted[T]{Value: validatedValue[T]{predicate: predicate, value: value, rule: rule}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

// Check is the direct diagnostic boundary analogous to tag validators' error
// return. Success returns nil without constructing a proof-bearing Outcome.
//
//goplus:dep Check[T any](0 p nat, rule Rule[T, p], value T) Failures
func Check[T any](rule Rule[T], value T) Failures {
	switch __gp_m4 := any(rule).(type) {
	case ruleValue[T]:
		run := __gp_m4.run

		return run(value, "", nil)
	default:
		panic("goplus: impossible enum value in match")
	}
}

// IsValid is the allocation-free boolean boundary for callers that do not need
// a witness or structured failures.
//
//goplus:dep IsValid[T any](0 p nat, rule Rule[T, p], value T) bool
func IsValid[T any](rule Rule[T], value T) bool {
	switch __gp_m5 := any(rule).(type) {
	case ruleValue[T]:
		run := __gp_m5.run

		return len(run(value, "", nil)) == 0
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep Value[T any](0 p nat, value Validated[T, p]) T
func Value[T any](value Validated[T]) T {
	switch __gp_m6 := any(value).(type) {
	case validatedValue[T]:
		raw := __gp_m6.value

		return raw
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep PredicateOfRule[T any](0 p nat, rule Rule[T, p]) Predicate
func PredicateOfRule[T any](rule Rule[T]) Predicate {
	switch __gp_m7 := any(rule).(type) {
	case ruleValue[T]:
		predicate := __gp_m7.predicate

		return predicate
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep PredicateOf[T any](0 p nat, value Validated[T, p]) Predicate
func PredicateOf[T any](value Validated[T]) Predicate {
	switch __gp_m8 := any(value).(type) {
	case validatedValue[T]:
		predicate := __gp_m8.predicate

		return predicate
	default:
		panic("goplus: impossible enum value in match")
	}
}

func PredicateEqual(left Predicate, right Predicate) bool {
	switch __gp_m9 := any(left).(type) {
	case Named:
		leftID := __gp_m9.ID

		switch __gp_m10 := any(right).(type) {
		case Named:
			rightID := __gp_m10.ID
			return leftID == rightID
		case Both:
			return false
		default:
			panic("goplus: impossible enum value in match")
		}
	case Both:
		leftA := __gp_m9.Left
		leftB := __gp_m9.Right

		switch __gp_m11 := any(right).(type) {
		case Named:
			return false
		case Both:
			rightA := __gp_m11.Left
			rightB := __gp_m11.Right

			return PredicateEqual(leftA, rightA) && PredicateEqual(leftB, rightB)
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

// Revalidate is statically same-predicate in Go+ and checks the retained witness
// so erased plain-Go callers cannot mix proofs from different rules.
//
//goplus:dep Revalidate[T any](0 p nat, rule Rule[T, p], value Validated[T, p]) bool
func Revalidate[T any](rule Rule[T], value Validated[T]) bool {
	if !PredicateEqual(PredicateOfRule(rule), PredicateOf(value)) {
		return false
	}
	return IsValid(rule, Value(value))
}

// Map applies an arbitrary transformation and revalidates because ordinary Go
// functions are not proofs that p is preserved.
//
//goplus:dep Map[T any](0 p nat, value Validated[T, p], transform func(T) T) Outcome[T, p]
func Map[T any](value Validated[T], transform func(T) T) Outcome[T] {
	if transform == nil {
		panic("validate: nil transform")
	}
	switch __gp_m12 := any(value).(type) {
	case validatedValue[T]:
		raw := __gp_m12.value
		rule := __gp_m12.rule

		return Validate(rule, transform(raw))
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep FailuresOf[T any](0 p nat, outcome Outcome[T, p]) Failures
func FailuresOf[T any](outcome Outcome[T]) Failures {
	switch __gp_m13 := any(outcome).(type) {
	case Accepted[T]:
		return nil
	case Rejected[T]:
		failures := __gp_m13.Failures
		return failures
	default:
		panic("goplus: impossible enum value in match")
	}
}

// Error adapts a rule to conventional error-returning Go interfaces such as
// config.Validator while retaining Failures as the concrete error value.
//
//goplus:dep Error[T any](0 p nat, rule Rule[T, p], value T) error
func Error[T any](rule Rule[T], value T) error {
	failures := Check(rule, value)
	if len(failures) == 0 {
		return nil
	}
	return failures
}

type ConfigValidator[T any] struct{ Rule Rule[T] }

func (validator ConfigValidator[T]) Validate(value T) error { return Error(validator.Rule, value) }

//goplus:dep AsConfigValidator[T any](0 p nat, rule Rule[T, p]) ConfigValidator[T]
func AsConfigValidator[T any](rule Rule[T]) ConfigValidator[T] {
	return ConfigValidator[T]{Rule: rule}
}
