// Code generated by goplus from process.gp. DO NOT EDIT.
//goplus:v v0.24.1

// Package process runs external commands while preserving structured failure
// information and allowing output to be captured, streamed, or both.
package process

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
)

type Spec struct {
	Path      string
	Args      []string
	Dir       string
	Env       []string
	Stdin     io.Reader
	Stdout    io.Writer
	Stderr    io.Writer
	Sensitive bool
}

type Output struct {
	Stdout []byte
	Stderr []byte
}

type Failure struct {
	Path   string
	Args   []string
	Code   int
	Stderr string
	Cause  error
}

func (e *Failure) Error() string {
	name := e.Path
	if !e.SensitiveArgs() && len(e.Args) > 0 {
		name += " " + fmt.Sprint(e.Args)
	}
	if e.Stderr != "" {
		return fmt.Sprintf("%s: exit %d: %s", name, e.Code, e.Stderr)
	}
	return fmt.Sprintf("%s: exit %d: %v", name, e.Code, e.Cause)
}
func (e *Failure) Unwrap() error       { return e.Cause }
func (e *Failure) SensitiveArgs() bool { return e.Args == nil }

func Run(ctx context.Context, spec Spec) (Output, error) {
	var outBuf, errBuf bytes.Buffer
	cmd := exec.CommandContext(ctx, spec.Path, spec.Args...)
	cmd.Dir, cmd.Stdin = spec.Dir, spec.Stdin
	if spec.Env != nil {
		cmd.Env = append(os.Environ(), spec.Env...)
	}
	cmd.Stdout = io.MultiWriter(&outBuf, writerOrDiscard(spec.Stdout))
	cmd.Stderr = io.MultiWriter(&errBuf, writerOrDiscard(spec.Stderr))
	err := cmd.Run()
	out := Output{Stdout: outBuf.Bytes(), Stderr: errBuf.Bytes()}
	if err == nil {
		return out, nil
	}
	code := -1
	var exit *exec.ExitError
	if errors.As(err, &exit) {
		code = exit.ExitCode()
	}
	args := append([]string(nil), spec.Args...)
	stderr := string(bytes.TrimSpace(out.Stderr))
	if spec.Sensitive {
		args = nil
		stderr = ""
	}
	return out, &Failure{Path: spec.Path, Args: args, Code: code, Stderr: stderr, Cause: err}
}

func writerOrDiscard(w io.Writer) io.Writer {
	if w == nil {
		return io.Discard
	}
	return w
}
