// Code generated by goplus from route.gp. DO NOT EDIT.
//goplus:v v0.25.0

// Package route provides immutable, pattern-indexed HTTP route values. Pattern
// identities are opt-in natural indices: Go+ checks them, generated Go retains
// IDs for erased-boundary guards, and ordinary net/http remains the wire API.
package route

import (
	"fmt"
	"net/http"
	"strings"
)

//goplus:enum SegmentKind
type SegmentKind interface{ isSegmentKind() }

//goplus:variant (SegmentKind) StaticKind()
type StaticKind struct{}

func (StaticKind) isSegmentKind() {}

//goplus:variant (SegmentKind) ParameterKind()
type ParameterKind struct{}

func (ParameterKind) isSegmentKind() {}

//goplus:variant (SegmentKind) WildcardKind()
type WildcardKind struct{}

func (WildcardKind) isSegmentKind() {}

// SegmentKindCases selects one handler per SegmentKind variant for SegmentKindFold.
type SegmentKindCases[R any] struct {
	StaticKind    func() R
	ParameterKind func() R
	WildcardKind  func() R
}

// SegmentKindFold reduces SegmentKind by one-level case analysis.
func SegmentKindFold[R any](s SegmentKind, cs SegmentKindCases[R]) R {
	switch any(s).(type) {
	case StaticKind:
		return cs.StaticKind()
	case ParameterKind:
		return cs.ParameterKind()
	case WildcardKind:
		return cs.WildcardKind()
	default:
		panic("goplus: impossible enum value in SegmentKindFold")
	}
}

// SegmentKindEqOverrides carries optional per-variant hooks for SegmentKindEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type SegmentKindEqOverrides struct {
	StaticKind    func(x, y StaticKind) (eq, handled bool)
	ParameterKind func(x, y ParameterKind) (eq, handled bool)
	WildcardKind  func(x, y WildcardKind) (eq, handled bool)
}

// SegmentKindEqualWith reports structural equality of a and b under ov.
func SegmentKindEqualWith(a, b SegmentKind, ov SegmentKindEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case StaticKind:
		y, ok := any(b).(StaticKind)
		if !ok {
			return false
		}
		if ov.StaticKind != nil {
			if eq, handled := ov.StaticKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ParameterKind:
		y, ok := any(b).(ParameterKind)
		if !ok {
			return false
		}
		if ov.ParameterKind != nil {
			if eq, handled := ov.ParameterKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case WildcardKind:
		y, ok := any(b).(WildcardKind)
		if !ok {
			return false
		}
		if ov.WildcardKind != nil {
			if eq, handled := ov.WildcardKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// SegmentKindEqual reports structural equality of a and b.
func SegmentKindEqual(a, b SegmentKind) bool {
	return SegmentKindEqualWith(a, b, SegmentKindEqOverrides{})
}

type Segment struct {
	Kind SegmentKind
	Text string
	Name string
}

// Capability makes middleware effects explicit instead of hiding them in an
// arbitrary handler wrapper.
//
//goplus:enum Capability
type Capability interface{ isCapability() }

//goplus:variant (Capability) ObserveRequest()
type ObserveRequest struct{}

func (ObserveRequest) isCapability() {}

//goplus:variant (Capability) WriteHeaders()
type WriteHeaders struct{}

func (WriteHeaders) isCapability() {}

//goplus:variant (Capability) ReadBody()
type ReadBody struct{}

func (ReadBody) isCapability() {}

//goplus:variant (Capability) MutateState()
type MutateState struct{}

func (MutateState) isCapability() {}

// CapabilityCases selects one handler per Capability variant for CapabilityFold.
type CapabilityCases[R any] struct {
	ObserveRequest func() R
	WriteHeaders   func() R
	ReadBody       func() R
	MutateState    func() R
}

// CapabilityFold reduces Capability by one-level case analysis.
func CapabilityFold[R any](v Capability, cs CapabilityCases[R]) R {
	switch any(v).(type) {
	case ObserveRequest:
		return cs.ObserveRequest()
	case WriteHeaders:
		return cs.WriteHeaders()
	case ReadBody:
		return cs.ReadBody()
	case MutateState:
		return cs.MutateState()
	default:
		panic("goplus: impossible enum value in CapabilityFold")
	}
}

// CapabilityEqOverrides carries optional per-variant hooks for CapabilityEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type CapabilityEqOverrides struct {
	ObserveRequest func(x, y ObserveRequest) (eq, handled bool)
	WriteHeaders   func(x, y WriteHeaders) (eq, handled bool)
	ReadBody       func(x, y ReadBody) (eq, handled bool)
	MutateState    func(x, y MutateState) (eq, handled bool)
}

// CapabilityEqualWith reports structural equality of a and b under ov.
func CapabilityEqualWith(a, b Capability, ov CapabilityEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case ObserveRequest:
		y, ok := any(b).(ObserveRequest)
		if !ok {
			return false
		}
		if ov.ObserveRequest != nil {
			if eq, handled := ov.ObserveRequest(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case WriteHeaders:
		y, ok := any(b).(WriteHeaders)
		if !ok {
			return false
		}
		if ov.WriteHeaders != nil {
			if eq, handled := ov.WriteHeaders(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ReadBody:
		y, ok := any(b).(ReadBody)
		if !ok {
			return false
		}
		if ov.ReadBody != nil {
			if eq, handled := ov.ReadBody(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case MutateState:
		y, ok := any(b).(MutateState)
		if !ok {
			return false
		}
		if ov.MutateState != nil {
			if eq, handled := ov.MutateState(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// CapabilityEqual reports structural equality of a and b.
func CapabilityEqual(a, b Capability) bool {
	return CapabilityEqualWith(a, b, CapabilityEqOverrides{})
}

//goplus:total ObserveRequestID() nat
func ObserveRequestID() int { return 1 }

//goplus:total WriteHeadersID() nat
func WriteHeadersID() int { return 2 }

//goplus:total ReadBodyID() nat
func ReadBodyID() int { return 3 }

//goplus:total MutateStateID() nat
func MutateStateID() int { return 4 }

// Middleware[c] carries one declared capability c.
//
//goplus:enum Middleware[c nat]
//goplus:derive off
type Middleware interface{ isMiddleware() }

//goplus:variant (Middleware) middlewareValue(ID int, Capability Capability, Wrap func(http.Handler) http.Handler) Middleware[c]
type middlewareValue struct {
	iD         int
	capability Capability
	wrap       func(http.Handler) http.Handler
}

func (middlewareValue) isMiddleware() {}

// Pattern[p] is a parsed route pattern with singleton identity p.
//
//goplus:enum Pattern[p nat]
//goplus:derive off
type Pattern interface{ isPattern() }

//goplus:variant (Pattern) patternValue(ID int, Text string, Segments []Segment, Names []string) Pattern[p]
type patternValue struct {
	iD       int
	text     string
	segments []Segment
	names    []string
}

func (patternValue) isPattern() {}

//goplus:enum ParseOutcome[p nat]
type ParseOutcome interface{ isParseOutcome() }

//goplus:variant (ParseOutcome) PatternParsed(Pattern Pattern[p])
type PatternParsed struct {
	Pattern Pattern
}

func (PatternParsed) isParseOutcome() {}

//goplus:variant (ParseOutcome) InvalidPattern(Message string)
type InvalidPattern struct {
	Message string
}

func (InvalidPattern) isParseOutcome() {}

// ParseOutcomeCases selects one handler per ParseOutcome variant for ParseOutcomeFold.
type ParseOutcomeCases[R any] struct {
	PatternParsed  func(Pattern Pattern) R
	InvalidPattern func(Message string) R
}

// ParseOutcomeFold reduces ParseOutcome by one-level case analysis.
func ParseOutcomeFold[R any](p ParseOutcome, cs ParseOutcomeCases[R]) R {
	switch m := any(p).(type) {
	case PatternParsed:
		return cs.PatternParsed(m.Pattern)
	case InvalidPattern:
		return cs.InvalidPattern(m.Message)
	default:
		panic("goplus: impossible enum value in ParseOutcomeFold")
	}
}

// Request[p] carries exactly the parameter environment produced by Pattern[p].
//
//goplus:enum Request[p nat]
//goplus:derive off
type Request interface{ isRequest() }

//goplus:variant (Request) requestValue(PatternID int, PatternText string, Writer http.ResponseWriter, Raw *http.Request, Params map[string]string) Request[p]
type requestValue struct {
	patternID   int
	patternText string
	writer      http.ResponseWriter
	raw         *http.Request
	params      map[string]string
}

func (requestValue) isRequest() {}

// Handler[p] is sealed handler code for Pattern[p].
//
//goplus:enum Handler[p nat]
//goplus:derive off
type Handler interface{ isHandler() }

//goplus:variant (Handler) handlerValue(PatternID int, PatternText string, Run func(Request[p])) Handler[p]
type handlerValue struct {
	patternID   int
	patternText string
	run         func(Request)
}

func (handlerValue) isHandler() {}

// ParamKey[T,p] decodes one named parameter belonging to Pattern[p].
//
//goplus:enum ParamKey[T any, p nat]
//goplus:derive off
type ParamKey[T any] interface{ isParamKey(T) }

//goplus:variant (ParamKey[T]) paramKeyValue(PatternID int, PatternText string, Name string, Decode func(string) (T, bool)) ParamKey[T, p]
type paramKeyValue[T any] struct {
	patternID   int
	patternText string
	name        string
	decode      func(string) (T, bool)
}

func (paramKeyValue[T]) isParamKey(T) {}

//goplus:enum ParamResult[T any]
type ParamResult[T any] interface{ isParamResult(T) }

//goplus:variant (ParamResult[T]) ParamMissing()
type ParamMissing[T any] struct{}

func (ParamMissing[T]) isParamResult(T) {}

//goplus:variant (ParamResult[T]) ParamInvalid(Raw string)
type ParamInvalid[T any] struct {
	Raw string
}

func (ParamInvalid[T]) isParamResult(T) {}

//goplus:variant (ParamResult[T]) ParamFound(Value T)
type ParamFound[T any] struct {
	Value T
}

func (ParamFound[T]) isParamResult(T) {}

// ParamResultCases selects one handler per ParamResult variant for ParamResultFold.
type ParamResultCases[T any, R any] struct {
	ParamMissing func() R
	ParamInvalid func(Raw string) R
	ParamFound   func(Value T) R
}

// ParamResultFold reduces ParamResult[T] by one-level case analysis.
func ParamResultFold[T any, R any](p ParamResult[T], cs ParamResultCases[T, R]) R {
	switch m := any(p).(type) {
	case ParamMissing[T]:
		return cs.ParamMissing()
	case ParamInvalid[T]:
		return cs.ParamInvalid(m.Raw)
	case ParamFound[T]:
		return cs.ParamFound(m.Value)
	default:
		panic("goplus: impossible enum value in ParamResultFold")
	}
}

type Metadata struct {
	Method     string
	Pattern    string
	PatternID  int
	ParamNames []string
}

// Registered[p] ties handler metadata to Pattern[p].
//
//goplus:enum Registered[p nat]
//goplus:derive off
type Registered interface{ isRegistered() }

//goplus:variant (Registered) registeredValue(Metadata Metadata) Registered[p]
type registeredValue struct {
	metadata Metadata
}

func (registeredValue) isRegistered() {}

// RouteSet[s] is an immutable route-set fingerprint. Add changes s using a
// collision-free pairing function, so separately assembled sets cannot mix.
//
//goplus:enum RouteSet[s nat]
//goplus:derive off
type RouteSet interface{ isRouteSet() }

//goplus:variant (RouteSet) routeSetValue(Fingerprint int, Routes []Metadata) RouteSet[s]
type routeSetValue struct {
	fingerprint int
	routes      []Metadata
}

func (routeSetValue) isRouteSet() {}

//goplus:enum AddOutcome[s nat]
type AddOutcome interface{ isAddOutcome() }

//goplus:variant (AddOutcome) RouteAdded(Set RouteSet[s])
type RouteAdded struct {
	Set RouteSet
}

func (RouteAdded) isAddOutcome() {}

//goplus:variant (AddOutcome) RouteConflict(Existing Metadata, Incoming Metadata)
type RouteConflict struct {
	Existing Metadata
	Incoming Metadata
}

func (RouteConflict) isAddOutcome() {}

// AddOutcomeCases selects one handler per AddOutcome variant for AddOutcomeFold.
type AddOutcomeCases[R any] struct {
	RouteAdded    func(Set RouteSet) R
	RouteConflict func(Existing Metadata, Incoming Metadata) R
}

// AddOutcomeFold reduces AddOutcome by one-level case analysis.
func AddOutcomeFold[R any](a AddOutcome, cs AddOutcomeCases[R]) R {
	switch m := any(a).(type) {
	case RouteAdded:
		return cs.RouteAdded(m.Set)
	case RouteConflict:
		return cs.RouteConflict(m.Existing, m.Incoming)
	default:
		panic("goplus: impossible enum value in AddOutcomeFold")
	}
}

//goplus:total RouteSetID(set nat, route nat) nat
func RouteSetID(set int, route int) int {
	return ((set+route)*(set+route+1) + route) + 1
}

func parse(text string) ([]Segment, []string, error) {
	if text == "" || text[0] != '/' {
		return nil, nil, fmt.Errorf("route: pattern must begin with '/'")
	}
	if text == "/" {
		return nil, nil, nil
	}
	parts := strings.Split(strings.TrimPrefix(text, "/"), "/")
	segments := make([]Segment, 0, len(parts))
	names := make([]string, 0)
	seen := make(map[string]bool)
	for i, part := range parts {
		segment := Segment{Kind: StaticKind{}, Text: part}
		if part == "*" {
			segment = Segment{Kind: WildcardKind{}, Name: "*"}
		} else if strings.HasPrefix(part, "{") && strings.HasSuffix(part, "}") {
			body := part[1 : len(part)-1]
			name, expression, hasExpression := strings.Cut(body, ":")
			if name == "" {
				return nil, nil, fmt.Errorf("route: empty parameter")
			}
			if hasExpression && expression != "*" && expression != ".*" {
				return nil, nil, fmt.Errorf("route: typed core does not accept regex parameters")
			}
			if hasExpression {
				segment = Segment{Kind: WildcardKind{}, Name: name}
			} else {
				segment = Segment{Kind: ParameterKind{}, Name: name}
			}
		}
		if !SegmentKindEqual(segment.Kind, StaticKind{}) {
			if seen[segment.Name] {
				return nil, nil, fmt.Errorf("route: duplicate parameter %q", segment.Name)
			}
			if SegmentKindEqual(segment.Kind, WildcardKind{}) && i != len(parts)-1 {
				return nil, nil, fmt.Errorf("route: wildcard must be final")
			}
			seen[segment.Name] = true
			names = append(names, segment.Name)
		}
		segments = append(segments, segment)
	}
	return segments, names, nil
}

//goplus:dep Parse(id nat, text string) ParseOutcome[id]
func Parse(id int, text string) ParseOutcome {
	if id < 0 {
		return InvalidPattern{Message: "route: negative pattern ID"}
	}
	segments, names, err := parse(text)
	if err != nil {
		return InvalidPattern{Message: err.Error()}
	}
	return PatternParsed{Pattern: patternValue{iD: int(id), text: text, segments: segments, names: names}}
}

//goplus:dep MustPattern(id nat, text string) Pattern[id]
func MustPattern(id int, text string) Pattern {
	if id < 0 {
		panic("route: negative pattern ID")
	}
	segments, names, err := parse(text)
	if err != nil {
		panic(err)
	}
	return patternValue{iD: int(id), text: text, segments: segments, names: names}
}

//goplus:dep Text(0 p nat, pattern Pattern[p]) string
func Text(pattern Pattern) string {
	switch __gp_m0 := any(pattern).(type) {
	case patternValue:
		text := __gp_m0.text
		return text
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep PatternID(0 p nat, pattern Pattern[p]) int
func PatternID(pattern Pattern) int {
	switch __gp_m1 := any(pattern).(type) {
	case patternValue:
		id := __gp_m1.iD
		return id
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep NewMiddleware(id nat, capability Capability, wrap func(http.Handler) http.Handler) Middleware[id]
func NewMiddleware(id int, capability Capability, wrap func(http.Handler) http.Handler) Middleware {
	if id < 0 {
		panic("route: negative capability ID")
	}
	if wrap == nil {
		panic("route: nil middleware")
	}
	expected := 0
	switch any(capability).(type) {
	case ObserveRequest:
		expected = int(ObserveRequestID())
	case WriteHeaders:
		expected = int(WriteHeadersID())
	case ReadBody:
		expected = int(ReadBodyID())
	case MutateState:
		expected = int(MutateStateID())
	default:
		panic("goplus: impossible enum value in match")
	}
	if int(id) != expected {
		panic("route: capability ID does not match capability")
	}
	return middlewareValue{iD: int(id), capability: capability, wrap: wrap}
}

//goplus:dep Observer(wrap func(http.Handler) http.Handler) Middleware[ObserveRequestID()]
func Observer(wrap func(http.Handler) http.Handler) Middleware {
	return NewMiddleware(ObserveRequestID(), ObserveRequest{}, wrap)
}

//goplus:dep HeaderWriter(wrap func(http.Handler) http.Handler) Middleware[WriteHeadersID()]
func HeaderWriter(wrap func(http.Handler) http.Handler) Middleware {
	return NewMiddleware(WriteHeadersID(), WriteHeaders{}, wrap)
}

//goplus:dep BodyReader(wrap func(http.Handler) http.Handler) Middleware[ReadBodyID()]
func BodyReader(wrap func(http.Handler) http.Handler) Middleware {
	return NewMiddleware(ReadBodyID(), ReadBody{}, wrap)
}

//goplus:dep StateMutator(wrap func(http.Handler) http.Handler) Middleware[MutateStateID()]
func StateMutator(wrap func(http.Handler) http.Handler) Middleware {
	return NewMiddleware(MutateStateID(), MutateState{}, wrap)
}

//goplus:dep Wrap(0 c nat, middleware Middleware[c]) func(http.Handler) http.Handler
func Wrap(middleware Middleware) func(http.Handler) http.Handler {
	switch __gp_m3 := any(middleware).(type) {
	case middlewareValue:
		wrap := __gp_m3.wrap
		return wrap
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep CapabilityOf(0 c nat, middleware Middleware[c]) Capability
func CapabilityOf(middleware Middleware) Capability {
	switch __gp_m4 := any(middleware).(type) {
	case middlewareValue:
		capability := __gp_m4.capability
		return capability
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep NewHandler(0 p nat, pattern Pattern[p], run func(Request[p])) Handler[p]
func NewHandler(pattern Pattern, run func(Request)) Handler {
	if run == nil {
		panic("route: nil handler")
	}
	switch __gp_m5 := any(pattern).(type) {
	case patternValue:
		id := __gp_m5.iD
		text := __gp_m5.text
		return handlerValue{patternID: id, patternText: text, run: run}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep NewParamKey[T any](0 p nat, pattern Pattern[p], name string, decode func(string) (T, bool)) ParamKey[T, p]
func NewParamKey[T any](pattern Pattern, name string, decode func(string) (T, bool)) ParamKey[T] {
	if name == "" {
		panic("route: empty parameter name")
	}
	if decode == nil {
		panic("route: nil parameter decoder")
	}
	switch __gp_m6 := any(pattern).(type) {
	case patternValue:
		patternID := __gp_m6.iD
		text := __gp_m6.text
		names := __gp_m6.names

		found := false
		for _, declared := range names {
			if declared == name {
				found = true
			}
		}
		if !found {
			panic("route: parameter is not declared by pattern")
		}
		return paramKeyValue[T]{patternID: patternID, patternText: text, name: name, decode: decode}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep Param[T any](0 p nat, request Request[p], key ParamKey[T, p]) ParamResult[T]
func Param[T any](request Request, key ParamKey[T]) ParamResult[T] {
	switch __gp_m7 := any(request).(type) {
	case requestValue:
		patternID := __gp_m7.patternID
		patternText := __gp_m7.patternText
		params := __gp_m7.params

		switch __gp_m8 := any(key).(type) {
		case paramKeyValue[T]:
			keyPatternID := __gp_m8.patternID
			keyPatternText := __gp_m8.patternText
			name := __gp_m8.name
			decode := __gp_m8.decode

			if patternID != keyPatternID || patternText != keyPatternText {
				panic("route: parameter key belongs to another pattern")
			}
			raw, ok := params[name]
			if !ok {
				return ParamMissing[T]{}
			}
			value, ok := decode(raw)
			if !ok {
				return ParamInvalid[T]{Raw: raw}
			}
			return ParamFound[T]{Value: value}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep Raw(0 p nat, request Request[p]) *http.Request
func Raw(request Request) *http.Request {
	switch __gp_m9 := any(request).(type) {
	case requestValue:
		raw := __gp_m9.raw
		return raw
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep Writer(0 p nat, request Request[p]) http.ResponseWriter
func Writer(request Request) http.ResponseWriter {
	switch __gp_m10 := any(request).(type) {
	case requestValue:
		writer := __gp_m10.writer
		return writer
	default:
		panic("goplus: impossible enum value in match")
	}
}

func patternMatch(segments []Segment, path string) (map[string]string, bool) {
	parts := []string{}
	if path != "/" && path != "" {
		parts = strings.Split(strings.TrimPrefix(path, "/"), "/")
	}
	params := make(map[string]string)
	part := 0
	for _, segment := range segments {
		if SegmentKindEqual(segment.Kind, WildcardKind{}) {
			params[segment.Name] = strings.Join(parts[part:], "/")
			part = len(parts)
			break
		}
		if part >= len(parts) {
			return nil, false
		}
		if SegmentKindEqual(segment.Kind, StaticKind{}) {
			if parts[part] != segment.Text {
				return nil, false
			}
		} else {
			params[segment.Name] = parts[part]
		}
		part++
	}
	return params, part == len(parts)
}

// Adapt turns a pattern-indexed handler into ordinary net/http. It validates
// the path independently, making std/http/route useful without any router.
//
//goplus:dep Adapt(0 p nat, pattern Pattern[p], handler Handler[p]) http.Handler
func Adapt(pattern Pattern, handler Handler) http.Handler {
	switch __gp_m11 := any(pattern).(type) {
	case patternValue:
		patternID := __gp_m11.iD
		patternText := __gp_m11.text
		segments := __gp_m11.segments

		switch __gp_m12 := any(handler).(type) {
		case handlerValue:
			handlerPatternID := __gp_m12.patternID
			handlerPatternText := __gp_m12.patternText
			run := __gp_m12.run

			if patternID != handlerPatternID || patternText != handlerPatternText {
				panic("route: handler belongs to another pattern")
			}
			return http.HandlerFunc(func(writer http.ResponseWriter, raw *http.Request) {
				params, ok := patternMatch(segments, raw.URL.Path)
				if !ok {
					panic("route: handler invoked for a non-matching path")
				}
				run(requestValue{patternID: patternID, patternText: patternText, writer: writer, raw: raw, params: params})
			})
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep Register(method string, 0 p nat, pattern Pattern[p]) Registered[p]
func Register(method string, pattern Pattern) Registered {
	if method == "" {
		panic("route: empty method")
	}
	switch __gp_m13 := any(pattern).(type) {
	case patternValue:
		id := __gp_m13.iD
		text := __gp_m13.text
		names := __gp_m13.names

		return registeredValue{metadata: Metadata{Method: strings.ToUpper(method), Pattern: text, PatternID: id, ParamNames: append([]string(nil), names...)}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep Empty() RouteSet[0]
func Empty() RouteSet { return routeSetValue{fingerprint: 0, routes: nil} }

func routeSetFingerprint(set int, route int) int { return (set+route)*(set+route+1) + route + 1 }

//goplus:dep Add(0 s nat, routeID nat, set RouteSet[s], route Registered[routeID]) AddOutcome[RouteSetID(s, routeID)]
func Add(routeID int, set RouteSet, route Registered) AddOutcome {
	switch __gp_m14 := any(set).(type) {
	case routeSetValue:
		fingerprint := __gp_m14.fingerprint
		routes := __gp_m14.routes

		switch __gp_m15 := any(route).(type) {
		case registeredValue:
			incoming := __gp_m15.metadata

			for _, existing := range routes {
				if existing.Method == incoming.Method && existing.Pattern == incoming.Pattern {
					return RouteConflict{Existing: existing, Incoming: incoming}
				}
			}
			owned := append([]Metadata(nil), routes...)
			owned = append(owned, incoming)
			return RouteAdded{Set: routeSetValue{fingerprint: routeSetFingerprint(fingerprint, int(routeID)), routes: owned}}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep Routes(0 s nat, set RouteSet[s]) []Metadata
func Routes(set RouteSet) []Metadata {
	switch __gp_m16 := any(set).(type) {
	case routeSetValue:
		routes := __gp_m16.routes

		owned := append([]Metadata(nil), routes...)
		for i := range owned {
			owned[i].ParamNames = append([]string(nil), owned[i].ParamNames...)
		}
		return owned
	default:
		panic("goplus: impossible enum value in match")
	}
}
