// Code generated by gpp from kleene.gpp. DO NOT EDIT.
//gpp:v v0.13.0

// Package kleene is Kleene's strong three-valued logic (K3): the truth
// value of a proposition that may be undetermined — a header not yet seen,
// a stream half not yet observed, a sensor not yet read. Connectives
// short-circuit on their dominant value (And on False, Or on True) and
// absorb Undetermined otherwise, so a partial observation set yields a
// definite answer exactly when one is logically forced.
//
// Authored in G++ and distributed as generated Go — consumers never need
// the gpp toolchain.
package kleene

import "iter"

// Value is a K3 truth value.
//
//gpp:enum Value
type Value interface{ isValue() }

// True is definitely true.
//
//gpp:variant (Value) True
type True struct{}

func (True) isValue() {}

// False is definitely false.
//
//gpp:variant (Value) False
type False struct{}

func (False) isValue() {}

// Undetermined is not yet known: the evidence seen so far forces
// neither True nor False.
//
//gpp:variant (Value) Undetermined
type Undetermined struct{}

func (Undetermined) isValue() {}

// ValueCases selects one handler per Value variant for Fold.
type ValueCases[R any] struct {
	True         func() R
	False        func() R
	Undetermined func() R
}

// Fold reduces Value by one-level case analysis.
func Fold[R any](v Value, cs ValueCases[R]) R {
	switch any(v).(type) {
	case True:
		return cs.True()
	case False:
		return cs.False()
	case Undetermined:
		return cs.Undetermined()
	default:
		panic("gpp: impossible enum value in Fold")
	}
}

// ValueEqOverrides carries optional per-variant hooks for ValueEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type ValueEqOverrides struct {
	True         func(x, y True) (eq, handled bool)
	False        func(x, y False) (eq, handled bool)
	Undetermined func(x, y Undetermined) (eq, handled bool)
}

// ValueEqualWith reports structural equality of a and b under ov.
func ValueEqualWith(a, b Value, ov ValueEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case True:
		y, ok := any(b).(True)
		if !ok {
			return false
		}
		if ov.True != nil {
			if eq, handled := ov.True(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case False:
		y, ok := any(b).(False)
		if !ok {
			return false
		}
		if ov.False != nil {
			if eq, handled := ov.False(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case Undetermined:
		y, ok := any(b).(Undetermined)
		if !ok {
			return false
		}
		if ov.Undetermined != nil {
			if eq, handled := ov.Undetermined(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// ValueEqual reports structural equality of a and b.
func ValueEqual(a, b Value) bool {
	return ValueEqualWith(a, b, ValueEqOverrides{})
}

// FromBool embeds two-valued logic.
func FromBool(b bool) Value {
	if b {
		return True{}
	}
	return False{}
}

// Def exits at the comma-ok boundary: (truth, determined). An
// Undetermined value reports ok=false with a false truth.
func Def(v Value) (bool, bool) {
	switch any(v).(type) {
	case True:
		return true, true
	case False:
		return false, true
	case Undetermined:
		return false, false
	default:
		panic("gpp: impossible enum value in match")
	}
}

// Resolve collapses Undetermined to the caller's default.
func Resolve(v Value, undetermined bool) bool {
	switch any(v).(type) {
	case True:
		return true
	case False:
		return false
	case Undetermined:
		return undetermined
	default:
		panic("gpp: impossible enum value in match")
	}
}

// Not is K3 negation: Undetermined passes through.
func Not(v Value) Value {
	switch any(v).(type) {
	case True:
		return False{}
	case False:
		return True{}
	case Undetermined:
		return Undetermined{}
	default:
		panic("gpp: impossible enum value in match")
	}
}

// And is K3 conjunction: False dominates, then Undetermined absorbs.
func And(a Value, b Value) Value {
	switch any(a).(type) {
	case False:
		return False{}
	case Undetermined:
		switch any(b).(type) {
		case False:
			return False{}
		case True:
			return Undetermined{}
		case Undetermined:
			return Undetermined{}
		default:
			panic("gpp: impossible enum value in match")
		}
	case True:
		return b
	default:
		panic("gpp: impossible enum value in match")
	}
}

// Or is K3 disjunction: True dominates, then Undetermined absorbs.
func Or(a Value, b Value) Value {
	switch any(a).(type) {
	case True:
		return True{}
	case Undetermined:
		switch any(b).(type) {
		case True:
			return True{}
		case False:
			return Undetermined{}
		case Undetermined:
			return Undetermined{}
		default:
			panic("gpp: impossible enum value in match")
		}
	case False:
		return b
	default:
		panic("gpp: impossible enum value in match")
	}
}

// All is n-ary And over a sequence, short-circuiting on the first False.
// The empty sequence is True (the conjunctive identity).
func All(vs iter.Seq[Value]) Value {
	var acc Value = True{}
	for v := range vs {
		switch any(v).(type) {
		case False:
			return False{}
		case Undetermined:
			acc = Undetermined{}
		case True:
			// no-op: True is the identity.
		default:
			panic("gpp: impossible enum value in match")
		}
	}
	return acc
}

// Any is n-ary Or over a sequence, short-circuiting on the first True.
// The empty sequence is False (the disjunctive identity).
func Any(vs iter.Seq[Value]) Value {
	var acc Value = False{}
	for v := range vs {
		switch any(v).(type) {
		case True:
			return True{}
		case Undetermined:
			acc = Undetermined{}
		case False:
			// no-op: False is the identity.
		default:
			panic("gpp: impossible enum value in match")
		}
	}
	return acc
}
