Feature: Lowering generic method declarations
  A generic method lowers to a package-level generic function: the receiver
  becomes the first parameter, receiver type parameters (with constraints
  copied from the type declaration) precede the method's own, and a
  //goplus:method marker makes the emitted artifact self-describing. Emitted
  files are gofmt-clean, headed, and committed beside their source.

  Scenario: A value-receiver generic method lowers to a package function
    Given a Go+ file "stack.gp":
      """
      package stack

      type Stack[T any] struct{ items []T }

      // Map transforms every element.
      func (s Stack[T]) Map[U any](f func(T) U) Stack[U] {
      	out := Stack[U]{items: make([]U, 0, len(s.items))}
      	for _, x := range s.items {
      		out.items = append(out.items, f(x))
      	}
      	return out
      }
      """
    When I run goplus with arguments "gen ."
    Then the exit code is 0
    And the file "stack_gp.go" contains:
      """
      // Code generated by goplus from stack.gp. DO NOT EDIT.
      """
    And the file "stack_gp.go" contains:
      """
      // Map transforms every element.
      //
      //goplus:method (Stack[T]) Map[U]
      func Map[T any, U any](s Stack[T], f func(T) U) Stack[U] {
      """
    And the file "stack_gp.go" is valid Go

  Scenario: Pointer receivers are preserved as pointer first parameters
    Given a Go+ file "stack.gp":
      """
      package stack

      type Stack[T any] struct{ items []T }

      func (s *Stack[T]) Push[V any](v V, conv func(V) T) {
      	s.items = append(s.items, conv(v))
      }
      """
    When I run goplus with arguments "gen ."
    Then the exit code is 0
    And the file "stack_gp.go" contains:
      """
      //goplus:method (*Stack[T]) Push[V]
      func Push[T any, V any](s *Stack[T], v V, conv func(V) T) {
      """

  Scenario: Receiver constraints are copied and renamed from the type declaration
    Given a Go+ file "pair.gp":
      """
      package pair

      type Pair[K comparable, V any] struct {
      	k K
      	v V
      }

      func (p Pair[A, B]) Swap[X any](x X) (B, A, X) {
      	return p.v, p.k, x
      }
      """
    When I run goplus with arguments "gen ."
    Then the exit code is 0
    And the file "pair_gp.go" contains:
      """
      func Swap[A comparable, B any, X any](p Pair[A, B], x X) (B, A, X) {
      """

  Scenario: A generic method on a non-generic receiver adds only its own type parameters
    Given a Go+ file "reg.gp":
      """
      package reg

      type Registry struct{ names []string }

      func (r Registry) Collect[U any](f func(string) U) []U {
      	out := make([]U, 0, len(r.names))
      	for _, n := range r.names {
      		out = append(out, f(n))
      	}
      	return out
      }
      """
    When I run goplus with arguments "gen ."
    Then the exit code is 0
    And the file "reg_gp.go" contains:
      """
      //goplus:method (Registry) Collect[U]
      func Collect[U any](r Registry, f func(string) U) []U {
      """

  Scenario: The receiver type may be declared in an authored Go file
    Given a file "types.go":
      """
      package mixed

      type Box[T any] struct{ v T }
      """
    And a Go+ file "box.gp":
      """
      package mixed

      func (b Box[T]) Convert[U any](f func(T) U) U {
      	return f(b.v)
      }
      """
    When I run goplus with arguments "gen ."
    Then the exit code is 0
    And the file "box_gp.go" contains:
      """
      func Convert[T any, U any](b Box[T], f func(T) U) U {
      """

  Scenario: Plain Go passes through with only the header added
    Given a Go+ file "plain.gp":
      """
      package plain

      import "fmt"

      // Greet says hello.
      func Greet(name string) string {
      	return fmt.Sprintf("hello, %s", name)
      }
      """
    When I run goplus with arguments "gen ."
    Then the exit code is 0
    And the file "plain_gp.go" is exactly the header for "plain.gp" plus the source

  Scenario: Generation is deterministic and idempotent
    Given a Go+ file "stack.gp":
      """
      package stack

      type Stack[T any] struct{ items []T }

      func (s Stack[T]) Map[U any](f func(T) U) Stack[U] {
      	return Stack[U]{}
      }
      """
    When I run goplus with arguments "gen ."
    And I record the generated files
    And I run goplus with arguments "gen ."
    Then the generated files are unchanged
    And running goplus with arguments "gen -check ." exits with 0

  Scenario: -check reports stale output without writing
    Given a Go+ file "stack.gp":
      """
      package stack

      type Stack[T any] struct{ items []T }

      func (s Stack[T]) Map[U any](f func(T) U) Stack[U] {
      	return Stack[U]{}
      }
      """
    When I run goplus with arguments "gen -check ."
    Then the exit code is 1
    And stderr contains "stale generated code"
    And the file "stack_gp.go" does not exist

  Scenario: An orphaned generated file is removed
    Given a file "gone_gp.go":
      """
      // Code generated by goplus from gone.gp. DO NOT EDIT.

      package stack
      """
    When I run goplus with arguments "gen ."
    Then the exit code is 0
    And the file "gone_gp.go" does not exist

  Scenario: A hand-written file at the output path is never clobbered
    Given a file "stack_gp.go":
      """
      package stack

      // hand-written, despite the suggestive name
      func Precious() {}
      """
    And a Go+ file "stack.gp":
      """
      package stack

      type Stack[T any] struct{ items []T }

      func (s Stack[T]) Map[U any](f func(T) U) Stack[U] {
      	return Stack[U]{}
      }
      """
    When I run goplus with arguments "gen ."
    Then the exit code is 2
    And stderr contains "refusing to overwrite"
    And the file "stack_gp.go" contains:
      """
      func Precious() {}
      """
