Feature: Lowering generic method declarations
  A generic method lowers to a package-level generic function: the receiver
  becomes the first parameter, receiver type parameters (with constraints
  copied from the type declaration) precede the method's own, and a
  //gpp:method marker makes the emitted artifact self-describing. Emitted
  files are gofmt-clean, headed, and committed beside their source.

  Scenario: A value-receiver generic method lowers to a package function
    Given a G++ file "stack.gpp":
      """
      package stack

      type Stack[T any] struct{ items []T }

      // Map transforms every element.
      func (s Stack[T]) Map[U any](f func(T) U) Stack[U] {
      	out := Stack[U]{items: make([]U, 0, len(s.items))}
      	for _, x := range s.items {
      		out.items = append(out.items, f(x))
      	}
      	return out
      }
      """
    When I run gpp with arguments "gen ."
    Then the exit code is 0
    And the file "stack_gpp.go" contains:
      """
      // Code generated by gpp from stack.gpp. DO NOT EDIT.
      """
    And the file "stack_gpp.go" contains:
      """
      // Map transforms every element.
      //
      //gpp:method (Stack[T]) Map[U]
      func StackMap[T any, U any](s Stack[T], f func(T) U) Stack[U] {
      """
    And the file "stack_gpp.go" is valid Go

  Scenario: Pointer receivers are preserved as pointer first parameters
    Given a G++ file "stack.gpp":
      """
      package stack

      type Stack[T any] struct{ items []T }

      func (s *Stack[T]) Push[V any](v V, conv func(V) T) {
      	s.items = append(s.items, conv(v))
      }
      """
    When I run gpp with arguments "gen ."
    Then the exit code is 0
    And the file "stack_gpp.go" contains:
      """
      //gpp:method (*Stack[T]) Push[V]
      func StackPush[T any, V any](s *Stack[T], v V, conv func(V) T) {
      """

  Scenario: Receiver constraints are copied and renamed from the type declaration
    Given a G++ file "pair.gpp":
      """
      package pair

      type Pair[K comparable, V any] struct {
      	k K
      	v V
      }

      func (p Pair[A, B]) Swap[X any](x X) (B, A, X) {
      	return p.v, p.k, x
      }
      """
    When I run gpp with arguments "gen ."
    Then the exit code is 0
    And the file "pair_gpp.go" contains:
      """
      func PairSwap[A comparable, B any, X any](p Pair[A, B], x X) (B, A, X) {
      """

  Scenario: A generic method on a non-generic receiver adds only its own type parameters
    Given a G++ file "reg.gpp":
      """
      package reg

      type Registry struct{ names []string }

      func (r Registry) Collect[U any](f func(string) U) []U {
      	out := make([]U, 0, len(r.names))
      	for _, n := range r.names {
      		out = append(out, f(n))
      	}
      	return out
      }
      """
    When I run gpp with arguments "gen ."
    Then the exit code is 0
    And the file "reg_gpp.go" contains:
      """
      //gpp:method (Registry) Collect[U]
      func RegistryCollect[U any](r Registry, f func(string) U) []U {
      """

  Scenario: The receiver type may be declared in an authored Go file
    Given a file "types.go":
      """
      package mixed

      type Box[T any] struct{ v T }
      """
    And a G++ file "box.gpp":
      """
      package mixed

      func (b Box[T]) Convert[U any](f func(T) U) U {
      	return f(b.v)
      }
      """
    When I run gpp with arguments "gen ."
    Then the exit code is 0
    And the file "box_gpp.go" contains:
      """
      func BoxConvert[T any, U any](b Box[T], f func(T) U) U {
      """

  Scenario: Plain Go passes through with only the header added
    Given a G++ file "plain.gpp":
      """
      package plain

      import "fmt"

      // Greet says hello.
      func Greet(name string) string {
      	return fmt.Sprintf("hello, %s", name)
      }
      """
    When I run gpp with arguments "gen ."
    Then the exit code is 0
    And the file "plain_gpp.go" is exactly the header for "plain.gpp" plus the source

  Scenario: Generation is deterministic and idempotent
    Given a G++ file "stack.gpp":
      """
      package stack

      type Stack[T any] struct{ items []T }

      func (s Stack[T]) Map[U any](f func(T) U) Stack[U] {
      	return Stack[U]{}
      }
      """
    When I run gpp with arguments "gen ."
    And I record the generated files
    And I run gpp with arguments "gen ."
    Then the generated files are unchanged
    And running gpp with arguments "gen -check ." exits with 0

  Scenario: -check reports stale output without writing
    Given a G++ file "stack.gpp":
      """
      package stack

      type Stack[T any] struct{ items []T }

      func (s Stack[T]) Map[U any](f func(T) U) Stack[U] {
      	return Stack[U]{}
      }
      """
    When I run gpp with arguments "gen -check ."
    Then the exit code is 1
    And stderr contains "stale generated code"
    And the file "stack_gpp.go" does not exist

  Scenario: An orphaned generated file is removed
    Given a file "gone_gpp.go":
      """
      // Code generated by gpp from gone.gpp. DO NOT EDIT.

      package stack
      """
    When I run gpp with arguments "gen ."
    Then the exit code is 0
    And the file "gone_gpp.go" does not exist

  Scenario: A hand-written file at the output path is never clobbered
    Given a file "stack_gpp.go":
      """
      package stack

      // hand-written, despite the suggestive name
      func Precious() {}
      """
    And a G++ file "stack.gpp":
      """
      package stack

      type Stack[T any] struct{ items []T }

      func (s Stack[T]) Map[U any](f func(T) U) Stack[U] {
      	return Stack[U]{}
      }
      """
    When I run gpp with arguments "gen ."
    Then the exit code is 2
    And stderr contains "refusing to overwrite"
    And the file "stack_gpp.go" contains:
      """
      func Precious() {}
      """
