// Code generated by goplus from latch.gp. DO NOT EDIT.
//goplus:v v0.24.1

// Package latch is a one-shot quiescence rendezvous: an in-flight counter
// and a trip switch. Once tripped, the latch fires — closes Done — the
// moment the counter reaches zero (immediately, if it already is). The
// canonical use is graceful drain: stop admitting work, then wait for the
// work already in flight to finish.
//
// The hot path is lock-free: Inc, Dec, and Tripped are single atomic
// operations. Trip is idempotent; Done is closed exactly once.
//
// Late increments — an Inc that races past a fired rendezvous — do not
// re-open Done: callers must check Tripped before Inc, the same
// admission-gate discipline any drain requires.
//
// Authored in Go+ and distributed as generated Go — consumers never need
// the goplus toolchain.
package latch

import (
	"sync"
	"sync/atomic"
)

// Latch is the rendezvous. Construct with New; the zero value is not usable.
type Latch struct {
	tripped   atomic.Bool
	inflight  atomic.Int64
	done      chan struct{}
	tripOnce  sync.Once
	closeOnce sync.Once
}

// New constructs an untripped Latch with a zero in-flight count.
func New() *Latch {
	return &Latch{done: make(chan struct{})}
}

// Inc registers one unit of in-flight work. Lock-free. Callers must check
// Tripped() == false first; see the package comment.
func (l *Latch) Inc() {
	l.inflight.Add(1)
}

// Dec retires one unit of in-flight work. If the count reaches zero and the
// latch has been tripped, the rendezvous fires (Done closes). Lock-free on
// the non-firing path.
func (l *Latch) Dec() {
	if l.inflight.Add(-1) == 0 && l.tripped.Load() {
		l.closeOnce.Do(func() { close(l.done) })
	}
}

// Trip arms the rendezvous. Idempotent. If the in-flight count is already
// zero, Done closes immediately.
func (l *Latch) Trip() {
	l.tripOnce.Do(func() {
		l.tripped.Store(true)
		if l.inflight.Load() == 0 {
			l.closeOnce.Do(func() { close(l.done) })
		}
	})
}

// Tripped reports whether Trip has been called. Lock-free; one atomic load.
func (l *Latch) Tripped() bool {
	return l.tripped.Load()
}

// Done returns the channel closed when the rendezvous fires: after Trip,
// once in-flight reaches zero. Before Trip it never closes.
func (l *Latch) Done() <-chan struct{} {
	return l.done
}
