// Code generated by goplus from fsatomic.gp. DO NOT EDIT.
//goplus:v v0.25.0

// Package fsatomic safely replaces files by writing, syncing, renaming, and
// syncing the containing directory.
package fsatomic

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
)

func WriteFile(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".atomic-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	ok := false
	defer func() {
		if !ok {
			_ = os.Remove(tmpPath)
		}
	}()
	if err := tmp.Chmod(perm); err != nil {
		_ = tmp.Close()
		return err
	}
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return err
	}
	// Windows does not support opening a directory for fsync. Rename remains
	// atomic there; directory durability follows the platform's filesystem.
	if runtime.GOOS == "windows" {
		ok = true
		return nil
	}
	d, err := os.Open(dir)
	if err != nil {
		return fmt.Errorf("sync directory: %w", err)
	}
	err = d.Sync()
	closeErr := d.Close()
	if err != nil {
		return fmt.Errorf("sync directory: %w", err)
	}
	if closeErr != nil {
		return closeErr
	}
	ok = true
	return nil
}
