// Code generated by gpp from retry.gpp. DO NOT EDIT.
//gpp:v v0.13.0

// Package retry is a bounded, context-aware retry loop with exponential
// backoff: attempt, wait base·2^n capped at cap, honor ctx cancellation
// mid-wait, and surface the LAST error when attempts are exhausted — the
// loop every fetcher hand-rolls.
//
// Authored in G++ and distributed as generated Go — consumers never need
// the gpp toolchain.
package retry

import (
	"context"
	"time"
)

// Policy bounds the loop. Attempts is the total number of tries (>= 1;
// values < 1 are treated as 1). Base is the first backoff delay; each
// subsequent delay doubles, clamped to Cap (Cap <= 0 means uncapped).
type Policy struct {
	Attempts int
	Base     time.Duration
	Cap      time.Duration
}

// Do runs f up to p.Attempts times. It returns f's first success, or —
// after the final failure — the zero T and the last error. Between
// attempts it sleeps the backoff delay unless ctx is done first, in which
// case it returns the zero T and ctx's error immediately. A ctx already
// done before the first attempt still gets one attempt: f observes ctx
// itself (matching the attempt-then-check shape of hand-rolled loops).
func Do[T any](ctx context.Context, p Policy, f func(context.Context) (T, error)) (T, error) {
	attempts := p.Attempts
	if attempts < 1 {
		attempts = 1
	}
	var lastErr error
	delay := p.Base
	for i := 0; i < attempts; i++ {
		v, err := f(ctx)
		if err == nil {
			return v, nil
		}
		lastErr = err
		if i == attempts-1 {
			break
		}
		if delay > 0 {
			t := time.NewTimer(delay)
			select {
			case <-ctx.Done():
				t.Stop()
				var zero T
				return zero, ctx.Err()
			case <-t.C:
			}
			delay *= 2
			if p.Cap > 0 && delay > p.Cap {
				delay = p.Cap
			}
		}
	}
	var zero T
	return zero, lastErr
}
